effect(s) の訳を見直し
vuejs-translations/docs-ja pull request #1480
Opened 2023-06-26 12:28 UTC by jay-es

resolve #000 ←（`000` の部分を実際の issue 番号に書き換えてください）

2023-06-26 12:29 UTC, jay-es commented on src/api/built-in-components.md
> +**単一の**要素またはコンポーネントにアニメーションのトランジション効果を提供します。
「効果」が漏れていた
> Provides animated transition effects to a **single** element or component.

2023-06-26 12:29 UTC, jay-es commented on src/api/built-in-components.md
> +リスト内の**複数**の要素またはコンポーネントにトランジション効果を提供します。
（ついで）
ですます調に修正

2023-06-26 12:31 UTC, jay-es commented on src/guide/built-ins/transition.md
> +/* ネストされた要素の、交互のアニメーション効果の enter の遅延 */
翻訳改善
> /* delay enter of nested element for staggered effect */

2023-06-26 12:32 UTC, jay-es commented on src/guide/built-ins/transition.md
> +/* ネストされた要素の、交互アニメーション効果の enter の遅延 */
翻訳改善
> /* delay enter of nested element for staggered effect */

2023-06-26 12:35 UTC, jay-es commented on src/guide/extras/reactivity-in-depth.md
> +- `update()` 関数はプログラムの状態を変更するため、**副作用（side effect、略してエフェクト）** を発生させます。
原文のままだと意味が通りづらいので少しだけ意訳
> The `update()` function produces a **side effect**, or **effect** for short, because it modifies the state of the program.

2023-06-26 12:36 UTC, jay-es commented on src/guide/extras/reactivity-in-depth.md
> +JavaScript でプロパティにアクセスを傍受する方法は 2 つあります: [getter](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/get) / [setters](https://developer.mozilla.org/ja/docs/Web/JavaScript/Referen
（ついで）
複数形だと分かりづらいので修正

2023-06-27 00:37 UTC, kazupon requested changes
レビューしました！エフェクトの方が本来の意味を捉えることが出来るのでいいと思います！

2023-06-27 00:37 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +この時点で、依存関係を自動的に追跡し、依存関係が変更されるたびに再実行するエフェクトが作成しました。これを **リアクティブエフェクト（Reactive Effect）** と呼びます。
この文章、最後の"作成されました"が日本語として違和感あるのですが、原文を訳すとそういう訳になる感じですか？
(スマホで見ているので原文みれなくてすいません)

2023-06-27 10:53 UTC, jay-es commented on src/guide/extras/reactivity-in-depth.md
> +この時点で、依存関係を自動的に追跡し、依存関係が変更されるたびに再実行するエフェクトが作成しました。これを **リアクティブエフェクト（Reactive Effect）** と呼びます。
「エフェクトを」に修正しました:bow:
> we have created an effect that ...

2023-07-05 10:07 UTC, kazupon approved these changes
すいません。遅くなりました！
LGTMです！

2023-07-05 10:07 UTC, merged