「Guide > TypeScript > Overview」の翻訳
vuejs-translations/docs-ja pull request #297
Opened 2022-02-26 05:47 UTC by ryoheinan

resolve #45  
  
[src/guide/typescript/overview.md](https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/typescript/overview.md) の翻訳をしました。  
Vue 3 旧ドキュメントの翻訳を一部参考にさせていただきました。  

ドキュメントの翻訳は初めてなのでおかしい点などがあるかもしれませんが、よろしくお願いします。

2022-02-26 05:48 UTC, ryoheinan commented on src/guide/typescript/overview.md
> +- [Options API とともに TypeScript を使用する](./options-api)
ここの部分は別ページ（未翻訳）のタイトルに依存するので、暫定的なものとして翻訳しました。

2022-02-28 13:17 UTC, jay-es requested changes
全体的に意訳になっている箇所が見受けられるので、https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md にある通り、「一語一句翻訳」に修正お願いします:bow:

例えば最初の一文は以下のようになります
```
A type system like TypeScript can detect many common errors via static analysis at build time.
TypeScript のような型システムは、ビルド時に静的解析で多くの一般的なエラーを検出できます。
```

2022-02-28 13:17 UTC, jay-es commented on src/guide/typescript/overview.md
> +# TypeScript のサポート
そのまま翻訳し、「TypeScript で Vue を使用する」や「Vue と TypeScript の併用」などとしてください:pray:

2022-03-01 04:10 UTC, ryoheinan reviewed
全体的に修正しました
ご確認よろしくお願いします🙇

2022-03-01 04:10 UTC, ryoheinan commented on src/guide/typescript/overview.md
> +# TypeScript のサポート
90b115dc52a4cb8dfc23c74d9cfe6477a18010e9 にて修正しました。

2022-03-02 17:08 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
確認お願いします。

2022-03-02 17:08 UTC, kazupon commented on src/guide/typescript/overview.md
> +参照する:
`See also` は他の翻訳ドキュメントにおいて、`参照` という体言止めな訳でも意味は通じそうですので、そのように訳しておきましょう。

2022-03-03 01:51 UTC, ryoheinan commented on src/guide/typescript/overview.md
> +参照する:
64933cb8dcdab12d9279e7450532b00eba46c325 にて修正しました。

2022-03-03 01:52 UTC, ryoheinan reviewed
ナビゲーション部分が未翻訳だったことに気づいたので、追加で翻訳しました。

2022-03-05 15:56 UTC, kazupon approved these changes

2022-03-05 15:57 UTC, kazupon commented
自分が指摘した部分はよさそうです。
後は、jay-es さんの指摘部分お願いします。

2022-03-06 03:17 UTC, jay-es requested changes
すみませんが1点修正お願いします:pray:

2022-03-06 03:17 UTC, jay-es commented on src/guide/typescript/overview.md
> +<script setup lang="ts"></script>
閉じタグの削除をお願いします:pray:
```suggestion
<script setup lang="ts">
```

2022-03-06 05:07 UTC, ryoheinan commented on src/guide/typescript/overview.md
> +<script setup lang="ts"></script>
7de5be0e95c4b9e5e9be07ec8b4ebcd17a4f2425 にて修正しました！

2022-03-06 05:13 UTC, ryoheinan commented
@jay-es 
レビューありがとうございます。
指摘いただいた点を修正しましたので、確認よろしくお願いします🙇

2022-03-06 05:19 UTC, jay-es approved these changes
ありがとうございます:pray:

2022-03-06 05:20 UTC, merged