「Guide > TypeScript > TypeScript with Composition API」の翻訳
vuejs-translations/docs-ja pull request #298
Opened 2022-02-26 13:30 UTC by bobstrange

resolve #46 

## Note

以下ちょっと訳に困りました、いくつかは表記揺れしそうなので
用語集に追加した方が良いのかと思われます :thinking: 

- type-based declaration
	- 型ベースの宣言
- runtime declaration
	- 実行時宣言
- an object literal type
	- オブジェクトリテラル型
- generic, generic type
	- 基本型引数として、必要が有る場合のみジェネリック型としました
	- 参照 [TypeScript deep dive](https://typescript-jp.gitbook.io/deep-dive/type-system/generics) 
- reactive destructure
- unwrap
	- [他](src/api/sfc-script-setup.md) [他2](src/guide/reusability/composables.md) でアンラップとしているので合わせましたが、unwrap の方が一般的ではと思いました
- getter
	- [旧 v3](https://v3.ja.vuejs.org/guide/composition-api-introduction.html#%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AB%E3%83%95%E3%83%83%E3%82%AF%E3%82%92-setup-%E3%81%AE%E4%B8%AD%E3%81%AB%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B) に合わせてゲッターとしましたが getter の方が一般的ではと思いました

2022-02-26 13:39 UTC, bobstrange commented on src/guide/typescript/composition-api.md
> +# Composition API とともに TypeScript を使用する
https://github.com/vuejs-translations/docs-ja/pull/297#discussion_r815272743

に合わせています。

2022-02-26 13:39 UTC, bobstrange commented on src/guide/typescript/composition-api.md
> +> このページは [TypeScript のサポート](./overview) ページの内容をすでに読んでいることを前提にしています。
https://github.com/vuejs-translations/docs-ja/pull/297/files#diff-30c34ca58d0edd3d6b94c99ac1539fd7571996115612e08dbbea5a34fa16ed9eR5

に合わせています。

2022-03-02 17:29 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2022-03-02 17:29 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +これは "type-based declaration" 型ベースの宣言) と呼ばれます。コンパイラーは型引数に基づいて同等の実行時のオプションを推論しようとします。今回の場合、2 番目の例は最初の例と全く同じ実行時のオプションにコンパイルされます。
カッコが漏れているようです。
```suggestion
これは "type-based declaration" (型ベースの宣言) と呼ばれます。コンパイラーは型引数に基づいて同等の実行時のオプションを推論しようとします。今回の場合、2 番目の例は最初の例と全く同じ実行時のオプションにコンパイルされます。
```

2022-03-02 17:29 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +type-base declaration (型ベースの宣言) と runtime declaration (実行時宣言) の両方を同時に使用することはできません。
`type-base declaration` と `runtime declaration` は既に一度カッコ付注釈で説明しているので、ここの文では説明は以下の不要でもよさそうです。
```suggestion
type-base declaration と runtime declaration の両方を同時に使用することはできません。
```

2022-03-02 17:29 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +type-based declaration (型ベースの宣言) を使用すると、props のデフォルト値を宣言することができません。これは、現在実験的な機能である [Reactivity Transform](/guide/extras/reactivity-transform.html) で解決することができます:
ここもそうですね。カッコは削除してもよさそうです。
```suggestion
type-based declaration を使用すると、props のデフォルト値を宣言することができません。これは、現在実験的な機能である [Reactivity Transform](/guide/extras/reactivity-transform.html) で解決することができます:
```

2022-03-02 17:29 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +`<script setup>` では、`emit` 関数も runtime declaration (実行時宣言) もしくは type declaration (型ベースの宣言) のいずれかを使って型付けすることができます:
ここの ` runtime declaration` そうですね。それは削除してもよさそうです。
`type declaration` は `型宣言` でも意味が通じるので、そのようにしておくとよさそうです。

```suggestion
`<script setup>` では、`emit` 関数も runtime declaration もしくは type declaration (型宣言) のいずれかを使って型付けすることができます:
```

2022-03-02 17:29 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +型ベースの宣言の場合、引数は、[Call Signatures](https://www.typescriptlang.org/docs/handbook/2/functions.html#call-signatures) を持つ型リテラルでなければなりません。この型リテラルは、返される `emit` 関数の型として使用されます。見れば分かるとおり、型ベースの宣言をすることで emit されるイ
```suggestion
type declaration の場合、引数は、[Call Signatures](https://www.typescriptlang.org/docs/handbook/2/functions.html#call-signatures) を持つ型リテラルでなければなりません。この型リテラルは、返される `emit` 関数の型として使用されます。見れば分かるとおり、型ベースの宣言をすることで emit されるイベントの型をより細かく制御することができます。
```

2022-03-02 17:29 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +型アノテーションが無い場合、`event` 引数は暗黙の `any` 型になります。`tsconfig.json` で `"strict": true` や `"noImplicitAny": true` にしている場合、これは型エラーになります。そのため、明示的にイベントハンドラーの引数を型付けすることが推奨されます。加えて、`event` のプロパティを明示的に型アサーションする必要があるか
`type annotation` は TypeScript 関連のドキュメント読んでいると頻出するので、カッコ付で注釈して訳を提供しつつも、`type annotation` としておいた方がよさそうです。
```suggestion
type annotation (型注釈) が無い場合、`event` 引数は暗黙の `any` 型になります。`tsconfig.json` で `"strict": true` や `"noImplicitAny": true` にしている場合、これは型エラーになります。そのため、明示的にイベントハンドラーの引数を型付けすることが推奨されます。加えて、`event` のプロパティを明示的に型アサーションする必要があるかもしれません:
```

2022-03-02 17:29 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +厳密な型安全性のために、`el.value` にアクセスする際には、オプショナルチェーンもしくは type guards (型ガード) をする必要があります。なぜなら、コンポーネントがマウントされるまでは ref の初期値は `null` であり、参照されていた要素が `v-if` によってアンマウントされた場合にも `null` にセットされる可能性があるからです。
`optional chaining` は TypeScript の言語機能として、よく英語表記でも使われるので、`optional chaining` のままでよさそうです。
```suggestion
厳密な型安全性のために、`el.value` にアクセスする際には、optional chaining もしくは type guards (型ガード) をする必要があります。なぜなら、コンポーネントがマウントされるまでは ref の初期値は `null` であり、参照されていた要素が `v-if` によってアンマウントされた場合にも `null` にセットされる可能性があるからです。
```

2022-03-02 17:30 UTC, kazupon commented
> * type-based declaration
>   
>   * 型ベースの宣言
> * runtime declaration
>   
>   * 実行時宣言
> * an object literal type
>   
>   * オブジェクトリテラル型
> * generic, generic type
>   
>   * 基本型引数として、必要が有る場合のみジェネリック型としました
>   * 参照 [TypeScript deep dive](https://typescript-jp.gitbook.io/deep-dive/type-system/generics)
> * interface
>   
>   * interface をそのまま使用するかインターフェースで悩みました
> * reactive destructure
>   
>   * リアクティブな分割代入
> * unwrap
>   
>   * [他](src/api/sfc-script-setup.md) [他2](src/guide/reusability/composables.md) でアンラップとしているので合わせましたが、unwrap の方が一般的ではと思いました
> * getter
>   
>   * [旧 v3](https://v3.ja.vuejs.org/guide/composition-api-introduction.html#%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AB%E3%83%95%E3%83%83%E3%82%AF%E3%82%92-setup-%E3%81%AE%E4%B8%AD%E3%81%AB%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B) に合わせてゲッターとしましたが getter の方が一般的ではと思いました


そうですね。用語集に追加した方がいいですね！/cc @jay-es

2022-03-03 05:27 UTC, bobstrange reviewed
@kazupon

レビューいただきありがとうございます。
以下修正いたしましたので、再度ご確認よろしくお願いします :bow:

- 指摘された変更内容の取り込み 53ef2b5882992a379d15906126a33534365f9a39
- side nav の翻訳 d2488f999f0df1b65d0cb8d6ce132c880042a5c1
- ページタイトルの修正 01bffbe672247472327bf6e8247d26911124df5f
- 細かな修正 2b056f06fc1cd53760a03430c6d781649e2e01b9

2022-03-03 05:27 UTC, bobstrange commented on .vitepress/config.ts
> +          text: 'Composition API とともに TypeScript を使用する',
left navi も翻訳追加しました

2022-03-03 05:27 UTC, bobstrange commented on src/guide/typescript/composition-api.md
> +厳密な型安全性のために、`el.value` にアクセスする際には、optional chaining もしくは type guards (型ガード) をする必要があります。なぜなら、コンポーネントがマウントされるまでは ref の初期値は `null` であり、参照されていた要素が `v-if` によってアンマウントされた場合にも `null` にセットされる可能性があるからです。
すみません、こちらコメント忘れてたのですが、MDN を参照して オプショナルチェーンとしました。
ただ、optional chaining をオプショナルチェーンと記載するのは違和感がある (本家もカッコ書きになっていました) ので、提案いただいたとおりに修正しました。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2022-03-03 05:27 UTC, bobstrange commented on src/guide/typescript/composition-api.md
> +`reactive()` の型引数を使用することは推奨されません、なぜなら reactive の戻り値の型は、ネストされた ref をアンラップする処理を含む為、型引数によって与えられる型と異なるからです。
為 と ため になっていたことと、ためが重なっていたので修正しました。

2022-03-05 16:02 UTC, kazupon commented on src/guide/typescript/composition-api.md
> +厳密な型安全性のために、`el.value` にアクセスする際には、optional chaining もしくは type guards (型ガード) をする必要があります。なぜなら、コンポーネントがマウントされるまでは ref の初期値は `null` であり、参照されていた要素が `v-if` によってアンマウントされた場合にも `null` にセットされる可能性があるからです。
なるほど。MDN がそう表記しているのであれば、カタカナ表記でも良さそうですね。度々すいませんが、カタカナ表記にしてもらえませんか？ 🙏

2022-03-05 16:03 UTC, kazupon commented
@bobstrange 
すいません、手数をかけてしまうのですが、optional chaining のところ、カナカナ表記にしてもらえますか？

2022-03-06 02:49 UTC, bobstrange commented
@kazupon 

レビューありがとうございます :bow:

修正しました [`6224e9c` (#298)](https://github.com/vuejs-translations/docs-ja/pull/298/commits/6224e9c490d1e526f07032f0eb21fa36b04861f1)


@jay-es 

用語集の方の修正が必要になりましたのでよろしくお願いします :bow:

- optional chaining
  - オプショナルチェーン
  - MDN に合わせる為 [ref](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

https://github.com/vuejs-translations/docs-ja/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E#%E8%8B%B1%E8%AA%9E%E3%81%AE%E3%81%BE%E3%81%BE

2022-03-21 15:50 UTC, kazupon commented
すいません。遅くなりました。:bow:
LGTMです！

2022-03-21 15:50 UTC, kazupon approved these changes

2022-03-21 15:50 UTC, merged