translate guide/essentials/reactivity-fundamentals.md
vuejs-translations/docs-ja pull request #305
Opened 2022-02-28 23:40 UTC by jiyuujin

resolve #9

ご確認のほど、よろしくお願いします！

2022-03-03 00:46 UTC, kazupon requested changes
レビュー 👀 コメント 💬しました。
レビューコメントのほとんどは、`:` を日本語句読点に変換してしまっているものがほとんどです。
確認お願いします。

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +# リアクティブ性の基礎
`Reactivity` を訳すと `反応性` ですが、その用語もあまり使われないので悩ましいですね。
ここでは、単純に Vue のリアクティブについてまさに基礎的な説明なので、用語の翻訳厳密に拘る必要はなく、意訳気味に、`リアクティブの基礎` でもよい感じがします。

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +リアクティブなオブジェクトは [JavaScript プロキシ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) で、通常のオブジェクトと同じように振る舞います。違いは、Vue がリアクティブなオブジェクトのプロパティアクセスとミューテーションを追跡できることです。詳細
`ミューテーション` は初見の人には、分からないと思うので、`変更`と訳しておいてもいいですね。ここの文章の文脈では。`ミューテーション`、ソフトウェア用語では一般的になってはいるのですが。

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +コンポーネントのテンプレートでリアクティブな状態を使うには、コンポーネントの `setup()` 関数で宣言し、それを返します。
`:` もなるべく原文に沿って翻訳お願いします！ 🙏 

```suggestion
コンポーネントのテンプレートでリアクティブな状態を使うには、コンポーネントの `setup()` 関数で宣言し、それを返します:
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +`setup()` 関数を使って手動で状態やメソッドを公開すると、冗長になることがあります。幸いなことに、これはビルドステップを使用しない場合にのみ必要です。Single-File Components (SFC) を使用する場合は、 `<script setup>` を使用することで大幅に簡略化することができます。
`Single-File Components` は `単一ファイルコンポーネント`でお願いします！ 🙏 

```suggestion
`setup()` 関数を使って手動で状態やメソッドを公開すると、冗長になることがあります。幸いなことに、これはビルドステップを使用しない場合にのみ必要です。単一ファイルコンポーネント (SFC) を使用する場合は、 `<script setup>` を使用することで大幅に簡略化することができます：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +Vue は `methods` の `this` 値を自動的にバインドし、常にコンポーネントのインスタンスを参照するようにします。これにより、イベントリスナーやコールバックとして使用される場合に、メソッドが正しい `this` 値を保持することが保証されます。Vue が適切な `this` 値をバインドできないため、 `methods` を定義する際に矢印関数を使用しないようにしましょう。
`矢印関数` ではなく `アロー関数` でお願いします。日本のソフトウェア業界ではそのように訳されるの一般的になっているので。

```suggestion
Vue は `methods` の `this` 値を自動的にバインドし、常にコンポーネントのインスタンスを参照するようにします。これにより、イベントリスナーやコールバックとして使用される場合に、メソッドが正しい `this` 値を保持することが保証されます。Vue が適切な `this` 値をバインドできないため、 `methods` を定義する際にアロー関数を使用しないようにしましょう：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +`reactive()` API には 2 つの制限があります。：
```suggestion
`reactive()` API には 2 つの制限があります：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +2. Vue のリアクティブ性追跡はプロパティアクセス上で動作するため、リアクティブなオブジェクトへの参照を常に同じに保つ必要があります。つまり、リアクティブなオブジェクトを簡単に「置き換える」ことができません。
```suggestion
2. Vue のリアクティブ性追跡はプロパティアクセス上で動作するため、リアクティブなオブジェクトへの参照を常に同じに保つ必要があります。つまり、リアクティブなオブジェクトを簡単に「置き換える」ことができません：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +このルールは、ネストされたオブジェクトにも適用されます。深いリアクティブ性を持つため、リアクティブなオブジェクトの中にあるネストされたオブジェクトもプロキシとなります。
```suggestion
このルールは、ネストされたオブジェクトにも適用されます。深いリアクティブ性を持つため、リアクティブなオブジェクトの中にあるネストされたオブジェクトもプロキシとなります：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +注意すべきは、`reactive()` の戻り値が、元のオブジェクトの [プロキシ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) であり、元のオブジェクトと等しくないということです。
```suggestion
注意すべきは、`reactive()` の戻り値が、元のオブジェクトの [プロキシ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) であり、元のオブジェクトと等しくないということです：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +状態変化後の DOM 更新が完了するのを待つため、[nextTick()](/api/general.html#nexttick) というグローバル API を使用することができます。
```suggestion
状態変化後の DOM 更新が完了するのを待つため、[nextTick()](/api/general.html#nexttick) というグローバル API を使用することができます：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +コンポーネントのインスタンスに属する他のプロパティと同じく、`methods` はコンポーネントのテンプレート内からアクセスすることができます。テンプレートの中では、イベントリスナーとして一般的に使用されます。
```suggestion
コンポーネントのインスタンスに属する他のプロパティと同じく、`methods` はコンポーネントのテンプレート内からアクセスすることができます。テンプレートの中では、イベントリスナーとして一般的に使用されます：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +コンポーネントのインスタンスにメソッドを追加するには、 `methods` オプションを使用します。これは、必要なメソッドを含むオブジェクトでなければなりません。
```suggestion
コンポーネントのインスタンスにメソッドを追加するには、 `methods` オプションを使用します。これは、必要なメソッドを含むオブジェクトでなければなりません：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +同様に、リアクティブな状態を変化させる関数を同じスコープで宣言し、状態と並行してメソッドとして公開することができます。
```suggestion
同様に、リアクティブな状態を変化させる関数を同じスコープで宣言し、状態と並行してメソッドとして公開することができます：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +Vue 3 では、[JavaScript プロキシ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) を活用することで、データをリアクティブにすることができます。Vue 2 から来たユーザーは、以下のエッジケースに注意する必要があります。
```suggestion
Vue 3 では、[JavaScript プロキシ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) を活用することで、データをリアクティブにすることができます。Vue 2 から来たユーザーは、以下のエッジケースに注意する必要があります：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +Options API では、`data` オプションを使用して、コンポーネントのリアクティブな状態を宣言します。オプションの値は、オブジェクトを返す関数でなければなりません。Vue は、新しいコンポーネントのインスタンスを作成するときにこの関数を呼び出し、返されたオブジェクトをリアクティブシステムでラップします。このオブジェクトのトップレベルのプロパティは、コンポーネントのインスタンス（メソッ
```suggestion
Options API では、`data` オプションを使用して、コンポーネントのリアクティブな状態を宣言します。オプションの値は、オブジェクトを返す関数でなければなりません。Vue は、新しいコンポーネントのインスタンスを作成するときにこの関数を呼び出し、返されたオブジェクトをリアクティブシステムでラップします。このオブジェクトのトップレベルのプロパティは、コンポーネントのインスタンス（メソッドやライフサイクルフックでは `this`）にプロキシされます：
```

2022-03-03 00:46 UTC, kazupon commented on .vitepress/config.ts
> +          text: 'リアクティブ性の基礎',
```suggestion
          text: 'リアクティビティの基礎',
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +Vue は、`reactive()` の制限に対処するため、[`ref()`](/api/reactivity-core.html#ref) という関数も提供しており、任意の値の型を保持できるリアクティブな **"refs "** を作成することができます。
```suggestion
Vue は、`reactive()` の制限に対処するため、[`ref()`](/api/reactivity-core.html#ref) という関数も提供しており、任意の値の型を保持できるリアクティブな **"refs "** を作成することができます：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +`ref()` は引数を受け取り、それを `.value` プロパティを持つ ref オブジェクトにラップして返します。
```suggestion
`ref()` は引数を受け取り、それを `.value` プロパティを持つ ref オブジェクトにラップして返します：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +オブジェクトの値を含む ref は、オブジェクト全体をリアクティブに置き換えることができます。
```suggestion
オブジェクトの値を含む ref は、オブジェクト全体をリアクティブに置き換えることができます：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +また、Ref を関数に渡したり、プレーンオブジェクトから分解したりしても、リアクティブ性が失われることはありません。
```suggestion
また、Ref を関数に渡したり、プレーンオブジェクトから分解したりしても、リアクティブ性が失われることはありません：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +# リアクティブ性の基礎
カタカナ翻訳でもいい気がしてきました。`リアクティビティ`

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +ref がテンプレートのトップレベルのプロパティとしてアクセスされた場合、それらは自動的に「アンラップ」されるので、`.value` を使用する必要はありません。以下は、先ほどのカウンターの例で、代わりに `ref()` を使用したものとなります。
```suggestion
ref がテンプレートのトップレベルのプロパティとしてアクセスされた場合、それらは自動的に「アンラップ」されるので、`.value` を使用する必要はありません。以下は、先ほどのカウンターの例で、代わりに `ref()` を使用したものとなります：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +// リアクティブ性を保持します。
```suggestion
// リアクティビティを保持します。
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +// リアクティブ性を保持しています。
```suggestion
// リアクティビティを保持しています。
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +つまり、`ref()` を使うと、任意の値への「参照」を作り、リアクティブ性を失わずに受け渡しすることができます。この能力は、ロジックを [Composable Functions](/guide/reusability/composables.html) に抽出する際に頻繁に使用されるため、非常に重要となります。
```suggestion
つまり、`ref()` を使うと、任意の値への「参照」を作り、リアクティビティを失わずに受け渡しすることができます。この能力は、ロジックを [Composable Functions](/guide/reusability/composables.html) に抽出する際に頻繁に使用されるため、非常に重要となります。
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +リアクティブなオブジェクトのプロパティとして `ref` にアクセスしたり変化させたりすると、自動的にアンラップされるので、通常のプロパティと同じように振る舞うことができます。
```suggestion
リアクティブなオブジェクトのプロパティとして `ref` にアクセスしたり変化させたりすると、自動的にアンラップされるので、通常のプロパティと同じように振る舞うことができます：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +既存の ref にリンクされたプロパティに新しい ref が割り当てられた場合に、それは古い ref を置き換えることとなります。
```suggestion
既存の ref にリンクされたプロパティに新しい ref が割り当てられた場合に、それは古い ref を置き換えることとなります：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +場合によっては、デバウンスされたイベントハンドラーを作成するなど、動的にメソッド関数を作成する必要があります。
```suggestion
場合によっては、デバウンスされたイベントハンドラーを作成するなど、動的にメソッド関数を作成する必要があります：
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +## リアクティブなトランスフォーム <sup class="vt-badge experimental" /> \*\*
`Transform` は `変換` でよさそうです。

```suggestion
## リアクティブな変換 <sup class="vt-badge experimental" /> \*\*
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +Ref で `.value` を使わなければならないのは、JavaScript の言語的な制約による欠点です。しかし、コンパイル時の変換を利用すれば、適切な場所に自動的に `.value` を追加して人間工学を改善することができます。Vue はコンパイル時の変換を提供しており、先ほどの「カウンター」の例をこのように記述することができます。
Vue のコンパイラを実装を考慮すると少し意訳気味以下でどうでしょう。

```suggestion
Ref で `.value` を使わなければならないのは、JavaScript の言語的な制約による欠点です。しかし、コンパイル時の変換 (ここでいうコンパイル時とは SFC を JavaScript コードへ変換する時) を利用すれば、適切な場所に自動的に `.value` を追加して人間工学を改善することができます。Vue はコンパイル時の変換を提供しており、先ほどの「カウンター」の例をこのように記述することができます。
```

2022-03-03 00:46 UTC, kazupon commented on src/guide/essentials/reactivity-fundamentals.md
> +[リアクティブなトランスフォーム](/guide/extras/reactivity-transform.html) の詳細については、専用のセクションで説明されています。ただし、現在はまだ実験的なものであり、最終的に完成するまでに変更される可能性があることに注意してください。
```suggestion
[リアクティブな変換](/guide/extras/reactivity-transform.html) の詳細については、専用のセクションで説明されています。ただし、現在はまだ実験的なものであり、最終的に完成するまでに変更される可能性があることに注意してください。
```

2022-03-03 03:50 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +# リアクティブ性の基礎
`リアクティビティ` にリネームしました - https://github.com/vuejs-translations/docs-ja/pull/305/commits/f70d2e07ab2956d3fc48141ccb25ad826b07ecfc

2022-03-03 04:33 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +コンポーネントのテンプレートでリアクティブな状態を使うには、コンポーネントの `setup()` 関数で宣言し、それを返します。
`コンポーネントのテンプレートでリアクティブな状態を使うには、下記に示すように、コンポーネントの `setup()` 関数で宣言し、それを返します：` に更新済

2022-03-03 04:34 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +`setup()` 関数を使って手動で状態やメソッドを公開すると、冗長になることがあります。幸いなことに、これはビルドステップを使用しない場合にのみ必要です。Single-File Components (SFC) を使用する場合は、 `<script setup>` を使用することで大幅に簡略化することができます。
`単一ファイルコンポーネント` に変更済

2022-03-03 04:34 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +Vue は `methods` の `this` 値を自動的にバインドし、常にコンポーネントのインスタンスを参照するようにします。これにより、イベントリスナーやコールバックとして使用される場合に、メソッドが正しい `this` 値を保持することが保証されます。Vue が適切な `this` 値をバインドできないため、 `methods` を定義する際に矢印関数を使用しないようにしましょう。
`アロー関数` に変更済

2022-03-03 04:35 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +Vue は `methods` の `this` 値を自動的にバインドし、常にコンポーネントのインスタンスを参照するようにします。これにより、イベントリスナーやコールバックとして使用される場合に、メソッドが正しい `this` 値を保持することが保証されます。Vue が適切な `this` 値をバインドできないため、 `methods` を定義する際に矢印関数を使用しないようにしましょう。
`アロー関数` に変更済

2022-03-03 04:35 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +既存の ref にリンクされたプロパティに新しい ref が割り当てられた場合に、それは古い ref を置き換えることとなります。
`既存の ref にリンクされたプロパティに新しい ref が割り当てられた場合、下記に示すように、それは古い ref を置き換えることとなります：` に更新済

2022-03-03 04:36 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +場合によっては、デバウンスされたイベントハンドラーを作成するなど、動的にメソッド関数を作成する必要があります。
`場合によっては、デバウンスされたイベントハンドラーを作成するなど、下記に示すように、動的にメソッド関数を作成する必要があります：` に更新済

2022-03-03 04:36 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +## リアクティブなトランスフォーム <sup class="vt-badge experimental" /> \*\*
`変換` に更新済

2022-03-03 04:37 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +Ref で `.value` を使わなければならないのは、JavaScript の言語的な制約による欠点です。しかし、コンパイル時の変換を利用すれば、適切な場所に自動的に `.value` を追加して人間工学を改善することができます。Vue はコンパイル時の変換を提供しており、先ほどの「カウンター」の例をこのように記述することができます。
`ここでいうコンパイル時とは SFC を JavaScript コードへ変換する時` というカッコ付注釈を追加済

2022-03-03 04:37 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +[リアクティブなトランスフォーム](/guide/extras/reactivity-transform.html) の詳細については、専用のセクションで説明されています。ただし、現在はまだ実験的なものであり、最終的に完成するまでに変更される可能性があることに注意してください。
`変換` に更新済

2022-03-03 13:49 UTC, jay-es requested changes

2022-03-03 13:49 UTC, jay-es commented on .vitepress/theme/components/PreferenceSwitch.vue
> +      <span>API の参照</span>
"Preference" には「参照」という意味はないですし、ここは翻訳対象ページと関係ない箇所なので元に戻していただくのがよさそうです

2022-03-03 13:49 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +### リアクティビティ
"Deep" に対する訳が抜けているので追加お願いします
```suggestion
### ディープなリアクティビティ
```

2022-03-03 13:49 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +## リアクティブな変換 <sup class="vt-badge experimental" /> \*\*
"Reactive" ではなく "Reactivity" なので「リアクティビティ」に変更

```suggestion
## リアクティビティ変換 <sup class="vt-badge experimental" /> \*\*
```

2022-03-03 13:49 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +[リアクティブな変換](/guide/extras/reactivity-transform.html) の詳細については、専用のセクションで説明されています。ただし、現在はまだ実験的なものであり、最終的に完成するまでに変更される可能性があることに注意してください。
```suggestion
[リアクティビティ変換](/guide/extras/reactivity-transform.html) の詳細については、専用のセクションで説明されています。ただし、現在はまだ実験的なものであり、最終的に完成するまでに変更される可能性があることに注意してください。
```

2022-03-04 01:17 UTC, jiyuujin commented on .vitepress/theme/components/PreferenceSwitch.vue
> +      <span>API の参照</span>
`API Preference` に戻しました

2022-03-04 01:17 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +### リアクティビティ
`ディープなリアクティビティ` に更新しました

2022-03-04 01:18 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +## リアクティブな変換 <sup class="vt-badge experimental" /> \*\*
`リアクティビティ変換` に更新しました

2022-03-04 01:18 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +[リアクティブな変換](/guide/extras/reactivity-transform.html) の詳細については、専用のセクションで説明されています。ただし、現在はまだ実験的なものであり、最終的に完成するまでに変更される可能性があることに注意してください。
`リアクティビティ変換` に更新しました

2022-03-05 14:35 UTC, jay-es requested changes
kazupon さんからの指摘事項もいくつか残っているので、それらも対応お願いします:pray:

2022-03-05 14:35 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
>  The following expression will **NOT** work as expected:
翻訳漏れがあるので対応お願いします:pray:

2022-03-05 14:35 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +{{ object.foo + 1 }} <!-- アンラップしなくても良い -->
コメントが多いので削除お願いします:pray:
```suggestion
{{ object.foo + 1 }}
```

2022-03-05 14:35 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +レンダリング結果は `[object Object]1` となります。これは `object.foo` が ref オブジェクトであるためです。これを解決するには、下記に示すように `foo` をトップレベルのプロパティにすればよい：
余分な行があるので削除お願いします:pray:
```suggestion
レンダリング結果は `[object Object]1` となります。これは `object.foo` が ref オブジェクトであるためです。これを解決するには、下記に示すように `foo` をトップレベルのプロパティにすればよい：
```

2022-03-06 09:57 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
>  The following expression will **NOT** work as expected:
`下記に示した式は、期待通りに動作 **しません** ：` に更新しました

2022-03-06 09:58 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +{{ object.foo + 1 }} <!-- アンラップしなくても良い -->
余計だった `<!-- アンラップしなくても良い -->` を削除しました

2022-03-06 09:58 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +レンダリング結果は `[object Object]1` となります。これは `object.foo` が ref オブジェクトであるためです。これを解決するには、下記に示すように `foo` をトップレベルのプロパティにすればよい：
余計だった行を削除しました

2022-03-06 09:59 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +リアクティブなオブジェクトは [JavaScript プロキシ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) で、通常のオブジェクトと同じように振る舞います。違いは、Vue がリアクティブなオブジェクトのプロパティアクセスとミューテーションを追跡できることです。詳細
`変更` に変更済

2022-03-06 14:44 UTC, jay-es requested changes

2022-03-06 14:44 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +これを解決するには、`foo` をトップレベルのプロパティにすれば良いです。
原文と違う意味の文が残っているので、前回の470行目にあった文に差し替えてください

（文末も修正）
```suggestion
レンダリング結果は `[object Object]1` となります。これは `object.foo` が ref オブジェクトであるためです。これを解決するには、下記に示すように `foo` をトップレベルのプロパティにすればよいです：
```

2022-03-10 11:48 UTC, jay-es commented
@jiyuujin 
こちらのファイルに2点修正が入りましたので、main ブランチの取り込みと訳文への反映をお願いします:pray:

https://github.com/vuejs-translations/docs-ja/pull/347
https://github.com/vuejs-translations/docs-ja/pull/352

2022-03-11 11:10 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +これを解決するには、`foo` をトップレベルのプロパティにすれば良いです。
@jiyuujin こちらもご対応お願いします:pray:

2022-03-11 12:29 UTC, jiyuujin commented on src/guide/essentials/reactivity-fundamentals.md
> +これを解決するには、`foo` をトップレベルのプロパティにすれば良いです。
@jay-es こちらも対応いたしました

2022-03-11 12:54 UTC, jay-es commented
@jiyuujin kazupon さんの指摘分が残っているので、それらもご確認・修正お願いします
https://github.com/vuejs-translations/docs-ja/pull/305/files

2022-03-12 03:26 UTC, jiyuujin commented
@jay-es 遅れました、対応いたしました

2022-03-14 12:08 UTC, merged