「Tutorial > List Rendering」の翻訳
vuejs-translations/docs-ja pull request #325
Opened 2022-03-04 11:49 UTC by yuri-htt

resolve #000 ←（`000` の部分を実際の issue 番号に書き換えてください）

2022-03-05 14:54 UTC, jay-es requested changes
何点か修正お願いします:pray:

2022-03-05 14:54 UTC, jay-es commented on src/tutorial/src/step-7/description.md
> +各 Todo オブジェクトに一意の `id` を与え、それを各 `<li>` の <a target="_blank" href="/api/built-in-special-attributes.html#key">一意な `key` 属性</a> としてバインドしていることに注目してください。この `key` により、Vue は各 `<li>` を配列内の対応するオブジェクトの位置に合わせて
special は「一意な」という意味はなさそうでしたので「特別な」か「専門の」に変更お願いします:pray:
```suggestion
各 Todo オブジェクトに一意の `id` を与え、それを各 `<li>` の <a target="_blank" href="/api/built-in-special-attributes.html#key">特別な `key` 属性</a> としてバインドしていることに注目してください。この `key` により、Vue は各 `<li>` を配列内の対応するオブジェクトの位置に合わせて正確に移動させることができます。
```

2022-03-05 14:54 UTC, jay-es commented on src/tutorial/src/step-7/description.md
> +1. 配列の [ミュータブルな関数](https://stackoverflow.com/questions/9009879/which-javascript-array-functions-are-mutating) を呼び出す:
```suggestion
1. 配列の [変更メソッド](https://stackoverflow.com/questions/9009879/which-javascript-array-functions-are-mutating) を呼び出す:
```

2022-03-05 14:54 UTC, jay-es commented on src/tutorial/src/step-7/description.md
> +2. 配列を置き換える:
後半の訳が抜けているので追加お願いします:pray:
```suggestion
2. 配列を新しいものに置き換える:
```

2022-03-05 16:08 UTC, kazupon reviewed
自分もレビュー 👀 しました。
jay-es さんが指摘以外は、特にないので、jay-es さんの指摘部分の対応お願いします！

2022-03-05 17:38 UTC, yuri-htt commented
📩 レビュワーさんへ

レビューありがとうございます。
ご丁寧にsuggestをしていただきましたので、その内容に置き換える形でご指摘の3点を修正いたしました。
再度ご確認お願いいたします。

2022-03-06 03:47 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-03-06 03:54 UTC, merged