「Tutorial > Getting Started」の翻訳
vuejs-translations/docs-ja pull request #326
Opened 2022-03-04 12:04 UTC by kzhrk

resolve https://github.com/vuejs-translations/docs-ja/issues/85

2022-03-05 16:27 UTC, kazupon approved these changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2022-03-05 16:27 UTC, kazupon commented on src/tutorial/src/step-1/description.md
> +このチュートリアルの目的はブラウザーで Vue で作業することがどのようなことなのか感じなのかいち早く体験してもらうことです。包括的な内容を目指すものではないため、すべてを理解してから次に進む必要はありません。しかしながら、すべてを完了したあと、各項目についてより詳しく説明している<a target="_blank" href="/guide/introduction.html">ガイド</a>
comprehensive は確かに辞典棟では、包括的 なという意味ですが、この用語普段あまり使う単語ではないので、他の単語で意訳気味にしたいですね。後の文章ではすべてを学ぶ必要がないとっているので、網羅的 とい訳でどうでしょうか。
```suggestion
このチュートリアルの目的はブラウザーで Vue で作業することがどのようなことなのか感じなのかいち早く体験してもらうことです。網羅的な内容を目指すものではないため、すべてを理解してから次に進む必要はありません。しかしながら、すべてを完了したあと、各項目についてより詳しく説明している<a target="_blank" href="/guide/introduction.html">ガイド</a>を必ずお読みください。
```

2022-03-05 16:27 UTC, kazupon commented on src/tutorial/src/step-1/description.md
> +<span class="wide">右</span><span class="narrow">下</span>のコードを編集することができて、瞬時に更新された結果を確認することができます。それぞれのステップでは Vue のコア機能を紹介し、デモが動作するようにコードを完成させることが期待されます。もし行き詰まったら、 "Show me!" ボタンで動作中のコードを表示できます。このボタンに頼り
特に翻訳内容的には問題ないのですが、`解決した` より `解いた` という訳の方が、このチュートリアルの話調的にいいですね。
```suggestion
<span class="wide">右</span><span class="narrow">下</span>のコードを編集することができて、瞬時に更新された結果を確認することができます。それぞれのステップでは Vue のコア機能を紹介し、デモが動作するようにコードを完成させることが期待されます。もし行き詰まったら、 "Show me!" ボタンで動作中のコードを表示できます。このボタンに頼り過ぎないようにしましょう。自分自身で考えて解いた方が早く習得できます。
```

2022-03-05 16:27 UTC, kazupon commented on src/tutorial/src/step-1/description.md
> +Vue 2 や他のフレームワークから来た経験豊富な開発者であれば、このチュートリアルを最大限に活用するために、いくつかの設定を変更することができます。もしあなたが初心者の場合、デフォルトの設定で作業することをお勧めします。
`it's recommended to go with the defaults` _の訳ですが、翻訳していただいた内容でも問題ないのですが、少し意訳気味に以下のようにしておくとこの章の流れ的によさそうです。
```suggestion
Vue 2 や他のフレームワークから来た経験豊富な開発者であれば、このチュートリアルを最大限に活用するために、いくつかの設定を変更することができます。もしあなたが初心者の場合、デフォルトの状態で解くことをお勧めします。
```

2022-03-05 22:30 UTC, kzhrk commented on src/tutorial/src/step-1/description.md
> +このチュートリアルの目的はブラウザーで Vue で作業することがどのようなことなのか感じなのかいち早く体験してもらうことです。包括的な内容を目指すものではないため、すべてを理解してから次に進む必要はありません。しかしながら、すべてを完了したあと、各項目についてより詳しく説明している<a target="_blank" href="/guide/introduction.html">ガイド</a>
たしかに 網羅的 の方がわかりやすい文章になりますね。
ご指摘ありがとうございます。修正します。

2022-03-05 22:32 UTC, kzhrk commented on src/tutorial/src/step-1/description.md
> +<span class="wide">右</span><span class="narrow">下</span>のコードを編集することができて、瞬時に更新された結果を確認することができます。それぞれのステップでは Vue のコア機能を紹介し、デモが動作するようにコードを完成させることが期待されます。もし行き詰まったら、 "Show me!" ボタンで動作中のコードを表示できます。このボタンに頼り
解いた にした方がマイルドな表現でいいですね。
修正します！

2022-03-05 22:37 UTC, kzhrk commented on src/tutorial/src/step-1/description.md
> +Vue 2 や他のフレームワークから来た経験豊富な開発者であれば、このチュートリアルを最大限に活用するために、いくつかの設定を変更することができます。もしあなたが初心者の場合、デフォルトの設定で作業することをお勧めします。
たしかに デフォルトの設定 とするより デフォルトの状態 の方がシンプルで伝わりやすいですね。
作業すること もL13の `自分自身で考えて解いた方が早く習得できます` に合わせて 解くこと にした方が伝わりやすいと思います。
修正します！

2022-03-05 22:41 UTC, kzhrk commented
ご指摘・ご提案いただいた変更取り込みました。
再レビューお願いします 🙏

2022-03-06 04:07 UTC, jay-es requested changes

2022-03-06 04:07 UTC, jay-es commented on src/tutorial/src/step-1/description.md
> +- Vue には 2 つの API スタイルがあります : オプション API とコンポジション API です。このチュートリアルは、両方で動作するように設計されています。上部にある **API Preference** スイッチを使って、好みのスタイルを選択することができます。 <a target="_blank" href="/guide/introduction.html#api-styl
Options API などは英語に変更お願いします:pray:
https://github.com/vuejs-translations/docs-ja/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E#%E8%8B%B1%E8%AA%9E%E3%81%AE%E3%81%BE%E3%81%BE
```suggestion
- Vue には 2 つの API スタイルがあります : Options API と Composition API です。このチュートリアルは、両方で動作するように設計されています。上部にある **API Preference** スイッチを使って、好みのスタイルを選択することができます。 <a target="_blank" href="/guide/introduction.html#api-styles">API スタイルの詳細については、こちらをご覧ください</a> 。
```

2022-03-06 05:00 UTC, kzhrk commented on src/tutorial/src/step-1/description.md
> +- Vue には 2 つの API スタイルがあります : オプション API とコンポジション API です。このチュートリアルは、両方で動作するように設計されています。上部にある **API Preference** スイッチを使って、好みのスタイルを選択することができます。 <a target="_blank" href="/guide/introduction.html#api-styl
翻訳ガイドのリファレンス見落としてました 🙇 
変更取り込みます。

2022-03-06 05:17 UTC, jay-es approved these changes
ありがとうございます:pray:

2022-03-07 12:53 UTC, jay-es commented
@kazupon こちら kazupon さんのレビュー分が修正済みですので、マージしてOKでしょうか？

2022-03-09 06:21 UTC, kazupon commented
@jay-es 
マージしてしまってOKです！

2022-03-09 12:07 UTC, merged