Event Listeners翻訳
vuejs-translations/docs-ja pull request #327
Opened 2022-03-04 12:11 UTC by yuma-ito-bd

resolve #94

2022-03-05 16:30 UTC, kazupon approved these changes
翻訳ありがとうございます！
私がレビューした限りでは、良さそうです！

2022-03-06 03:59 UTC, jay-es requested changes
細かくて恐縮ですが2点修正お願いします:pray:

2022-03-06 03:59 UTC, jay-es commented on src/tutorial/src/step-4/description.md
> +関数の中では、参照を変えることによってコンポーネントの状態を更新することができます。
"refs" は ref （の変数）を指していると思うので、以下のように修正お願いします:pray:
```suggestion
関数の中では、ref を変えることによってコンポーネントの状態を更新することができます。
```

2022-03-06 03:59 UTC, jay-es commented on src/tutorial/src/step-4/description.md
> +イベントハンドラーはインライン表現も使うことができ、共通のタスクを装飾子で簡略にすることができます。これらの詳細は <a target="_blank" href="/guide/essentials/event-handling.html">ガイド - イベントハンドリング</a> の中でカバーされています。
expression は「式」とするのがよいかと思いました
```suggestion
イベントハンドラーはインラインの式を使うこともでき、共通のタスクを装飾子で簡略にすることができます。これらの詳細は <a target="_blank" href="/guide/essentials/event-handling.html">ガイド - イベントハンドリング</a> の中でカバーされています。
```

2022-03-07 23:58 UTC, yuma-ito-bd commented
@jay-es 
ご指摘ありがとうございます。
修正いたしましたので、大変お手数ですが再レビューをお願いいたします。

2022-03-08 12:18 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-03-08 12:18 UTC, merged