「Tutorial > Conditional Rendering」の翻訳
vuejs-translations/docs-ja pull request #328
Opened 2022-03-04 14:13 UTC by ttt3pu

resolve #96

2022-03-05 16:35 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
対応お願いします。

2022-03-05 16:35 UTC, kazupon commented on src/tutorial/src/step-6/description.md
> +この `<h1>` は `awesome` の値が [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) である場合にのみレンダリングされます。もし `awesome` の値が [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) に変わった
MDN のリンクするなら以下のように日本語のURLしたいですね！
```suggestion
この `<h1>` は `awesome` の値が [truthy](https://developer.mozilla.org/ja/docs/Glossary/Truthy) である場合にのみレンダリングされます。もし `awesome` の値が [falsy](https://developer.mozilla.org/ja/docs/Glossary/Falsy) に変わったら、この `<h1>` は DOM から削除されます。
```

2022-03-06 04:11 UTC, jay-es approved these changes
LGTM です！
kazupon さんの指摘内容を修正お願いします:pray:

2022-03-06 13:13 UTC, ttt3pu commented
レビューありがとうございます！
いただいた箇所を https://github.com/vuejs-translations/docs-ja/pull/328/commits/f338e486a50169f8a4c264aa0c8e0e28096eef11 にて修正いたしました。
再レビューいただけますと幸いです。

2022-03-07 06:28 UTC, kazupon approved these changes

2022-03-07 06:30 UTC, merged