translate guide/best-practices/performance.md
vuejs-translations/docs-ja pull request #329
Opened 2022-03-05 06:58 UTC by takmatsukawa

resolve #42

2022-03-05 17:14 UTC, kazupon requested changes
レビュー 👀 しました。
いくつかコメント 💬 しましたので、対応お願いします。

2022-03-05 17:14 UTC, kazupon commented on src/guide/best-practices/performance.md
> +  - ビルドステップを使用する場合、ES モジュール形式を提供し、tree-shaking に適した依存関係を選択してください。例えば、 `lodash` よりも `lodash-es` を選択します。
`ES module` を ES2015 の仕様において策定された JavaScript のモジュール機構の総称なのですが、`ES モジュール` と英単語と日本語が混じって訳すのは違和感がありますね。
日本では、現在 `ES Modules` というように英語表記でも技術ブログ記事や他のメディアでも使っているので、`ES Modules`という形で統一していきたいです。

2022-03-05 17:14 UTC, kazupon commented on src/guide/best-practices/performance.md
> +  - ビルドステップを使用する場合、ES モジュール形式を提供し、tree-shaking に適した依存関係を選択してください。例えば、 `lodash` よりも `lodash-es` を選択します。
この後、`ESM` という単語もでてくるので、`ES Modules (ESM と略すこともある)` のような形にしておきたいですね。

2022-03-06 02:36 UTC, takmatsukawa commented on src/guide/best-practices/performance.md
> +## プロファイリングの選択肢
`プロファイリングツールのオプション` とした方が分かりやすかったかもしれませんが、ひとまず原文を尊重した形に収めます。

2022-03-06 02:42 UTC, takmatsukawa commented
細かいところまで見ていただきありがとうございます！修正しました。

2022-03-06 04:33 UTC, jay-es approved these changes
自分もレビューしました。LGTM です！

2022-03-07 06:30 UTC, kazupon approved these changes

2022-03-07 06:30 UTC, merged