Guide > Extra Topics > Vue and Web Components」の翻訳
vuejs-translations/docs-ja pull request #330
Opened 2022-03-05 08:13 UTC by yamanoku

resolve #53

2022-03-05 17:29 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
翻訳内容については問題ありません。
MDNのリンク先を日本語の方に対応するようにするというぐらいです。
対応お願いします。 🙏

2022-03-05 17:29 UTC, kazupon commented on src/guide/extras/web-components.md
> +[Web コンポーネント](https://developer.mozilla.org/en-US/docs/Web/Web_Components) は、開発者が再利用可能なカスタム要素 (custom elements) を作成するための一連の Web ネイティブ API 群の総称です。
MDN も日本語URLの方にしておくと読者フレンドリーですね！
```suggestion
[Web コンポーネント](https://developer.mozilla.org/ja/docs/Web/Web_Components) は、開発者が再利用可能なカスタム要素 (custom elements) を作成するための一連の Web ネイティブ API 群の総称です。
```
```suggestion
[Web コンポーネント](https://developer.mozilla.org/en-US/docs/Web/Web_Components) は、開発者が再利用可能なカスタム要素 (custom elements) を作成するための一連の Web ネイティブ API 群の総称です。
```

2022-03-05 17:29 UTC, kazupon commented on src/guide/extras/web-components.md
> +- Vue のカスタム要素は、要素の [`connectedCallback`](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks) が初めて呼び出されたときに、その shadow root 内に内部の Vue コンポーネン
ここも、MDNのリンク先は日本語の方にしておいたほうが、読者フレンドリーですね。
```suggestion
- Vue のカスタム要素は、要素の [`connectedCallback`](https://developer.mozilla.org/ja/docs/Web/Web_Components/Using_custom_elements#%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%AB%E3%83%90%E3%83%83%E3%82%AF%E3%81%AE%E4%BD%BF%E7%94%A8) が初めて呼び出されたときに、その shadow root 内に内部の Vue コンポーネントインスタンスをマウントします。
```
```suggestion
- Vue のカスタム要素は、要素の [`connectedCallback`](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks) が初めて呼び出されたときに、その shadow root 内に内部の Vue コンポーネントインスタンスをマウントします。
```

2022-03-05 17:29 UTC, kazupon commented on src/guide/extras/web-components.md
> +- Vue のカスタム要素は、要素の [`connectedCallback`](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks) が初めて呼び出されたときに、その shadow root 内に内部の Vue コンポーネン
ここも、MDNのリンク先は日本語の方にしておいたほうが、読者フレンドリーですね。
```suggestion
- Vue のカスタム要素は、要素の [`connectedCallback`](https://developer.mozilla.org/ja/docs/Web/Web_Components/Using_custom_elements#%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B5%E3%82%A4%E3%82%AF%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%AB%E3%83%90%E3%83%83%E3%82%AF%E3%81%AE%E4%BD%BF%E7%94%A8) が初めて呼び出されたときに、その shadow root 内に内部の Vue コンポーネントインスタンスをマウントします。
```
```suggestion
- Vue のカスタム要素は、要素の [`connectedCallback`](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks) が初めて呼び出されたときに、その shadow root 内に内部の Vue コンポーネントインスタンスをマウントします。
```

2022-03-05 17:29 UTC, kazupon commented on src/guide/extras/web-components.md
> +`this.$emit` や setup の `emit` を通じて発行されたイベントは、カスタム要素上でネイティブの[カスタムイベント (CustomEvents)](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_cu
ここのMDNのリンク先もそうですね。日本語の方にしましょう！
```suggestion
`this.$emit` や setup の `emit` を通じて発行されたイベントは、カスタム要素上でネイティブの[カスタムイベント (CustomEvents)](https://developer.mozilla.org/ja/docs/Web/Events/Creating_and_triggering_events#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E8%BF%BD%E5%8A%A0_%E2%80%93_customevent) としてディスパッチされます。追加のイベント引数(ペイロード)は、カスタムイベントオブジェクトの `details` プロパティの配列として公開されます。
```
```suggestion
`this.$emit` や setup の `emit` を通じて発行されたイベントは、カスタム要素上でネイティブの[カスタムイベント (CustomEvents)](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_customevent) としてディスパッチされます。追加のイベント引数(ペイロード)は、カスタムイベントオブジェクトの `details` プロパティの配列として公開されます。
```

2022-03-05 17:29 UTC, kazupon commented on src/guide/extras/web-components.md
> +`this.$emit` や setup の `emit` を通じて発行されたイベントは、カスタム要素上でネイティブの[カスタムイベント (CustomEvents)](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_cu
ここのMDNのリンク先もそうですね。日本語の方にしましょう！
```suggestion
`this.$emit` や setup の `emit` を通じて発行されたイベントは、カスタム要素上でネイティブの[カスタムイベント (CustomEvents)](https://developer.mozilla.org/ja/docs/Web/Events/Creating_and_triggering_events#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E8%BF%BD%E5%8A%A0_%E2%80%93_customevent) としてディスパッチされます。追加のイベント引数(ペイロード)は、カスタムイベントオブジェクトの `details` プロパティの配列として公開されます。
```
```suggestion
`this.$emit` や setup の `emit` を通じて発行されたイベントは、カスタム要素上でネイティブの[カスタムイベント (CustomEvents)](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_customevent) としてディスパッチされます。追加のイベント引数(ペイロード)は、カスタムイベントオブジェクトの `details` プロパティの配列として公開されます。
```

2022-03-05 17:29 UTC, kazupon commented on src/guide/extras/web-components.md
> +コンポーネント内部では、通常通り `<slot/>` 要素を使ってスロットをレンダリングすることができます。しかし、生成された要素を使うときは、[ネイティブのスロット構文](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots)しか受け付けません。
ここも同じく。日本語のURLの方へ。
```suggestion
コンポーネント内部では、通常通り `<slot/>` 要素を使ってスロットをレンダリングすることができます。しかし、生成された要素を使うときは、[ネイティブのスロット構文](https://developer.mozilla.org/ja/docs/Web/Web_Components/Using_templates_and_slots)しか受け付けません。
```
```suggestion
コンポーネント内部では、通常通り `<slot/>` 要素を使ってスロットをレンダリングすることができます。しかし、生成された要素を使うときは、[ネイティブのスロット構文](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots)しか受け付けません。
```

2022-03-05 17:29 UTC, kazupon commented on src/guide/extras/web-components.md
> +コンポーネント内部では、通常通り `<slot/>` 要素を使ってスロットをレンダリングすることができます。しかし、生成された要素を使うときは、[ネイティブのスロット構文](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots)しか受け付けません。
ここも同じく。日本語のURLの方へ。
```suggestion
コンポーネント内部では、通常通り `<slot/>` 要素を使ってスロットをレンダリングすることができます。しかし、生成された要素を使うときは、[ネイティブのスロット構文](https://developer.mozilla.org/ja/docs/Web/Web_Components/Using_templates_and_slots)しか受け付けません。
```
```suggestion
コンポーネント内部では、通常通り `<slot/>` 要素を使ってスロットをレンダリングすることができます。しかし、生成された要素を使うときは、[ネイティブのスロット構文](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots)しか受け付けません。
```

2022-03-06 00:48 UTC, yamanoku commented
@kazupon レビューありがとうございます！URLのほう差し替え対応いたしました

2022-03-06 01:39 UTC, kazupon approved these changes

2022-03-06 01:39 UTC, kazupon commented
@yamanoku 
対応ありがとうございます！
LGTMです！ 👍 
(いつもありがとうございます！)

2022-03-06 01:39 UTC, merged