[#14] Event Handling の翻訳
vuejs-translations/docs-ja pull request #331
Opened 2022-03-05 14:16 UTC by okakyo

resolve #14 ←（`000` の部分を実際の issue 番号に書き換えてください）

2022-03-05 17:38 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします。

2022-03-05 17:38 UTC, kazupon commented on src/guide/essentials/event-handling.md
> +テンプレートコンパイラーは `v-on` は、文字列値が JavaScript アイデンティファイヤー、あるいはプロパティのアクセスパスか適切などうかを検証することで、メソッドイベントハンドラーを検出します。例えば、`foo`、 `foo.bar` さらには `foo['bar']` がメソッドイベントハンドラーとして扱われる一方、`foo()` and `count++` はインラインイベント
`JavaScript identifier` の訳ですが、ここの文章の文脈では、JavaScript 言語仕様の [Identifier](https://262.ecma-international.org/5.1/#sec-7.6) のことを意味していますね。なので、日本語訳するのではなく、英語そのままでよさそうですね。

2022-03-05 17:38 UTC, kazupon commented on src/guide/essentials/event-handling.md
> +Vue はもっともよく使われるキーのためにアライアスが提供されます:
`アライアス` ではなく、`エリアス` ですかね。

2022-03-05 17:38 UTC, kazupon commented on src/guide/essentials/event-handling.md
> +これらの就職しは特定のマウスボタンが発火したイベントを制御するハンドラーを制限します。
typo
```suggestion
これらの修飾子は特定のマウスボタンが発火したイベントを制御するハンドラーを制限します。
```

2022-03-06 05:04 UTC, okakyo commented
修正を行いました。

ご確認のほどよろしくお願いします 🙇🏻

2022-03-06 05:11 UTC, jay-es requested changes
レビューしました。何点か修正お願いします:pray:

2022-03-06 05:11 UTC, jay-es commented on src/guide/essentials/event-handling.md
> +イベントハンドラーの中で `event.preventDefault()` あるいは `event.stopPropagation()` を呼び出す必要があるのはよくあることです。たとえメソッド内で簡単に扱うことができるかどうかにかかわらず、メソッドが DOM イベントの詳細を扱宇野ではなく、純粋にデータロジックに特化したメソッドがより最適です。
typo
```suggestion
イベントハンドラーの中で `event.preventDefault()` あるいは `event.stopPropagation()` を呼び出す必要があるのはよくあることです。たとえメソッド内で簡単に扱うことができるかどうかにかかわらず、メソッドが DOM イベントの詳細を扱うのではなく、純粋にデータロジックに特化したメソッドがより最適です。
```

2022-03-06 05:11 UTC, jay-es commented on src/guide/essentials/event-handling.md
> +`.capture`、 `.once`、 さらには `.passive` 修飾子 [ネイティブ  `addEventListener` メソッドのオプション](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters) を反映します:
typo?
```suggestion
`.capture`、 `.once`、 さらには `.passive` 修飾子は [ネイティブ  `addEventListener` メソッドのオプション](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters) を反映します:
```

2022-03-06 05:11 UTC, jay-es commented on src/guide/essentials/event-handling.md
> +<!-- つまり、インナーエレメントをターゲットにしたイベントはそのエレメントで操作される前にここで操作されます。 -->
element → 要素
```suggestion
<!-- つまり、内側の要素をターゲットにしたイベントはその要素で操作される前にここで操作されます。 -->
```

2022-03-06 05:11 UTC, jay-es commented on src/guide/essentials/event-handling.md
> +キーボードイベントを受信しているとき、特定のキーをチェックする必要がある場合があります。キーイベントを受信しているとき、Vue は `v-on` あるいは `@` にキー修飾子を加えることができます:
```suggestion
キーボードイベントを購読しているとき、特定のキーをチェックする必要がある場合があります。キーイベントを受信しているとき、Vue は `v-on` あるいは `@` にキー修飾子を加えることができます:
```

2022-03-07 12:57 UTC, okakyo commented
修正遠行いました。

ご確認のほどよろしくお願いします！

2022-03-07 13:26 UTC, jay-es approved these changes
ありがとうございます。LGTM！

@kazupon お手すきでご確認お願いします:pray:

2022-03-09 12:29 UTC, jay-es commented
指摘分修正済みなのでマージします:pray:

2022-03-09 12:29 UTC, merged