Introduction
vuejs-translations/docs-ja pull request #333
Opened 2022-03-05 21:58 UTC by tanquar

resolve #4

初コミットです。よろしくお願いします。

- 「？」「！」はそのまま使うようにしましたが、多少不自然なところでも、このままでよいでしょうか？
  - 「コンポジション API を土台にしています！」は「。」にしたほうが自然に思います。
- 他のドキュメントへのリンクタイトルは、仮のものとして訳しました。
- stateは「状態」にしました。「ステート」のほうが好まれるでしょうか?
- 「## 2 つの」は、複数形の「s」の訳出です。
- playgoundは「サンドボックス」のほうが通じるかと思って使いましたが、「プレイグラウンド」のほうがよいでしょうか?
- 「Vue 2 のドキュメントは [v2.vuejs.org](https://v2.vuejs.org/) に移動しました。」の移動先は「[jp.vuejs.org](https://jp.vuejs.org/)」が正しいでしょうか?

2022-03-06 14:33 UTC, jay-es requested changes
レビューしました。何点か修正お願いします:pray:

2022-03-06 14:33 UTC, jay-es commented on src/guide/introduction.md
> +- JAMStack / 静的サイトジェネレーション (SSG)
この行は先ほど本家の変更を取り込んだので、同じように修正お願いします:pray:
https://github.com/vuejs-translations/docs-ja/pull/338/files#diff-f43200945b93eacb14613755322fd170adbc7ba5905b9349859b23245f80249b
```suggestion
- Jamstack / 静的サイトジェネレーション (SSG)
```

2022-03-06 14:33 UTC, jay-es commented on src/guide/introduction.md
> +これらのテーマにはまだ付いていけないと感じても、大丈夫です！　チュートリアルとガイドでは、本当に基礎的な HTML と JavaScript の知識だけが求められます。これらのテーマのエキスパートでなくても、付いていける内容となっています。
concepts は直訳のままでも通じるかなと思いました
```suggestion
これらの概念にはまだ付いていけないと感じても、大丈夫です！　チュートリアルとガイドでは、本当に基礎的な HTML と JavaScript の知識だけが求められます。これらのテーマのエキスパートでなくても、付いていける内容となっています。
```

2022-03-06 14:33 UTC, jay-es commented on src/guide/introduction.md
> +Vue コンポーネントを作成する際は、**オプション API**、そして **コンポジション API** と呼ばれる 2 種類の異なる API スタイルが利用できます。
Options API, Composition API は英語に修正お願いします:pray:
（他の箇所も同様）
https://github.com/vuejs-translations/docs-ja/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E
```suggestion
Vue コンポーネントを作成する際は、**Options API**、そして **Composition API** と呼ばれる 2 種類の異なる API スタイルが利用できます。
```

2022-03-06 14:33 UTC, jay-es commented on src/guide/introduction.md
> +[サンドボックスで試す](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgLy8gcmVhY3RpdmUgc3RhdGVcbiAgZGF0YSgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgY291bnQ6IDBcbiAgICB9XG4gIH0sXG5cbiAgLy8
Playground は「プレイグラウンド」としてください:pray:

2022-03-06 14:33 UTC, jay-es commented on src/guide/introduction.md
> +// 状態をミューテートし、更新をトリガーする関数。
```suggestion
// 状態を変更し、更新をトリガーする関数。
```

2022-03-07 06:54 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
jay_es さんのレビューも含めて修正お願いします。 🙏

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +- Vue 2 のドキュメントは [v2.vuejs.org](https://v2.vuejs.org/) に移動しました。
Vue 2ドキュメントのリンク先ですが、リンクも日本語ドキュメントへのところにローカライズしたいところです。
現時点では、[`jp.vuejs.org`](https://v2.vuejs.org/) を Vue 2 の日本語 docs にしていく予定なので、とりあえずそれでお願いします。 🙏 
(今回翻訳しているVue 3向けの docs はサブドメインは `jp` ではなく`ja` で、`ja.vuejs.org` にする予定です。)

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +    カウント: {{ count }}
コード内のコメントを除いて、特に翻訳しないでそのままでよいです。
```suggestion
    Count is: {{ count }}
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +    カウント: {{ count }}
ここも同じく、コードのコメントはないのでそのままでよいです。
```suggestion
    Count is: {{ count }}
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +このドキュメントの続きでは、HTML、CSS、そして JavaScript の基礎知識があることが前提となっています。もしフロントエンドの開発をまったく経験したことがなければ、最初の一歩で Vue のようなフレームワークにすぐに飛び込むのは最適な方針でないかもしれません。基本を習ってからここに戻ってくるのでも大丈夫です！　ほかのフレームワークを使用した経験があれば、役立ちます。ただし、必須ではあ
ここのケースでは、全角スペースは入れなくても大丈夫です。(入れると読み手が不自然に感じる)
```suggestion
このドキュメントの続きでは、HTML、CSS、そして JavaScript の基礎知識があることが前提となっています。もしフロントエンドの開発をまったく経験したことがなければ、最初の一歩で Vue のようなフレームワークにすぐに飛び込むのは最適な方針でないかもしれません。基本を習ってからここに戻ってくるのでも大丈夫です！ほかのフレームワークを使用した経験があれば、役立ちます。ただし、必須ではありません。
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +## プログレッシブなフレームワーク
Vue の設計思想の根幹でコンセプトであり、そのタイトルには、単語感に飾り的な助詞を入れなくても大丈夫です。
```suggestion
## プログレッシブフレームワーク
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +柔軟性を備える一方で、Vue が動く仕組みについての中心的な知識は、上に挙げたすべてのユースケースで共通です。今はまだ初心者であっても、進みながら得てゆく知識は、今後もっと大きなプロジェクトに取り組むうえで常に役立つものであり続けます。ベテランであれば、解決したい問題に応じて、生産性を保ちながら Vue を適切に活用する方法を選定できるでしょう。Vue を「プログレッシブなフレームワーク」と呼ん
```suggestion
柔軟性を備える一方で、Vue が動く仕組みについての中心的な知識は、上に挙げたすべてのユースケースで共通です。今はまだ初心者であっても、進みながら得てゆく知識は、今後もっと大きなプロジェクトに取り組むうえで常に役立つものであり続けます。ベテランであれば、解決したい問題に応じて、生産性を保ちながら Vue を適切に活用する方法を選定できるでしょう。Vue を「プログレッシブフレームワーク」と呼んでいる理由は、そこにあります。Vue は、皆さんとともに成長し、皆さんのニーズに適応するフレームワークなのです。
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +  <button @click="count++">カウント: {{ count }}</button>
```suggestion
  <button @click="count++">Count is: {{ count }}</button>
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +  console.log(`カウントの初期値は ${count.value} です。`)
ここも、コード部分は訳さずそのままでお願いします。:pray:
```suggestion
  console.log(`The initial count is ${count.value}.`)
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +  <button @click="increment">カウント: {{ count }}</button>
```suggestion
  <button @click="increment">Count is: {{ count }}</button>
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +オプション API の考え方は、「コンポーネントのインスタンス」(サンプルに見られる `this`) を中心とするもので、OOP 言語の経験のあるユーザーにとってはクラスベースの心理的モデルによく適合します。同時に、オプション API ではリアクティブ性の細かな部分が抽象化され、各オプションのグループによってコードの構成が整理されるため、初心者にとって分かりやすいモデルでもあります。
OOPについて知らない方もいるかもしれないで、ここは注釈しておきたいです。
```suggestion
オプション API の考え方は、「コンポーネントのインスタンス」(サンプルに見られる `this`) を中心とするもので、OOP (Object Oriented Programming: オブジェクト指向プログラミング) 言語の経験のあるユーザーにとってはクラスベースの心理的モデルによく適合します。同時に、オプション API ではリアクティブ性の細かな部分が抽象化され、各オプションのグループによってコードの構成が整理されるため、初心者にとって分かりやすいモデルでもあります。
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +学習を進める段階では、どちらか一方のスタイルにこだわる必要はありません。このドキュメントの続きの部分に登場するコードサンプルは、該当する場合、両方のスタイルで提供されます。左サイドバーの上部にある **API 設定スイッチ**を使って、いつでもスタイルを切り替えることができます。
API Preference は訳さずそのままで大丈夫です。
```suggestion
学習を進める段階では、どちらか一方のスタイルにこだわる必要はありません。このドキュメントの続きの部分に登場するコードサンプルは、該当する場合、両方のスタイルで提供されます。左サイドバーの上部にある **API Preference スイッチ**を使って、いつでもスタイルを切り替えることができます。
```

2022-03-07 06:54 UTC, kazupon commented on src/guide/introduction.md
> +## ラーニングパスを選びましょう
Learning Path の Path はここでは道筋を示すつながりのことを意味しています。なので、それを踏まえて少し意訳気味に訳すと以下な感じでしょうか。
```suggestion
## 学習方法を選びましょう
```

2022-03-09 13:03 UTC, tanquar commented
レビューありがとうございました！修正しました。

- 束縛はバインドに直したほうがよいでしょうか?

2022-03-09 13:42 UTC, jay-es commented
@tanquar ありがとうございます！お手数ですが「バインド」に修正お願いします:bow:

2022-03-09 20:40 UTC, tanquar commented
修正しました！よろしくお願いいたします。

2022-03-10 11:36 UTC, jay-es approved these changes
ありがとうございました:pray:
kazupon さん指摘分の修正も確認したのでマージします！

2022-03-10 11:36 UTC, merged