「API > Composition API > Composition API: setup()」の翻訳
vuejs-translations/docs-ja pull request #334
Opened 2022-03-06 05:41 UTC by shiyuu33

resolve #61
レビューよろしくお願いいたします🙇‍♂️

## 疑問点
- ドキュメントコード内コメントはどこまでが翻訳の対象なのか
    - 旧Vue3の日本語ドキュメントではところどころ英語のままの箇所が存在しました。
     ![スクリーンショット 2022-03-06 14 37 26](https://user-images.githubusercontent.com/46603895/156910744-83cb3deb-bbc7-4bc2-8aa0-bf8ee0b1a002.png)
ご教示いただければ幸いです🙇‍♂️

### 備考
一部の文言は旧Vue3系のドキュメントを参考にしました
https://v3.ja.vuejs.org/guide/composition-api-setup.html#%E5%BC%95%E6%95%B0

2022-03-07 07:01 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
対応お願いします！ 🙏

2022-03-07 09:26 UTC, shiyuu33 commented
@kazupon
ご指摘・ご提案いただいた変更取り込みました!
再レビューよろしくお願いいたします🙇‍♂️

2022-03-07 13:20 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします！:pray:

2022-03-07 13:20 UTC, jay-es commented on src/api/composition-api-setup.md
> +私たちは `setup()` からオブジェクトを返すことによって、 [Reactivity APIs](./reactivity-core.html) を使ったリアクティブな状態を宣言することや、それらを公開することができます。返されたオブジェクトのプロパティは、コンポーネントインスタンス上でも利用することができます (他のオプションが使用されている場合):
1文目の by 以降は expose ~ の部分にかかるのではないかと思います
（また細かいですが、ここの主語はない方が自然かと思いました）

```suggestion
[Reactivity APIs](./reactivity-core.html) を使ってリアクティブな状態を宣言したり、`setup()` からオブジェクトを返すことによってそれらを公開することができます。返されたオブジェクトのプロパティは、コンポーネントインスタンス上でも利用することができます (他のオプションが使用されている場合):
```

2022-03-07 13:20 UTC, jay-es commented on src/api/composition-api-setup.md
> +`setup` から返された [refs](/api/reactivity-core.html#ref) は、テンプレート内でアクセスされたときに[自動的に浅いアンラップ](/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates)であるため、テンプレート内で `.value` を使用すべきではないことに
「アンラップされる」とした方が元のニュアンスに近いかなと思いました
```suggestion
`setup` から返された [refs](/api/reactivity-core.html#ref) は、テンプレート内でアクセスされたときに[自動的に浅くアンラップされる](/guide/essentials/reactivity-fundamentals.html#ref-unwrapping-in-templates)ため、テンプレート内で `.value` を使用する必要はないことに注意してください。また、`this` でアクセスしたときも同様にアンラップされます。
```

2022-03-07 13:20 UTC, jay-es commented on src/api/composition-api-setup.md
> +`setup()` 自体はコンポーネントインスタンスにアクセスしません。- `this` は `setup()` 内の `null` 値を持ちます。Options API から Composition API で公開された値にアクセスすることができますが、その逆はできません。
こちらもニュアンスが少し変わっているので修正お願いします:pray:
```suggestion
`setup()` 自体はコンポーネントインスタンスにアクセスできません。- `this` は `setup()` 内では `null` 値を持ちます。Options API から Composition API で公開された値にアクセスすることができますが、その逆はできません。
```

2022-03-07 13:20 UTC, jay-es commented on src/api/composition-api-setup.md
> +    // `title` は `props.title` を追跡する参照です
```suggestion
    // `title` は `props.title` を追跡する ref です
```

2022-03-07 13:20 UTC, jay-es commented on src/api/composition-api-setup.md
> +context オブジェクトはリアクティブではなく、安全に分割代入されます:
```suggestion
context オブジェクトはリアクティブではなく、安全に分割代入できます:
```

2022-03-07 13:20 UTC, jay-es commented on src/api/composition-api-setup.md
> +私たちは [`expose()`](#exposing-public-properties) を呼び出すことによって、この問題を解決することができます:
```suggestion
[`expose()`](#exposing-public-properties) を呼び出すことによって、この問題を解決することができます:
```

2022-03-08 15:58 UTC, shiyuu33 commented
@kazupon @jay-es 
2回目レビューに関する修正をいたしました!
ご確認の程よろしくお願いいたします!

2022-03-09 12:08 UTC, jay-es approved these changes
ありがとうございます！:pray:
@kazupon さんのご指摘分も修正されているのでマージしますね

2022-03-09 12:09 UTC, merged