「Tutorial > Form Bindings」の翻訳
vuejs-translations/docs-ja pull request #343
Opened 2022-03-07 13:52 UTC by kzhrk

resolve #95

https://vuejs.org/tutorial/#step-5 を翻訳しました。
レビューお願いします 🙏

2022-03-08 12:16 UTC, jay-es requested changes
レビューしました！

2022-03-08 12:16 UTC, jay-es commented on src/tutorial/src/step-5/description.md
> +# フォーム入力バインディング
原題に合わせました
```suggestion
# フォームバインディング
```

2022-03-08 12:16 UTC, jay-es commented on src/tutorial/src/step-5/description.md
> +`v-model` は `<input>` の値をバインドされた状態と自動的に同期するので、そのためのイベントハンドラーを使う必要はありません。
用語集では bind を「束縛」とするようになっていますが、上でずっと「バインディング」と書いてきているので合わせるか悩ましいところですね...
```suggestion
`v-model` は `<input>` の値を束縛された状態と自動的に同期するので、そのためのイベントハンドラーを使う必要はありません。
```

2022-03-08 13:59 UTC, kzhrk commented on src/tutorial/src/step-5/description.md
> +`v-model` は `<input>` の値をバインドされた状態と自動的に同期するので、そのためのイベントハンドラーを使う必要はありません。
双方向バインディングやフォームバインディングで紐付けられる的なニュアンスは伝わっているので、このページではバインドの方が意味が伝わりやすいのかなと思いました。
とはいえ、用語集でルール統一しているのであれば「束縛」に集約するのも一理ありだと思いました。

Vue3のドキュメントで「バインド」を検索しても一定数ヒットする & 双方向バインディングという言葉も浸透しているのでbind はバインドするを許容してもよいのかなと思いました。
<img width="582" alt="スクリーンショット 2022-03-08 22 53 56" src="https://user-images.githubusercontent.com/548508/157252210-af7f2f88-5236-49b1-bc8c-18e0ba76293e.png">

「バインドする」の翻訳を許容する場合、用語集の「[日本語にする](https://github.com/vuejs-translations/docs-ja/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E#%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%AB%E3%81%99%E3%82%8B)」から「bind」を取り除く必要もあるかと思います。
最終判断はメンテナーの皆様におまかせします 🙏

2022-03-09 06:50 UTC, kazupon commented on src/tutorial/src/step-5/description.md
> +`v-model` は `<input>` の値をバインドされた状態と自動的に同期するので、そのためのイベントハンドラーを使う必要はありません。
自分が、これまで Vue の初期から関わって来た身からすると、バインドはという用語は訳さなくても、意味が理解できるようになってきているのを見てきているので、`束縛` と訳すより、カタカナ日本語でもよいと思っています。
なので、用語集からも削除してもいいかと。

2022-03-09 06:50 UTC, kazupon approved these changes
翻訳ありがとうございます。
一通りみました。
特に問題ないです。

2022-03-09 12:12 UTC, merged

2022-03-09 12:13 UTC, jay-es commented on src/tutorial/src/step-5/description.md
> +`v-model` は `<input>` の値をバインドされた状態と自動的に同期するので、そのためのイベントハンドラーを使う必要はありません。
用語集は「バインドする」と訳すよう修正しておきます:pray: