translate tutorial step 3: Attribute Bindings
vuejs-translations/docs-ja pull request #356
Opened 2022-03-11 09:21 UTC by Robjam

resolves #93

2022-03-11 12:48 UTC, jay-es requested changes
レビューしました。何点か修正お願いします:pray:

2022-03-11 12:48 UTC, jay-es commented on src/tutorial/src/step-3/description.md
> +Vue では mustaches (二重中括弧)がテキスト補間のみ使用します。動的な値が属性にバインドするのは、`v-bind` ディレクティブを使います：
カッコを全角にしました。
「が」→「を」に変更しました。
```suggestion
Vue では mustaches（二重中括弧）はテキスト補間のみ使用します。動的な値を属性にバインドするのは、`v-bind` ディレクティブを使います：
```

2022-03-11 12:48 UTC, jay-es commented on src/tutorial/src/step-3/description.md
> +コロン（`:id`）の後の部分はディレクティブの「引数」です。ここでは要素の `id` はコンポーネントの状態から `dynamicId` 属性と同期されます。
カッコの位置を移動しました
```suggestion
コロンの後の部分（`:id`）はディレクティブの「引数」です。ここでは要素の `id` はコンポーネントの状態から `dynamicId` 属性と同期されます。
```

2022-03-14 15:10 UTC, kazupon approved these changes
自分も見ました。
よさそうです！

2022-03-15 10:50 UTC, jay-es approved these changes
修正ありがとうございます！
問題なさそうなのでマージします

2022-03-15 10:51 UTC, merged