「Tutorial > Computed Property」の翻訳
vuejs-translations/docs-ja pull request #358
Opened 2022-03-11 14:28 UTC by kzhrk

resolve https://github.com/vuejs-translations/docs-ja/issues/98

https://vuejs.org/tutorial/#step-8 を翻訳しました。
レビューお願いします 🙏

2022-03-14 12:05 UTC, jay-es requested changes
レビューしました！
`computed ref` については他の方の意見も伺いたいです

2022-03-14 12:05 UTC, jay-es commented on src/tutorial/src/step-8/description.md
> +次の変更点はすでに完了した Todo を隠すことができるようにすることです。すでに `hideCompleted` 状態をトグルするボタンがあります。しかし、その状態に基づいて異なるリスト項目をレンダリングするにはどうしたらよいでしょうか？
「こと」が続いているので、省略した方が読みやすいと思いました
```suggestion
次の変更点はすでに完了した Todo を隠せるようにすることです。すでに `hideCompleted` 状態をトグルするボタンがあります。しかし、その状態に基づいて異なるリスト項目をレンダリングするにはどうしたらよいでしょうか？
```

2022-03-14 15:17 UTC, kazupon requested changes
コメントしたところ以外、全般的によさそうです。
コメントの部分対応お願いします。

2022-03-14 15:17 UTC, kazupon commented on src/tutorial/src/step-8/description.md
> +<a target="_blank" href="/guide/essentials/computed.html">`computed()`</a> の紹介です。他のリアクティブなデータソースに基づいて `.value` を計算する算出参照をつくることができます:
この markdown では算出プロパティーにゆいて説明しているので、ここでの文脈では、`算出 ref` という訳でもよさそうです。

2022-03-15 06:37 UTC, kzhrk commented on src/tutorial/src/step-8/description.md
> +<a target="_blank" href="/guide/essentials/computed.html">`computed()`</a> の紹介です。他のリアクティブなデータソースに基づいて `.value` を計算する算出参照をつくることができます:
`算出 ref` にしておきます！

2022-03-15 06:39 UTC, kzhrk commented on src/tutorial/src/step-8/description.md
> +次の変更点はすでに完了した Todo を隠すことができるようにすることです。すでに `hideCompleted` 状態をトグルするボタンがあります。しかし、その状態に基づいて異なるリスト項目をレンダリングするにはどうしたらよいでしょうか？
たしかに suggest いただいた文章のほうが読みやすいですね 🙏 
取り込みます。

2022-03-15 06:43 UTC, kzhrk commented on src/tutorial/src/step-8/description.md
> +<a target="_blank" href="/guide/essentials/computed.html">`computed()`</a> の紹介です。他のリアクティブなデータソースに基づいて `.value` を計算する算出参照をつくることができます:
fix [eb660c2](https://github.com/vuejs-translations/docs-ja/pull/358/commits/eb660c2f90eef4a27a4766a4e07738e4a9e7a7f6)

2022-03-15 10:59 UTC, jay-es commented on src/tutorial/src/step-8/description.md
> +<a target="_blank" href="/guide/essentials/computed.html">`computed()`</a> の紹介です。他のリアクティブなデータソースに基づいて `.value` を計算する算出参照をつくることができます:
他のページにも出てくるので用語集に入れておきます:pray:

2022-03-15 11:00 UTC, jay-es approved these changes
ありがとうございます！
修正確認できましたのでマージします

2022-03-15 11:00 UTC, merged