Guide essentials template syntax
vuejs-translations/docs-ja pull request #359
Opened 2022-03-12 07:31 UTC by tanquar

resolve #8

2022-03-14 13:05 UTC, jay-es requested changes
`directive.png` は 2MB 以上あるようなので、オリジナルのファイルサイズと同等になるくらいに軽量化をお願いします:pray:

2022-03-14 13:05 UTC, jay-es commented on src/guide/essentials/template-syntax.md
> +その他の修飾子の例として、後ほど [`v-on` のイベント修飾子](./event-handling.html#event-modifiers)や [`v-model` の修飾子](./forms.html#modifiers)などを目にする機会があります。それぞれの機能を学びながらご確認ください。
なかなか難しいですが、なるべく原文の意味に合うようにしてみました:bow:
```suggestion
この後、[`v-on` 向け](./event-handling.html#event-modifiers)や [`v-model` 向け](./forms.html#modifiers)の修飾子の例を、その機能のページで見ることになるでしょう。
```

2022-03-17 12:28 UTC, tanquar commented
レビューありがとうございました! ご指摘の箇所を反映しました。
画像はまだ未調整です。今週末に対応しようと思います。

2022-03-18 10:39 UTC, jay-es requested changes
折りたたまれている箇所の修正が残っているのでご対応お願いします:pray:
（`Load more...` を押すと内容が表示されます）
![image](https://user-images.githubusercontent.com/46585162/158988111-92e32957-fea5-498e-b3f3-1e65a29d4dfa.png)

2022-03-18 22:31 UTC, tanquar commented
ありがとうございます!
折りたたみ機能に気づきませんでした。。。反映しました!
図をFigmaで作り直して、en:47KB→53KBに収まりました。
よろしくお願いします。

2022-03-18 22:39 UTC, tanquar commented on src/guide/essentials/template-syntax.md
> +「動的引数の値に関する制約」および「動的引数の構文上の制約」セクションで説明します。
承知しました!
https://github.com/vuejs/docs/pull/1613 が取り込まれたので、最後のコミットで復活させました。

2022-03-21 11:50 UTC, jay-es reviewed
修正ありがとうございます！
自分はこの内容で問題ないと思います:ok_man:

2022-03-21 15:47 UTC, kazupon approved these changes
レビュー遅くなりました。:bow:
いいですね！
図までやって頂いてありがとうございます！

2022-03-22 11:04 UTC, merged