「Tutorial > Declarative Rendering」の翻訳
vuejs-translations/docs-ja pull request #364
Opened 2022-03-13 06:46 UTC by tutti2612

resolve #92

2022-03-14 13:13 UTC, jay-es requested changes
レビューしました。
2箇所修正をお願いします:pray:

2022-03-14 13:13 UTC, jay-es commented on src/tutorial/src/step-2/description.md
> +変更されたときに更新のトリガーとなるような状態は**リアクティブ**とみなされます。`reactive()` API を使用してリアクティブな状態を宣言することができます。`reactive()` で生成されるオブジェクトは JavaScript の [プロキシ](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Glo
```suggestion
変更されたときに更新のトリガーとなるような状態は**リアクティブ**とみなされます。Vue の `reactive()` API を使用してリアクティブな状態を宣言することができます。`reactive()` で生成されるオブジェクトは JavaScript の [プロキシ](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Proxy) であり、通常のオブジェクトと同様に動作します:
```

2022-03-14 13:13 UTC, jay-es commented on src/tutorial/src/step-2/description.md
> +mustaches の内側の内容は ID やパスに限られません。有効な JavaScript の表現であれば何でも使うことができます。:
```suggestion
mustaches の内側の内容は識別子やパスに限られません。有効な JavaScript の式であれば何でも使うことができます。:
```

2022-03-14 15:25 UTC, kazupon submitted a review, later dismissed
レビュー 👀 コメント 💬 しました。
確認お願いします。

2022-03-14 15:25 UTC, kazupon commented on src/tutorial/src/step-2/description.md
> +`reactive()` はオブジェクト（配列や `Map` や `Set` のような組み込み型も含む）に対してのみ動作します。一方、`ref()` は、任意の値の型を取り、`.value` プロパティの下で内部の値を公開するオブジェクトを作成することができます。:
文章の最後にある `:` は、翻訳に対応させるときは、読点`。`+ `:`ではなく、`:` で大丈夫です。

```suggestion
`reactive()` はオブジェクト（配列や `Map` や `Set` のような組み込み型も含む）に対してのみ動作します。一方、`ref()` は、任意の値の型を取り、`.value` プロパティの下で内部の値を公開するオブジェクトを作成することができます:
```

2022-03-14 15:25 UTC, kazupon commented on src/tutorial/src/step-2/description.md
> +コンポーネントの `<script setup>` ブロックで宣言されたリアクティブステートはテンプレートで直接使用することができます。このようにして、mustaches 構文を使い、 `state` オブジェクトと `message` ref の値に基づいて動的なテキストをレンダリングすることができます。:
`:` 同じく。

```suggestion
コンポーネントの `<script setup>` ブロックで宣言されたリアクティブステートはテンプレートで直接使用することができます。このようにして、mustaches 構文を使い、 `state` オブジェクトと `message` ref の値に基づいて動的なテキストをレンダリングすることができます:
```

2022-03-14 15:25 UTC, kazupon commented on src/tutorial/src/step-2/description.md
> +`createApp()` に渡されるオブジェクトは Vue のコンポーネントです。コンポーネントの状態は、その `setup()` 関数内で宣言され、オブジェクトを使用して返される必要があります。:
`:` 同じく。
```suggestion
`createApp()` に渡されるオブジェクトは Vue のコンポーネントです。コンポーネントの状態は、その `setup()` 関数内で宣言され、オブジェクトを使用して返される必要があります:
```

2022-03-14 15:25 UTC, kazupon commented on src/tutorial/src/step-2/description.md
> +返されたオブジェクトのプロパティはテンプレートで利用できるようになります。このようにして、mustaches 構文を使い、 `message` の値に基づいて動的なテキストをレンダリングすることができます。:
`:` 同じく。
```suggestion
返されたオブジェクトのプロパティはテンプレートで利用できるようになります。このようにして、mustaches 構文を使い、 `message` の値に基づいて動的なテキストをレンダリングすることができます:
```

2022-03-14 15:25 UTC, kazupon commented on src/tutorial/src/step-2/description.md
> +mustaches の内側の内容は識別子やパスに限られません。有効な JavaScript の式であれば何でも使うことができます。:
`:` 同じく。
```suggestion
mustaches の内側の内容は識別子やパスに限られません。有効な JavaScript の式であれば何でも使うことができます:
```

2022-03-15 05:27 UTC, tutti2612 commented
@kazupon
指摘箇所を修正しました。
再レビューお願いします！

2022-03-15 10:55 UTC, jay-es approved these changes
修正ありがとうございます！:pray:
kazupon さんの箇所も直っているのでマージします

2022-03-15 10:56 UTC, merged