「Tutorial > You Did It!」の翻訳
vuejs-translations/docs-ja pull request #379
Opened 2022-03-15 11:10 UTC by yuri-htt

resolve https://github.com/vuejs-translations/docs-ja/issues/91

2022-03-16 12:53 UTC, jay-es requested changes
レビューしました。
1点修正お願いします:pray:

2022-03-16 12:53 UTC, jay-es commented on src/tutorial/src/step-15/description.md
> +この時点で、Vue を使った作業がどのようなものであるかは、よく理解できたはずです。しかし、私たちは多くのことを本当に速く学習し、細部には目を瞑ってきました。ですからぜひ学習を継続してください！次のステップとして、次のことができます。:
句点削除お願いします:pray:
```suggestion
この時点で、Vue を使った作業がどのようなものであるかは、よく理解できたはずです。しかし、私たちは多くのことを本当に速く学習し、細部には目を瞑ってきました。ですからぜひ学習を継続してください！次のステップとして、次のことができます:
```

2022-03-17 06:48 UTC, kazupon approved these changes
内容確認しました。
jay-es さん以外の部分以外は特にありませんでした。
そこの修正お願いします。

2022-03-17 11:41 UTC, yuri-htt commented
📩 レビュワーさんへ

レビューありがとうございます。
ご丁寧にsuggestをしていただきましたので、その内容に置き換える形でご指摘の3点を修正いたしました。
再度ご確認お願いいたします。

2022-03-18 10:30 UTC, jay-es approved these changes
修正ありがとうございます！:pray:

2022-03-18 10:31 UTC, merged