「Tutorial > Watchers」の翻訳
vuejs-translations/docs-ja pull request #380
Opened 2022-03-15 12:29 UTC by ttt3pu

resolve #86

2022-03-16 13:00 UTC, jay-es requested changes
レビューしました。
1点修正お願いします:pray:

2022-03-17 01:11 UTC, ttt3pu commented on src/tutorial/src/step-10/description.md
> +時には "side effects (副作用)" を反応的に実行する必要があるかもしれません - 例えば、数値が変化したときにコンソールにログを記録するといったことです。これはウォッチャーで実現することができます:
@jay-es レビューありがとうございます。下記コミットで修正いたしました 🙇 
https://github.com/vuejs-translations/docs-ja/pull/380/commits/b63051435e82b0383b282e00ab49265fed8d0850

2022-03-17 06:51 UTC, kazupon approved these changes
翻訳内容みました。
よさそうです。

2022-03-18 10:03 UTC, jay-es approved these changes
修正ありがとうございます！:pray:

2022-03-18 10:03 UTC, merged