Translate tutorial slots
vuejs-translations/docs-ja pull request #382
Opened 2022-03-15 15:50 UTC by gyvm

resolve #90 
ご確認お願いいたします。

2022-03-15 15:56 UTC, gyvm commented on src/tutorial/src/step-14/description.md
> +`<slot>` アウトレット内のコンテンツは、"フォールバック" コンテンツとして扱われます。また、親コンポーネントがスロットコンテンツを渡さなかった場合には表示されます。:
`また、`の箇所は`:`を意訳しました。

2022-03-15 15:59 UTC, gyvm commented on src/tutorial/src/step-14/description.md
> +子コンポーネントでは、 `<slot>` 要素をアウトレットとして使用した親コンポーネントからスロットコンテンツをレンダリングできます。:
`parent`を親コンポーネントとしました。
コンポーネントを付けたほうが読みやすいと感じたので、この行以外も付けて訳しています。

2022-03-16 13:27 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-03-16 13:27 UTC, jay-es commented on src/tutorial/src/step-14/description.md
> +プロパティを経由したデータの受け渡しだけでなく、親コンポーネントはテンプレートフラグメントを **スロット** を経由して子コンポーネントへ渡すこともできます。:
props はそのままの方が分かりやすいかなと思いました
```suggestion
props を経由したデータの受け渡しだけでなく、親コンポーネントはテンプレートフラグメントを **スロット** を経由して子コンポーネントへ渡すこともできます。:
```

2022-03-16 13:27 UTC, jay-es commented on src/tutorial/src/step-14/description.md
> +子コンポーネントでは、 `<slot>` 要素をアウトレットとして使用した親コンポーネントからスロットコンテンツをレンダリングできます。:
元のニュアンスに近づけるよう調整しました
```suggestion
子コンポーネントでは、 `<slot>` 要素をアウトレットとして使用し、親コンポーネントからのスロットコンテンツをレンダリングできます。:
```

2022-03-16 13:27 UTC, jay-es commented on src/tutorial/src/step-14/description.md
> +`<slot>` アウトレット内のコンテンツは、"フォールバック" コンテンツとして扱われます。また、親コンポーネントがスロットコンテンツを渡さなかった場合には表示されます。:
前の文に対して付加や列挙していないので「また」はない方がいいかなと思いました。
文末のコロンの前の句点は不要なので削除しました。
```suggestion
`<slot>` アウトレット内のコンテンツは、"フォールバック" コンテンツとして扱われます。親コンポーネントがスロットコンテンツを渡さなかった場合に表示されます:
```

2022-03-16 14:28 UTC, gyvm commented
レビューありがとうございます！
修正したので再度、確認をお願いいたします。

文末のコロンの前の句点は指摘いただいた箇所以外にもあったので、それも削除しました。https://github.com/vuejs-translations/docs-ja/pull/382/commits/ac8bdb8b7ece1c56f784bdf03bbf544e0a789a0a

2022-03-17 06:53 UTC, kazupon approved these changes
内容確認しました。
よさそうです！

2022-03-18 10:09 UTC, jay-es approved these changes
修正ありがとうございます！:pray:

2022-03-18 10:09 UTC, merged