「Tutorial > Emits」の翻訳
vuejs-translations/docs-ja pull request #386
Opened 2022-03-17 10:27 UTC by tutti2612

resolve #89

レビューお願いします！

2022-03-18 10:22 UTC, jay-es commented on src/tutorial/src/step-13/description.md
> +プロパティを受け取るだけでなく、子コンポーネントは親コンポーネントにイベントを発することもできます:
`props` はそのままにしました
```suggestion
props を受け取るだけでなく、子コンポーネントは親コンポーネントにイベントを発することもできます:
```

2022-03-18 10:27 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-03-18 10:27 UTC, jay-es commented on src/tutorial/src/step-13/description.md
> +親は `v-on` を使って子が発するイベントを聞くことができます。ここでは、ハンドラーは子の emit 呼び出しから余分な引数を受け取り、それをローカルステートに割り当てています:
「聞く」だと分かりにくいため「リッスン」にしました。
また「余分な」とすると若干ネガティブな印象になるので「追加の」にしました。
```suggestion
親は `v-on` を使って、子が発するイベントをリッスンすることができます。ここでは、ハンドラーは子の emit 呼び出しから追加の引数を受け取り、それをローカルステートに割り当てています:
```

2022-03-19 16:11 UTC, tutti2612 commented
@jay-es 
指摘箇所を修正しました。
再レビューお願いします！

2022-03-22 11:05 UTC, merged