「Guide > Scaling Up > Single-File Components」の翻訳
vuejs-translations/docs-ja pull request #390
Opened 2022-03-20 16:11 UTC by komura-c

resolve #35

2022-03-21 12:21 UTC, jay-es requested changes
レビューしました。
ご確認よろしくお願いします:pray:

2022-03-21 12:21 UTC, jay-es commented on src/guide/scaling-up/sfc.md
> +## 使い方
愚直に訳すと「どのように動作しているか」なので「使い方」だと少し違和感がありました
```suggestion
## 仕組み
```

2022-03-21 16:06 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願います！

2022-03-21 16:06 UTC, kazupon commented on src/guide/scaling-up/sfc.md
> +単一ファイルコンポーネントのアイデアが気に入らない場合でも、[Src Imports](/api/sfc-spec.html#src-imports) を使用して JavaScript と CSS を別々のファイルに分割することで、ホットリロードと事前コンパイル機能を活用できることに注意してください。
`don't like` の訳ですが、docs はいろんな人読むので、表現は少し以下のようにソフトにお願いします。

```suggestion
単一ファイルコンポーネントのアイデアが好まない場合でも、[Src Imports](/api/sfc-spec.html#src-imports) を使用して JavaScript と CSS を別々のファイルに分割することで、ホットリロードと事前コンパイル機能を活用できることに注意してください。
```

2022-03-26 15:45 UTC, komura-c commented
レビューいただきありがとうございます！🙇‍♂️
修正しましたので、ご確認よろしくお願いします🙏

2022-03-27 13:20 UTC, kazupon approved these changes

2022-03-27 13:21 UTC, kazupon commented
改めて確認しました！
LGTMです！

2022-03-28 11:56 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-03-28 11:56 UTC, merged