「Guide > Built-in Components > Teleport」の翻訳
vuejs-translations/docs-ja pull request #396
Opened 2022-03-21 10:31 UTC by yamanoku

resolve #33

2022-03-21 10:34 UTC, yamanoku commented on src/guide/built-ins/teleport.md
> +- モーダルの `z-index` は、それを含む要素によって制約されます。もし `<div class="outer">` と重なった、より高い `z-index` の値が設定された別の要素があれば、モーダルコンポーネントを覆ってしまうかもしれません。
> it would cover our modal.

の `our modal` を `<MyModal>` と見なして、以下のように意訳しました。

> モーダルコンポーネントを覆ってしまうかもしれません。

2022-03-21 12:34 UTC, jay-es requested changes
レビューしました。
1点修正お願いします:pray:

2022-03-21 12:34 UTC, jay-es commented on src/guide/built-ins/teleport.md
> +そして、以下が `<MyModal>` の実装です。
行末をコロンに変更お願いします
```suggestion
そして、以下が `<MyModal>` の実装です:
```

2022-03-21 12:37 UTC, yamanoku commented on src/guide/built-ins/teleport.md
> +そして、以下が `<MyModal>` の実装です。
[`095a7f9` (#396)](https://github.com/vuejs-translations/docs-ja/pull/396/commits/095a7f95b7e2223f7765cae5cfbc0de8da6286a0) にて変更いたしました

2022-03-21 16:09 UTC, kazupon commented on src/guide/built-ins/teleport.md
> +  <h3>Vue Teleport の例</h3>
コードに出てくる英語は基本原文のままで大丈夫です。`<!-- -->` 、 `// ... ` 、`/* ... */` といったコメントは翻訳していただいてOKです〜

2022-03-21 16:10 UTC, kazupon commented on src/guide/built-ins/teleport.md
> +  <h3>Vue Teleport の例</h3>
以降も同じく、お願いします！

2022-03-21 16:13 UTC, kazupon commented on src/guide/built-ins/teleport.md
> +- モーダルの `z-index` は、それを含む要素によって制約されます。もし `<div class="outer">` と重なった、より高い `z-index` の値が設定された別の要素があれば、モーダルコンポーネントを覆ってしまうかもしれません。
はい！文脈的に訳して頂いた内容で問題ないです。

2022-03-21 16:16 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2022-03-22 00:01 UTC, yamanoku commented on src/guide/built-ins/teleport.md
> +`<Teleport>` は、ネストされた DOM 構造から抜け出せるようにすることで、これらの問題を回避するクリーンな方法を提供します。それでは、`<MyModal>` を修正して、 `<Teleport>` を使用するようにしてみましょう。
[`5fff814` (#396)](https://github.com/vuejs-translations/docs-ja/pull/396/commits/5fff814de5ecb7d78e30cfca99ca16f1f2a0edbf) にて対応いたしました。

2022-03-22 00:10 UTC, yamanoku commented on src/guide/built-ins/teleport.md
> +  <h3>Vue Teleport の例</h3>
[`ad99abf` (#396)](https://github.com/vuejs-translations/docs-ja/pull/396/commits/ad99abf905641e3ebac44a51dc1ca06c5ed45e8c) にて対応いたしました

2022-03-22 06:04 UTC, kazupon approved these changes

2022-03-22 06:05 UTC, kazupon commented
レビュー指摘事項の対応ありがとうございます！
@jay-es さんの指摘事項も対応されているので、マージしますね！

2022-03-22 06:05 UTC, merged