「Guide > Getting Started > Quick Start」の翻訳
vuejs-translations/docs-ja pull request #397
Opened 2022-03-22 09:31 UTC by u-sho

resolve #5 

遅くなりました。すみません :bow:

2022-03-22 11:15 UTC, jay-es requested changes
なにやらコミット履歴がおかしくなっている（差分が27ファイルあるなど）ので、最新の main を取り込むか、新しいブランチでPR再作成お願いします:bow:

2022-03-24 23:48 UTC, u-sho commented
@jay-es 
ツリー修正しました :bow:　よろしくお願いします！

2022-03-25 12:30 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-03-25 12:30 UTC, jay-es commented on src/guide/quick-start.md
> +このコマンドは、Vue プロジェクトの公式 scaffolding (足場材) ツールである [create-vue](https://github.com/vuejs/create-vue) をインストールして実行します。TypeScript やテストのサポートといった複数のオプション機能がプロンプトに表示されます:
scaffold は訳してしまうと分かりにくいのでカタカナのままが良いかなと思いました 
```suggestion
このコマンドは、公式の Vue プロジェクトスキャフォールディングツールである [create-vue](https://github.com/vuejs/create-vue) をインストールして実行します。TypeScript やテストのサポートといった複数のオプション機能がプロンプトに表示されます:
```

2022-03-25 12:30 UTC, jay-es commented on src/guide/quick-start.md
> +- 礎となっているビルドツール Vite について学ぶには、[Vite のドキュメント](https://vitejs.dev/) を確認しましょう。
日本語ドキュメントの URL に変更お願いします
```suggestion
- 礎となっているビルドツール Vite について学ぶには、[Vite のドキュメント](https://ja.vitejs.dev/) を確認しましょう。
```

2022-03-25 12:30 UTC, jay-es commented on src/guide/quick-start.md
> +上の例ではグローバル `Vue` 変数の下で公開されているすべての Vue API が Vue のグローバルビルドを使っています。
語順の入れ替え
```suggestion
上の例ではグローバル `Vue` 変数の下ですべての API が公開されている、Vue のグローバルビルドを使っています。
```

2022-03-25 12:30 UTC, jay-es commented on src/guide/quick-start.md
> +グローバルビルドは機能しますが、以降のドキュメントでは一貫性を保つため主に [ES modules](https://developer.mozilla.org/docs/Web/JavaScript/Guide/Modules) を使用します。ネイティブ ES モジュールで Vue を使うには、代わりに次の HTML を使用してください。
```suggestion
グローバルビルドは機能しますが、以降のドキュメントでは一貫性を保つため主に [ES modules](https://developer.mozilla.org/docs/Web/JavaScript/Guide/Modules) 構文を使用します。ネイティブ ES モジュールで Vue を使うには、代わりに次の HTML を使用してください。
```

2022-03-25 12:30 UTC, jay-es commented on src/guide/quick-start.md
> +コード中の `'vue'` から直接インポートする方法に注目してください - これは `<script type="importmap">` によって可能になり、[Import Maps](https://caniuse.com/import-maps) と呼ばれるネイティブのブラウザー機能を活用します。Import maps は現在のところ Chromium-ベースのブラウザーのみで利用可能な
ハイフンを削除しました
```suggestion
コード中の `'vue'` から直接インポートする方法に注目してください - これは `<script type="importmap">` によって可能になり、[Import Maps](https://caniuse.com/import-maps) と呼ばれるネイティブのブラウザー機能を活用します。Import maps は現在のところ Chromium ベースのブラウザーのみで利用可能なので、学習過程の間は Chrome または Edge の使用を推奨します。あなたイチオシのブラウザーがまだ import maps に対応していなくとも、[es-module-shims](https://github.com/guybedford/es-module-shims) でポリフィル (polyfill) できます。
```

2022-03-25 23:51 UTC, u-sho commented on src/guide/quick-start.md
> +- 礎となっているビルドツール Vite について学ぶには、[Vite のドキュメント](https://vitejs.dev/) を確認しましょう。
0224f84 にて、他のサイトのリンクと一緒に修正しました。

2022-03-25 23:55 UTC, u-sho commented
レビューありがとうございます！　修正受け入れました。
日本語ドキュメントの URL については Vite のみでしたか？（MDN, Node.js は英語サイトのまま等）

2022-03-26 13:37 UTC, jay-es approved these changes
他のサイト URL も日本語のものに差し替えていただきありがとうございます！:bow:

2022-03-27 13:36 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします。

2022-03-27 13:36 UTC, kazupon commented on src/guide/quick-start.md
> +- 礎となっているビルドツール Vite について学ぶには、[Vite のドキュメント](https://ja.vitejs.dev/) を確認しましょう。
`underlying` の訳は、`基礎となる` だと思いますが、typo している気がします。
```suggestion
- 基礎となっているビルドツール Vite について学ぶには、[Vite のドキュメント](https://ja.vitejs.dev/) を確認しましょう。
```

2022-03-27 13:36 UTC, kazupon commented on src/guide/quick-start.md
> +コード中の `'vue'` から直接インポートする方法に注目してください - これは `<script type="importmap">` によって可能になり、[Import Maps](https://caniuse.com/import-maps) と呼ばれるネイティブのブラウザー機能を活用します。Import maps は現在のところ Chromium ベースのブラウザーのみで利用可能な
一応公式ドキュメントなので、`preferred` の訳を `イチオシ` ではなく、`好む` で訳す方がいいですね。以下な感じになるでしょう。

```suggestion
コード中の `'vue'` から直接インポートする方法に注目してください - これは `<script type="importmap">` によって可能になり、[Import Maps](https://caniuse.com/import-maps) と呼ばれるネイティブのブラウザー機能を活用します。Import maps は現在のところ Chromium ベースのブラウザーのみで利用可能なので、学習過程の間は Chrome または Edge の使用を推奨します。あなたの好むブラウザーがまだ import maps に対応していなくとも、[es-module-shims](https://github.com/guybedford/es-module-shims) でポリフィル (polyfill) できます。
```

2022-03-27 13:36 UTC, kazupon commented on src/guide/quick-start.md
> +あなたのアプリをプロダクション環境に出す準備ができたら、これを実行してください:
`following` の訳を `これ` でも、このセクションの文脈上理解はできるのですが、ここでは、`以下` でなるべく原文を考慮しましょう。
```suggestion
あなたのアプリをプロダクション環境に出す準備ができたら、以下を実行してください:
```

2022-03-28 00:13 UTC, u-sho commented on src/guide/quick-start.md
> +- 礎となっているビルドツール Vite について学ぶには、[Vite のドキュメント](https://ja.vitejs.dev/) を確認しましょう。
typo ではなく思い違いでした 😓 
（`underlying` は建築用語としての `基礎` の意味で使われることが多いと思っていました）

2022-03-28 00:24 UTC, u-sho commented
@kazupon 
レビューありがとうございます！　修正受け入れました 🐣 
確認よろしくお願いします

2022-04-02 11:45 UTC, kazupon approved these changes

2022-04-02 11:45 UTC, kazupon commented
@u-sho 
すいません、遅くなりました！
対応ありがとうございました！

2022-04-02 11:45 UTC, merged