API > Advanced APIs > Utility Types」の翻訳 #82
vuejs-translations/docs-ja pull request #415
Opened 2022-03-26 22:37 UTC by kakikubo

resolve #82

FIXME

2022-03-26 23:03 UTC, kakikubo commented on src/api/utility-types.md
> +  <div :style="{ '--bg-color': 'blue' }"></div>
```suggestion
  <div :style="{ '--bg-color': 'blue' }">
```

2022-03-26 23:47 UTC, kakikubo commented on src/api/utility-types.md
> +このページには、一般的に使われるもののうち、使用法の説明が必要ないくつかのユーティリティー型のみがリストされています。export された型の完全なリストについては、[ソースコード](https://github.com/vuejs/core/blob/main/packages/runtime-core/src/index.ts#L131)を参照してください。
```suggestion
このページでは、一般的に使われるものの中から、使用法の説明が必要ないくつかのユーティリティー型のみがリストされています。export された型の完全なリストについては、[ソースコード](https://github.com/vuejs/core/blob/main/packages/runtime-core/src/index.ts#L131)を参照してください。
```

2022-03-27 02:50 UTC, kakikubo commented on src/api/utility-types.md
> +  拡張するには、モジュールを `.ts` または `.d.ts` ファイルとして配置する必要があります。詳細は[グローバルプロパティの拡張](/guide/typescript/options-api.html#augmenting-global-properties)を参照してください。
移行、何度か同じtipが出てきていますが、すべて同じ翻訳にしています。

2022-03-27 02:51 UTC, kakikubo commented on src/api/utility-types.md
> +- **参照:** [ガイド - グローバルプロパティの拡張](/guide/typescript/options-api.html#augmenting-global-properties)
ここは先に翻訳をしてしまいましたが、問題あれば戻します。

2022-03-27 02:52 UTC, kakikubo commented on src/api/utility-types.md
> +SFC `<style>` タグは、`v-bind CSS` 関数を使って、CSS の値を動的コンポーネントの状態にリンクすることをサポートしています。
こちらは [状態ドリブンな動的 CSS](https://v3.ja.vuejs.org/api/sfc-style.html#%E7%8A%B6%E6%85%8B%E3%83%88%E3%82%99%E3%83%AA%E3%83%95%E3%82%99%E3%83%B3%E3%81%AA%E5%8B%95%E7%9A%84-css)をそのまま参考にさせて頂きました。

2022-03-27 15:40 UTC, kazupon approved these changes
翻訳ありがとうございます！
確認しました。
良さそうです！

2022-03-28 12:04 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-03-28 12:04 UTC, jay-es commented on src/api/utility-types.md
> +- **See also:** [ガイド - コンポーネントプロパティの型付け](/guide/typescript/options-api.html#typing-component-props)
```suggestion
- **参照:** [ガイド - コンポーネントプロパティの型付け](/guide/typescript/options-api.html#typing-component-props)
```

2022-03-28 12:04 UTC, jay-es commented on src/api/utility-types.md
> +
行がずれるため削除お願いします:pray:
```suggestion
```

2022-03-28 12:04 UTC, jay-es commented on src/api/utility-types.md
> +  // helloが宣言されていないプロパティでも使えるようになります
スペースの追加
```suggestion
  // hello が宣言されていないプロパティでも使えるようになります
```

2022-03-28 12:04 UTC, jay-es commented on src/api/utility-types.md
> +        // より具体的な型を`Object`に提供します
スペースの追加
```suggestion
        // より具体的な型を `Object` に提供します
```

2022-03-29 08:20 UTC, kakikubo commented on src/api/utility-types.md
> +- **See also:** [ガイド - コンポーネントプロパティの型付け](/guide/typescript/options-api.html#typing-component-props)
すみません。漏れておりました。ありがとうございます！

2022-03-29 08:20 UTC, kakikubo commented on src/api/utility-types.md
> +  // helloが宣言されていないプロパティでも使えるようになります
ああーすみません 😓

2022-03-29 08:20 UTC, kakikubo commented on src/api/utility-types.md
> +        // より具体的な型を`Object`に提供します
漏れてばかり 😓

2022-03-29 08:21 UTC, kakikubo commented
@jay-es suggestありがとうございました。改めてレビューをお願いしてもよろしいでしょうか 🙏

2022-03-29 11:42 UTC, jay-es approved these changes
LGTM!

2022-03-29 11:42 UTC, merged