Translate Tutorial > Lifecycle and Template Refs
vuejs-translations/docs-ja pull request #417
Opened 2022-03-27 20:51 UTC by Robjam

resolves #99
お手すきにレビューおねがいいたします。

2022-03-28 12:13 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-03-28 12:13 UTC, jay-es commented on src/tutorial/src/step-9/description.md
> +ref にアクセスするには、一致する名前を定義して<span class="html">公開する</span>必要があります：
表示を切り替えたときに崩れないように修正しました
```suggestion
ref にアクセスするには、一致する名前を定義<span class="html">して公開</span>する必要があります：
```

2022-03-28 12:13 UTC, jay-es commented on src/tutorial/src/step-9/description.md
> +要素が `this.$refs` は `this.$refs.p` として公開されますが、コンポーネントが**マウントさした後**でないとにアクセスできません。
typo
```suggestion
要素が `this.$refs` は `this.$refs.p` として公開されますが、コンポーネントが**マウントされた後**でないとにアクセスできません。
```

2022-03-28 12:13 UTC, jay-es commented on src/tutorial/src/step-9/description.md
> +これは**ライフサイクルフック**とよばれます。コンポーネントライフサイクルは特定の時にコールバックが登録できます。他にも <span class="options-api">`created` と `updated`</span><span class="composition-api">`onUpdated` と `onUnmounted`</span> があります。詳しくは<a targe
`to be called` に対応する部分を追加しました
```suggestion
これは**ライフサイクルフック**とよばれます。コンポーネントライフサイクルの特定の時に呼び出されるコールバックが登録できます。他にも <span class="options-api">`created` と `updated`</span><span class="composition-api">`onUpdated` と `onUnmounted`</span> があります。詳しくは<a target="_blank" href="/guide/essentials/lifecycle.html#lifecycle-diagram">ライフサイクルダイアグラム</a>を参照してください。
```

2022-03-30 00:30 UTC, Robjam commented
レビューいただきありがとうございます。
ご指摘いただいた補足反映しまいた。
ref: [405e0c6](https://github.com/vuejs-translations/docs-ja/pull/417/commits/405e0c6f0070da66e53b7bd6f29183770766a218)

2022-03-30 11:00 UTC, jay-es approved these changes
修正ありがとうございます！:pray:
自分はこれでOKです！

2022-04-02 11:46 UTC, kazupon approved these changes
翻訳ありがとうございました！
大丈夫そうです！

2022-04-02 11:46 UTC, merged