「Guide > Essentials > Form Input Bindings」の翻訳
vuejs-translations/docs-ja pull request #426
Opened 2022-03-30 08:56 UTC by kohbis

resolve #15

2022-03-30 11:18 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-03-30 11:18 UTC, jay-es commented on src/guide/essentials/forms.md
> +なお、`<textarea>` 内の補間は機能しません。代わりに `v-model` を使用してください。
`note that` の訳を修正しました
```suggestion
`<textarea>` 内の補間は機能しないことに注意してください。代わりに `v-model` を使用してください。
```

2022-03-30 11:18 UTC, jay-es commented on src/guide/essentials/forms.md
> +複数のセレクト (配列へのバインド):
```suggestion
複数選択（配列へのバインド）:
```

2022-03-30 11:18 UTC, jay-es commented on src/guide/essentials/forms.md
> +単一のセレクト:
275行目は「複数選択」と訳した方がよさそうなので、それに合わせて修正
```suggestion
単一選択:
```

2022-03-30 11:18 UTC, jay-es commented on src/guide/essentials/forms.md
> +ユーザー入力を自動で数値として型変換したい場合、 `v-model` で管理している入力に `number` 就職を追加することができます。
typo 修正
```suggestion
ユーザー入力を自動で数値として型変換したい場合、 `v-model` で管理している入力に `number` 修飾子を追加することができます。
```

2022-03-30 11:18 UTC, jay-es commented on src/guide/essentials/forms.md
> +> Vueのコンポーネントにまだ慣れていない場合、とりあえずはこのセクションをスキップすることができます。
```suggestion
> Vue のコンポーネントにまだ慣れていない場合、とりあえずはこのセクションをスキップすることができます。
```

2022-04-02 11:58 UTC, kazupon requested changes
翻訳ありがとうございます。
レビュー 👀 遅くなってすいません。 🙇 
コメント 💬 いくつかしたので対応お願いします。

2022-04-02 11:58 UTC, kazupon commented on src/guide/essentials/forms.md
> +さらに、 `v-model` は様々な種類の入力や `<textarea>` 、 `<select>` 要素の入力で使用することができます。使用する要素に応じて、異なる DOM プロパティとイベントのペアに自動で展開します。
`:` の対応お願いします。

```suggestion
さらに、 `v-model` は様々な種類の入力や `<textarea>` 、 `<select>` 要素の入力で使用することができます。使用する要素に応じて、異なる DOM プロパティとイベントのペアに自動で展開します:
```

2022-04-02 11:58 UTC, kazupon commented on src/guide/essentials/forms.md
> +<textarea v-model="messageテキストaceholder="add multiple lines"></textarea>
コード部分は、コメントのみで対応する方針なので、ここでは以下のように翻訳はする必要はないです。
```suggestion
<textarea v-model="message" placeholder="add multiple lines"></textarea>
```

2022-04-02 11:58 UTC, kazupon commented on src/guide/essentials/forms.md
> +複数のチェックボックスを同じ配列もしくは [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) の値にバインドすることもできます。
`:` は句点はなく、原文のままでお願いします！ 🙏 
```suggestion
複数のチェックボックスを同じ配列もしくは [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) の値にバインドすることもできます:
```

2022-04-02 11:58 UTC, kazupon commented on src/guide/essentials/forms.md
>  <!-- `picked` is a string "a" when checked -->
ここのコードのコメント部分は翻訳お願いします！ 🙏

2022-04-02 11:58 UTC, kazupon commented on src/guide/essentials/forms.md
>  <!-- `picked` is a string "a" when checked -->
他のコードのコメント部分も同じく。

2022-04-03 03:04 UTC, kohbis commented on src/guide/essentials/forms.md
>  <!-- `picked` is a string "a" when checked -->
↓にて修正
https://github.com/vuejs-translations/docs-ja/pull/426/files/e67cb739d99ca50c9890d25300b441d0b0c05a9e..f1a4a76d116679057d8d60a37750210729c6fb62

2022-04-03 12:24 UTC, kazupon approved these changes

2022-04-03 12:24 UTC, merged