「Guide > Extra Topics > Composition API FAQ」の翻訳
vuejs-translations/docs-ja pull request #427
Opened 2022-03-31 03:52 UTC by hiro-lapis

resolve #49

2022-03-31 04:03 UTC, hiro-lapis commented on src/guide/extras/composition-api-faq.md
> +多くのユーザーはデフォルトの Options API で構成されたコードを書くことを好みます: なにごとにもあるべき方法というものが決まっているものです。しかしながら、 Options API では単一ファイルコンポーネントのロジックが成長し、ある一定以上の複雑さを超えた時点で深刻な制限を受けることになります。この制限は複数の**論理的関心**を扱うコンポーネントで特に顕著で、私たちは実際に稼働
他ページでは`論理的な関心`と訳されていましたが、
このページでは何度も出てくることを考慮して簡潔な表現にしました。

2022-03-31 04:04 UTC, hiro-lapis commented on src/guide/extras/composition-api-faq.md
> +ここ数年、多くのフロントエンドの開発者たちが [TypeScript](https://www.typescriptlang.org/) を取り入れ、より堅牢なコードを書き、より安心して変更を加えられるようにしていて、また IDE のサポートと共にすばらしい開発体験を提供してくれています。しかしながら、2013 年に Options API が生まれた当時、型推論の考慮がない状態でデザインされま
`absurdly complex type gymnastics`の訳に悩みまして、、、この訳し方でどうでしょうか？

2022-03-31 04:07 UTC, hiro-lapis commented on src/guide/extras/composition-api-faq.md
> +Composition API で書かれたコードと `<script setup>` は　Options API より効率的でバンドルサイズの縮小化に親和性があります。テンプレート内の `<script setup>` コンポーネントは `<script setup>` と同じスコープ内にインラインの関数としてコンパイルされます。`this` からのプロパティアクセスとは異なり、コンパイルされた
`instance proxy`は直訳`インスタンスプロキシ`でもいいかと思ったのですが、
あまり出てこない言葉ということもあり、意味が通りやすい表現にしてみました。

2022-03-31 11:46 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-03-31 11:46 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +- [Reactivity API](/api/reactivity-core.html) 、例: `ref()` と `reactive()` で、リアクティブな状態を作り、状態を監視します。
他にも関数はあるので、`and` は「や」の方が適切かと思いました。
また、後半は意味が変わってしまっているので修正お願いします
（computed state の訳が難しい...）
```suggestion
- [Reactivity API](/api/reactivity-core.html) 、例: `ref()` や `reactive()` で、リアクティブな状態、算出状態、ウォッチャーを直接作成できます。
```

2022-03-31 11:46 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +- [Lifecycle Hooks](/api/composition-api-lifecycle.html)、 例: `onMounted()` と `onUnmounted()` で、コンポーネントのライフサイクルにフックを設定します。
```suggestion
- [Lifecycle Hooks](/api/composition-api-lifecycle.html)、 例: `onMounted()` や `onUnmounted()` で、コンポーネントのライフサイクルにプログラム的なフックを設定します。
```

2022-03-31 11:46 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +- [Dependency Injection](/api/composition-api-dependency-injection.html) 、すなわち `provide()` と `inject()` のような、 Reactivity API を使用するために用いられる Vue の依存性の注入のことです。
意味が変わっているので修正お願いします
```suggestion
- [Dependency Injection](/api/composition-api-dependency-injection.html) 、すなわち `provide()` と `inject()` によって、Reactivity API を使用しながら Vue の依存性注入システムを利用できます。
```

2022-03-31 11:46 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +コンポジション関数ベースでスタイリングされた API にも関わらず、 **Composition API は関数型プログラミングではありません**。 関数型言語プログラミングはイミュータブルを重視するのに対して、 Composition API は Vue のミュータブルできめ細かなリアクティブさをベースにしています。
```suggestion
関数合成ベースの API スタイルにも関わらず、 **Composition API は関数型プログラミングではありません**。 関数型プログラミングはイミュータブルを重視するのに対して、 Composition API は Vue のミュータブルできめ細かなリアクティブさをベースにしています。
```

2022-03-31 11:46 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +Composition API で書かれたコードと `<script setup>` は　Options API より効率的でバンドルサイズの縮小化に親和性があります。テンプレート内の `<script setup>` コンポーネントは `<script setup>` と同じスコープ内にインラインの関数としてコンパイルされます。`this` からのプロパティアクセスとは異なり、コンパイルされた
文の内容が変わってしまうので `インスタンスプロキシ` に変更お願いします:pray:

2022-03-31 11:46 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +- `useMemo` を使用するときにコストの高い計算が必要となり、再び手動で正しい依存関係の配列を渡す必要があります。
```suggestion
- コストの高い計算には `useMemo` の使用が必要となり、再び手動で正しい依存関係の配列を渡す必要があります。
```

2022-03-31 11:46 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +これと比較して、 Vue Composition API :
```suggestion
これと比較して、 Vue Composition API は:
```

2022-03-31 13:05 UTC, hiro-lapis commented on src/guide/extras/composition-api-faq.md
> +- [Reactivity API](/api/reactivity-core.html) 、例: `ref()` と `reactive()` で、リアクティブな状態を作り、状態を監視します。
指摘の通り文意が変わってしまってましたね。。。
提案してもらった訳に修正しました！

2022-04-01 13:05 UTC, jay-es requested changes
1箇所修正お願いします:pray:

2022-04-01 13:05 UTC, jay-es commented on src/guide/extras/composition-api-faq.md
> +- [Dependency Injection](/api/composition-api-dependency-injection.html) 、すなわち `provide()` と `inject()` によって、 Reactivity API を使用しながらる Vue の依存性注入システムを利用できます。
「る」を削除
```suggestion
- [Dependency Injection](/api/composition-api-dependency-injection.html) 、すなわち `provide()` と `inject()` によって、 Reactivity API を使用しながら Vue の依存性注入システムを利用できます。
```

2022-04-02 05:27 UTC, hiro-lapis commented
@jay-es 
ありがとうございます!都合がよろしい時に再レビューいただいてもいいでしょうか。

2022-04-02 12:17 UTC, kazupon requested changes
翻訳ありがとうございます。
レビュー 👀 コメント 💬 しました。
確認お願いします！

2022-04-02 12:17 UTC, kazupon commented on src/guide/extras/composition-api-faq.md
> +## なぜComposition APIなのか?
細かいですが、読みさすさを考慮して、以下のようにスペース入れて頂きたいです。 🙏 
```suggestion
## なぜ Composition API なのか?
```

2022-04-02 12:17 UTC, kazupon commented on src/guide/extras/composition-api-faq.md
> +例として Vue CLI の GUI で使われるフォルダーエクスプローラーコンポーネントをとりあげます: このコンポーネントは以下のような論理的関心を担っています。
細かいですが、`:` の体裁、原文と同じでお願いします。

```suggestion
例として Vue CLI の GUI で使われるフォルダーエクスプローラーコンポーネントをとりあげます: このコンポーネントは以下のような論理的関心を担っています:
```

2022-04-02 12:17 UTC, kazupon commented on src/guide/extras/composition-api-faq.md
> +ここ数年、多くのフロントエンドの開発者たちが [TypeScript](https://www.typescriptlang.org/) を取り入れ、より堅牢なコードを書き、より安心して変更を加えられるようにしていて、また IDE のサポートと共にすばらしい開発体験を提供してくれています。しかしながら、2013 年に Options API が生まれた当時、型推論の考慮がない状態でデザインされま
そうですね。
原文では、伝えたいこととして、とても複雑なことをしていることを言葉にしたのが、`absurdly complex type gymnastics` になっていると思うんですが、原文どおり `馬鹿馬鹿しいほどに複雑な型の運動` と訳すと、ちょっと言い回しが読み手にとってきついので、意訳気味に `とてもありえない複雑な型定義` とするとどうでしょう？

@jay-es 
何かコメントありましたら、どうぞ！ 🙏

2022-04-02 15:05 UTC, jay-es approved these changes

2022-04-03 01:49 UTC, hiro-lapis commented
@kazupon 
ありがとうございます！修正ができましたので再レビューおねがいしてもいいでしょうか？

2022-04-03 02:20 UTC, kazupon commented
@hiro-lapis 
すいません。修正したcommitがpushされていないようなのですが、こちらお願いできますか？
(このコメント時に自分が見逃しているだけかもしれませんが...)

2022-04-03 10:50 UTC, hiro-lapis commented
@kazupon 
すみません、push漏れてました🙇‍♂️
改めて、確認いただいてもいいでしょうか。よろしくおねがいします。

2022-04-03 12:25 UTC, kazupon approved these changes

2022-04-03 12:28 UTC, merged