Guide essentials class and style bindings
vuejs-translations/docs-ja pull request #428
Opened 2022-04-01 23:07 UTC by tanquar

resolve #11

2022-04-02 11:25 UTC, tanquar commented
翻訳しました。よろしくお願いします。

2022-04-02 12:23 UTC, kazupon requested changes
翻訳ありがとうございます。
レビュー 👀 コメント 💬 しました。
確認お願いします。

2022-04-02 12:23 UTC, kazupon commented on src/guide/essentials/class-and-style.md
> +`:class` (`v-bind:class` の省略記法) では、オブジェクトを渡して CSS クラスを動的に切り替えることができます。
`:` は原文と同じままでお願いします。

```suggestion
`:class` (`v-bind:class` の省略記法) では、オブジェクトを渡して CSS クラスを動的に切り替えることができます:
```

2022-04-02 12:23 UTC, kazupon commented on src/guide/essentials/class-and-style.md
> +### マルチバリュー
以下のように訳すと自然が気がします。
```suggestion
### 複数の値
```

2022-04-02 15:17 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-04-02 15:17 UTC, jay-es commented on src/guide/essentials/class-and-style.md
> +### 配列とのバインディング
```suggestion
### 配列へのバインディング
```

2022-04-02 15:17 UTC, jay-es commented on src/guide/essentials/class-and-style.md
> +次のクラスバインディングでも同様です:
クラスバインディング全般に関する説明なので、「次の」はない方がよいと思いました
```suggestion
クラスバインディングでも同様です:
```

2022-04-02 22:01 UTC, tanquar commented
ありがとうございます！
修正しました。よろしくお願いします。

2022-04-03 12:29 UTC, kazupon approved these changes

2022-04-03 12:29 UTC, kazupon commented
ありがとうございます。
自分が指摘してところは大丈夫そうです。

2022-04-04 10:57 UTC, jay-es approved these changes
ありがとうございます:pray:

2022-04-04 10:57 UTC, merged