「Style Guide > Priority A Rules: Essential」の翻訳
vuejs-translations/docs-ja pull request #429
Opened 2022-04-02 09:30 UTC by nabeken5

resolve #102

2022-04-02 15:01 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-04-02 22:35 UTC, nabeken5 commented on src/style-guide/rules-essential.md
> +<!-- in-DOMテンプレート -->
修正4

2022-04-03 12:51 UTC, kazupon reviewed
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しておきました。
確認お願いします。

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +## 詳細なプロップ定義を使用する
ここでの `prop` の訳は以下のように `プロパティ` でお願いします！
(`prop` 、`props` の訳はドキュメントの文脈によって訳すか原文のままか、翻訳するときは注意する必要があります。)

```suggestion
## 詳細なプロパティ定義を使用する
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +詳細な[プロップ定義](/guide/components/props.html#prop-validation)には、2 つの利点があります。
ここも同じく、以下のように `プロパティ` で。
```suggestion
詳細な[プロパティ定義](/guide/components/props.html#prop-validation)には、2 つの利点があります。
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +- 開発では、コンポーネントが不適切な形式の prop を提供された場合に Vue が警告を発し、潜在的なエラー源を捕らえるのに役立ちます。
ここは、 以下のように、`props` そのままですね。
```suggestion
- 開発では、コンポーネントが不適切な形式の props を提供された場合に Vue が警告を発し、潜在的なエラー源を捕らえるのに役立ちます。
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +例えば、TODO のリストがあるとします。
`:` は原文のままでお願いします。
```suggestion
例えば、TODO のリストがあるとします:
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +        text: 'v-forの使い方を学ぶ'
コードのコメント部分は翻訳する必要があるのですが、コード部分のテキストは、原文のままでお願いします。 🙏 
```suggestion
        text: 'Learn to use v-for'
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +        text: 'キーの使い方を覚える'
ここも同じく。
```suggestion
        text: 'Learn to use key'
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +私たちの経験では、常に一意なキーを追加して、あなたやチームがこのようなエッジケースについて心配する必要がないようにする方がいいです。そして、まれにパフォーマンスが重要なシナリオで、オブジェクトの不変性が必要でない場合は、意識的に例外を作ることができます。
細かいですが、口語ではなく文書体で、お願いします。

```suggestion
私たちの経験では、常に一意なキーを追加して、あなたやチームがこのようなエッジケースについて心配する必要がないようにする方がよいです。そして、まれにパフォーマンスが重要なシナリオで、オブジェクトの不変性が必要でない場合は、意識的に例外を作ることができます。
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +これが魅力的なのは、よくある 2 つのケースです。
`:` は原文のままでお願いします！
```suggestion
これが魅力的なのは、よくある 2 つのケースです:
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +これは、次のように、算出プロパティに対して反復処理を行うことで解決できます。
```suggestion
これは、次のように、算出プロパティに対して反復処理を行うことで解決できます:
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +## mixinでプライベート関数の公開を避ける
細かいですが読みやすさを考慮してスペースをお願いします！
```suggestion
## mixin でプライベート関数の公開を避ける
```

2022-04-03 12:51 UTC, kazupon commented on src/style-guide/rules-essential.md
> +プレフィックス `$` については、Vue のエコシステム内での用途は、ユーザーに公開される特別なインスタンスプロパティです。したがって、_private_プロパティに使用することは適切ではありません。
private も訳しておきましょう。

```suggestion
プレフィックス `$` については、Vue のエコシステム内での用途は、ユーザーに公開される特別なインスタンスプロパティです。したがって、_プライベート_プロパティに使用することは適切ではありません。
```

2022-04-04 11:02 UTC, jay-es approved these changes
自分の指摘箇所は修正確認できました:pray:
kazupon さんご指摘分の修正をお願いします

2022-04-06 00:39 UTC, nabeken5 commented
二人とも、ありがとうございます！
修正しました！

2022-04-08 02:44 UTC, nabeken5 commented
サイドバー側のタイトルも変更しました。

2022-04-10 13:38 UTC, kazupon approved these changes
すいません、遅くなりました。
指摘内容の対応ありがとうございました。
よさそうです！

2022-04-10 13:38 UTC, merged