Translate accessibility.md
vuejs-translations/docs-ja pull request #430
Opened 2022-04-02 14:32 UTC by takmatsukawa

resolve #43

2022-04-03 13:12 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
確認お願いいたします。

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <button type="submit">確定</button>
ここのコードのテキストは以下のように訳さない形にしておいてください。:pray:
```suggestion
  <button type="submit">Submit</button>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +<label for="name">名前</label>
```suggestion
<label for="name">Name</label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  名前:
```suggestion
  Name:
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +<label for="name">名前</label>
```suggestion
<label for="name">Name</label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <h1 id="billing">支払い</h1>
```suggestion
  <h1 id="billing">Billing</h1>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +    <label for="name">名前:</label>
```suggestion
    <label for="name">Name:</label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <button type="submit">確定</button>
```suggestion
  <button type="submit">Submit</button>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <h1 id="billing">支払い</h1>
```suggestion
  <h1 id="billing">Billing</h1>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +    <label for="name">氏名:</label>
```suggestion
    <label for="name">Full Name:</label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +    <p id="nameDescription">姓と名を入力してください。</p>
```suggestion
    <p id="nameDescription">Please provide first and last name.</p>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <button type="submit">確定</button>
```suggestion
  <button type="submit">Submit</button>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <button type="submit">確定</button>
```suggestion
  <button type="submit">Submit</button>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <legend>aria-labelledby を使う</legend>
```suggestion
  <legend>Using aria-labelledby</legend>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <label id="date-label" for="date">現在の日時:</label>
```suggestion
  <label id="date-label" for="date">Current Date:</label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <p id="date-instructions">YYYY/MM/DD</p>
```suggestion
  <p id="date-instructions">MM/DD/YYYY</p>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <label id="dob" for="dob">誕生日:</label>
```suggestion
  <label id="dob" for="dob">Date of Birth:</label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <legend>aria-describedby を使う</legend>
```suggestion
  <legend>Using aria-describedby</legend>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <p id="dob-instructions">YYYY/MM/DD</p>
```suggestion
  <p id="dob-instructions">MM/DD/YYYY</p>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <label for="search" class="hidden-visually">検索: </label>
```suggestion
  <label for="search" class="hidden-visually">Search: </label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <button type="submit">検索</button>
```suggestion
  <button type="submit">Search</button>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +<p>これはスクリーンリーダーから非表示ではありません。</p>
```suggestion
<p>This is not hidden from screen readers.</p>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +<p aria-hidden="true">これはスクリーンリーダーから非表示です。</p>
```suggestion
<p aria-hidden="true">This is hidden from screen readers.</p>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <button type="button">キャンセル</button>
```suggestion
  <button type="button">Cancel</button>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <button type="submit">確定</button>
```suggestion
  <button type="submit">Submit</button>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <input type="button" value="キャンセル" />
```suggestion
  <input type="button" value="Cancel" />
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <input type="submit" value="確定" />
```suggestion
  <input type="submit" value="Submit" />
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +    <label for="search" class="hidden-visually">検索: </label>
```suggestion
    <label for="search" class="hidden-visually">Search: </label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +      alt="検索"
```suggestion
      alt="Search"
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +  <label for="searchIcon" class="hidden-visually">検索: </label>
```suggestion
  <label for="searchIcon" class="hidden-visually">Search: </label>
```

2022-04-03 13:12 UTC, kazupon commented on src/guide/best-practices/accessibility.md
> +    <span class="hidden-visually">検索</span>
```suggestion
    <span class="hidden-visually">Search</span>
```

2022-04-03 14:11 UTC, takmatsukawa commented
レビューありがとうございます！修正しました。

2022-04-04 11:51 UTC, jay-es requested changes
レビューしました。
細かいですが何点か修正お願いします:pray:

2022-04-04 11:51 UTC, jay-es commented on src/guide/best-practices/accessibility.md
> +[ランドマーク](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/landmark_role)は、アプリケーション内のセクションへのプログラムによるアクセスを提供します。アシスティブ・テクノロジーに依存するユーザーは、アプリケーションの各セクションに移動し、コンテンツをスキップすることができます。これを実
カタカナだけだと分かりにくそうなので、最初の一回は漢字も併記しておきましょう
```suggestion
[ランドマーク](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/landmark_role)は、アプリケーション内のセクションへのプログラムによるアクセスを提供します。アシスティブ・テクノロジー（支援技術）に依存するユーザーは、アプリケーションの各セクションに移動し、コンテンツをスキップすることができます。これを実現するために、[ARIA ロール](https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/Roles)を使用できます。
```

2022-04-04 11:51 UTC, jay-es commented on src/guide/best-practices/accessibility.md
> +## セマンティックフォーム
細かいですが、「な」を入れたほうがよさそうに感じました
```suggestion
## セマンティックなフォーム
```

2022-04-04 11:51 UTC, jay-es commented on src/guide/best-practices/accessibility.md
> +Chrome DevTools でこの要素を検査し、Elements タブ内の Accessibility タブを開くと、入力欄がどのようにラベルから名付けられているか確認できます:
細かいですが原文が `DevTools` ではなく `developer tools` なので合わせた方がベターかなと思いました
```suggestion
Chrome デベロッパー ツールでこの要素を検査し、Elements タブ内の Accessibility タブを開くと、入力欄がどのようにラベルから名付けられているか確認できます:
```

2022-04-04 11:51 UTC, jay-es commented on src/guide/best-practices/accessibility.md
> +![Chrome DevTools が、入力欄がラベルから得たアクセシブルな名前を表示している](./images/AccessibleLabelChromeDevTools.png)
```suggestion
![Chrome デベロッパー ツールが、入力欄がラベルから得たアクセシブルな名前を表示している](./images/AccessibleLabelChromeDevTools.png)
```

2022-04-04 11:51 UTC, jay-es commented on src/guide/best-practices/accessibility.md
> +![Chrome DevTools が、入力欄が aria-label から得たアクセシブルな名前を表示している](./images/AccessibleARIAlabelDevTools.png)
```suggestion
![Chrome デベロッパー ツールが、入力欄が aria-label から得たアクセシブルな名前を表示している](./images/AccessibleARIAlabelDevTools.png)
```

2022-04-04 11:51 UTC, jay-es commented on src/guide/best-practices/accessibility.md
> +![Chrome DevTools が、入力欄が aria-labelledby から得たアクセシブルな名前を表示している](./images/AccessibleARIAlabelledbyDevTools.png)
```suggestion
![Chrome デベロッパー ツールが、入力欄が aria-labelledby から得たアクセシブルな名前を表示している](./images/AccessibleARIAlabelledbyDevTools.png)
```

2022-04-04 11:51 UTC, jay-es commented on src/guide/best-practices/accessibility.md
> +![Chrome DevTools が、入力欄に設定された aria-labelledby のアクセシブルな名前と、aria-describedby の説明文を表示している](./images/AccessibleARIAdescribedby.png)
```suggestion
![Chrome デベロッパー ツールが、入力欄に設定された aria-labelledby のアクセシブルな名前と、aria-describedby の説明文を表示している](./images/AccessibleARIAdescribedby.png)
```

2022-04-04 12:23 UTC, takmatsukawa commented
対応しました。

2022-04-05 10:56 UTC, jay-es approved these changes
ありがとうございます

2022-04-10 13:38 UTC, kazupon approved these changes

2022-04-10 13:39 UTC, kazupon commented
すいません、遅くなりました。
ありがとうございました！

2022-04-10 13:39 UTC, merged