docs: translate TypeScript options api
vuejs-translations/docs-ja pull request #432
Opened 2022-04-03 11:56 UTC by bobstrange

resolve #47

2022-04-03 11:58 UTC, bobstrange commented on src/guide/typescript/options-api.md
> +## グローバルなプロパティの拡張
augmentation の翻訳は
[Vue 2 の翻訳](https://jp.vuejs.org/v2/guide/typescript.html#%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%A7%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E5%9E%8B%E6%8B%A1%E5%BC%B5) を参照しました

2022-04-03 13:18 UTC, kazupon approved these changes
翻訳ありがとうございます。
レビュー 👀 コメント 💬 しました。
よさそうです。

2022-04-04 11:17 UTC, jay-es requested changes
レビューしました。
細かいですが1点だけ修正をお願いします:pray:

2022-04-04 11:17 UTC, jay-es commented on src/guide/typescript/options-api.md
> +Options API における型推論は、コンポーネントを `defineComponent()` でラップする必要があります。そうすることで、Vue は `props` オプションを元に、`required: true` や、 `default` などの追加のオプションを考慮した上で、props の型を推論することができるようになります。
`for props` の訳を追加しました
```suggestion
Options API における props の型推論は、コンポーネントを `defineComponent()` でラップする必要があります。そうすることで、Vue は `props` オプションを元に、`required: true` や、 `default` などの追加のオプションを考慮した上で、props の型を推論することができるようになります。
```

2022-04-04 11:49 UTC, bobstrange commented
@jay-es 

ありがとうございます、props 抜けていましたね :sweat: 
suggest 頂いた形でそのまま取り込みました。[`3d48882` (#432)](https://github.com/vuejs-translations/docs-ja/pull/432/commits/3d4888215c1d72e02ee52d31a923185eca6fb7f5)
よろしくお願いします。

2022-04-04 11:52 UTC, jay-es approved these changes
修正ありがとうございます！:pray:

2022-04-04 11:52 UTC, merged