「Guide > Components In-Depth > Fallthrough Attributes」の翻訳
vuejs-translations/docs-ja pull request #435
Opened 2022-04-04 15:01 UTC by hiro-lapis

resolve #23 

お手すきの際にレビューおねがいします🙇‍♂️

2022-04-04 15:13 UTC, hiro-lapis commented on src/guide/components/attrs.md
> +ここで `attrs` オブジェクトは常に最新のフォールスルー属性を反映していますが、リアクティブではないことに注意してください（パフォーマンス上の理由です）。ウォッチャーを使ってその変更を監視することはできません。リアクティビティが必要であれば、 prop を使ってください。または、 `onUpdated()` を使用して、更新されるたびに最新の `attrs` による副作用を実行することもで
この文節最後の一文の翻訳も少し悩みました。

原文の表現を残しつつ、最新の `attrs` を使うことができるよ！という文意を持たせたつもりですが、
少しわかわりにくいかな？と思っているのですが、どうでしょうか？

2022-04-05 03:56 UTC, hiro-lapis commented on src/guide/components/attrs.md
> +`<script setup>` を使用するなら、このオプションは別の通常の `<script>` ブロックを使って宣言する必要があります:
現時点で表示してないですが、翻訳しました

2022-04-05 11:18 UTC, jay-es requested changes
レビューしました。
1点だけ修正をお願いします:pray:

2022-04-05 11:18 UTC, jay-es commented on src/guide/components/attrs.md
> +コンポーネントに自動的な属性の継承をさせたくない場合は、コンポーネントのオプションで `inheritAttrs: false` を設定することができます。
not の太字を反映
```suggestion
コンポーネントに自動的な属性の継承をさせたく**ない**場合は、コンポーネントのオプションで `inheritAttrs: false` を設定することができます。
```

2022-04-05 11:18 UTC, jay-es commented on src/guide/components/attrs.md
> +`<script setup>` を使用するなら、このオプションは別の通常の `<script>` ブロックを使って宣言する必要があります:
画面左上のトグルを "Composition" にすると表示されます

2022-04-05 13:11 UTC, hiro-lapis commented on src/guide/components/attrs.md
> +`<script setup>` を使用するなら、このオプションは別の通常の `<script>` ブロックを使って宣言する必要があります:
ありがとうございます、確認しました。

2022-04-05 13:13 UTC, hiro-lapis commented
@jay-es 
ありがとうございます、
suggestionを受け入れる形で修正させてもらいました。

手隙の際にチェックしていただけますか🙇‍♂️

2022-04-06 13:55 UTC, jay-es approved these changes
ありがとうございます。
自分はOKです！ 🙆‍♂️

2022-04-07 10:20 UTC, hiro-lapis commented
@jay-es 
ありがとうございます!

@kazupon 
手隙の際にレビューお願いします🙇‍♂️

2022-04-10 13:46 UTC, kazupon approved these changes
レビュー 👀 遅くなりました 🙇 
いいですね！

2022-04-10 13:46 UTC, merged