Translate "About > Meet the Team"
vuejs-translations/docs-ja pull request #436
Opened 2022-04-05 17:38 UTC by gyvm

resolve #110

2022-04-06 14:24 UTC, jay-es requested changes
レビューしました。
修正お願いします:pray:

2022-04-06 14:24 UTC, jay-es commented on src/about/team/TeamPage.vue
> +        彼らは Vue エコシステムに有意な貢献をしており、プロジェクトとユーザの成功のために長い期間献身しています。</template
ユーザ→ユーザーに変更
```suggestion
        彼らは Vue エコシステムに有意な貢献をしており、プロジェクトとユーザーの成功のために長い期間献身しています。</template
```

2022-04-06 14:24 UTC, jay-es commented on src/about/team/TeamPage.vue
> +        >Vue とそのエコシステムの開発は国際チームによって主導されています。一部のメンバーを以下に記載します。</template
元の行と対応するよう、16-18 行目になるよう調整し、19-20 に追加されている空行は削除お願いします
（下のセクションも同様）

2022-04-06 20:19 UTC, gyvm commented on src/about/team/TeamPage.vue
> +        >Vue とそのエコシステムの開発は国際チームによって主導されています。一部のメンバーを以下に記載します。</template
@jay-es 
修正しましたので、ご確認をお願いいたします。[ad2f565](https://github.com/vuejs-translations/docs-ja/pull/436/commits/ad2f5651ccbfb1e60c1f71cacfe89f68b1167b22)

2022-04-10 13:47 UTC, kazupon approved these changes
レビュー 👀 しました。
OKです！

2022-04-10 13:47 UTC, merged