translate component-basics.md
vuejs-translations/docs-ja pull request #444
Opened 2022-04-11 14:27 UTC by hiro-lapis

resolve #19 

度々レビューしてくださりありがとうございます。
都合のつきますときにレビューよろしくおねがいします🙇‍♂️

2022-04-11 14:35 UTC, hiro-lapis commented on src/guide/essentials/component-basics.md
> +SFC では、ネイティブの HTML 要素と区別するために、子コンポーネントに `パスカルケース` のタグ名を使用することが推奨されます。ネイティブの HTML のタグ名は大文字小文字を区別しませんが、 Vue の SFC はコンパイルされたフォーマットなので、大文字小文字を区別するタグ名を使うことができます。また、タグを閉じるために `/>` を使用することができます。
バッククォートで囲った言葉を訳している箇所が他になかったのですが、
パスカルケースという言葉を訳している箇所自体は他にもあったので翻訳しています。

2022-04-11 14:38 UTC, hiro-lapis commented on src/guide/essentials/component-basics.md
> +これまでのコードサンプルでは、コンポーネントに自己クローズ (self-closing) タグを使用していました:
どう訳すか迷ったのですが、
[reactのドキュメント](https://ja.reactjs.org/docs/jsx-in-depth.html)を参考に、自己クローズタグと訳しました。

2022-04-11 14:44 UTC, hiro-lapis commented on src/guide/essentials/component-basics.md
> +DOM テンプレート解析の注意点については、以上で終わりです。そして実は、 Vue の _Essentials_（エッセンス集）はこれで終わりです。おめでとうございます！まだ学ぶことはありますが、ひとまずは休みをいれて、あなた自身が Vue で遊び、何か楽しいものを作ってみることをおすすめします。もしくは、[サンプル集](/examples/)をまだ見ていないようであれば、チェックしてください。
_Essentials_　はユーモア表現なので訳さないままの方がいいと思ったものの、
日本語の注釈もあった方がいいと思い()付けで説明をつけています。

2022-04-15 12:20 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-04-15 12:20 UTC, jay-es commented on src/guide/essentials/component-basics.md
> +`<script setup>` を使用していない時は `emits` オプションを使用してイベント発行を宣言することができます。 `emit` 関数には、セットアップコンテキスト (第 2 引数として `setup()` に渡されます) のプロパティとしてアクセスすることができます:
```suggestion
`<script setup>` を使用していない時は `emits` オプションを使用してイベント発行を宣言することができます。セットアップコンテキスト (`setup()` に第 2 引数として渡されます) のプロパティとして `emit` 関数にアクセスすることができます:
```

2022-04-15 12:20 UTC, jay-es commented on src/guide/essentials/component-basics.md
> +// JavaScript 内のキャメルケース
```suggestion
// JavaScript 内ではキャメルケース
```

2022-04-15 12:20 UTC, jay-es commented on src/guide/essentials/component-basics.md
> +<!-- HTML 内のケバブケース -->
```suggestion
<!-- HTML 内ではケバブケース -->
```

2022-04-15 12:20 UTC, jay-es commented on src/guide/essentials/component-basics.md
> +これは、Vue のテンプレートパーサーが `/>` を、型に関係なく任意のタグを終了する指示として尊重するためです。
「型」だと紛らわしいので「種類」とするのが良いかなと思いました
```suggestion
これは、Vue のテンプレートパーサーが `/>` を、タグの種類に関係なく任意のタグを終了する指示として尊重するためです。
```

2022-04-15 15:51 UTC, hiro-lapis commented
@jay-es

レビューありがとうございます！

指摘もらった箇所に加え、以下気づいた点を修正・調整しました。
再レビューしてもらえますか🙇‍♂️
・句読点後と英字の間をスペースをなしに統一
・不要と思われる句読点は削除
・脱字修正
・改めて読み直し、違和感のある表現を調整

2022-04-18 12:18 UTC, jay-es approved these changes
ありがとうございます！
自分はOKです 🙆‍♂️

2022-04-19 16:03 UTC, kazupon requested changes
いつも翻訳ありがとうございます。
すいません、レビュー 👀 遅くなりました。
コメントしたので確認お願いします！

2022-04-19 16:03 UTC, kazupon commented on src/guide/essentials/component-basics.md
> +`<script setup>` を使用していない時は `emits` オプションを使用してイベント発行を宣言することができます。セットアップコンテキスト (`setup()` に第 2 引数として渡されます) のプロパティとして `emit` 関数にアクセスすることができます:
ここの `setup context` の `setup` は訳さずに、`setup コンテキスト` として方がコードの `setup` と目視した瞬間理解しやすいと思いので、そのままでいいですね。
```suggestion
`<script setup>` を使用していない時は `emits` オプションを使用してイベント発行を宣言することができます。setup コンテキスト (`setup()` に第 2 引数として渡されます) のプロパティとして `emit` 関数にアクセスすることができます:
```

2022-04-20 04:58 UTC, hiro-lapis commented
@kazupon 
ありがとうございます、
suggentionを受け入れる形で修正させてもらいました！

2022-04-20 05:00 UTC, kazupon approved these changes

2022-04-20 05:00 UTC, kazupon commented
ありがとうございました。マージします！

2022-04-20 05:00 UTC, merged