「Guide > Built-in Components > Suspense」の翻訳
vuejs-translations/docs-ja pull request #451
Opened 2022-04-13 15:25 UTC by bobstrange

resolve #34

2022-04-15 12:31 UTC, jay-es requested changes
レビューしました。
1点だけ修正をお願いします:pray:

2022-04-15 12:31 UTC, jay-es commented on src/guide/built-ins/suspense.md
> +また、これらのコンポーネントは [Vue Router](https://router.vuejs.org/) の `<RouterView>` コンポーネントと組み合わせて使われることもよく有ります。
```suggestion
また、これらのコンポーネントは [Vue Router](https://router.vuejs.org/) の `<RouterView>` コンポーネントと組み合わせて使われることもよくあります。
```

2022-04-15 13:20 UTC, bobstrange commented on src/guide/built-ins/suspense.md
> +`<Suspense>` を [`<Transition>`](./transition) や [`<KeepAlive>`](./keep-alive) と組み合わせて使用したい場合はよく有ります。これらのコンポーネントを正しく動作させるためには、ネストの順番が重要です。
```suggestion
`<Suspense>` を [`<Transition>`](./transition) や [`<KeepAlive>`](./keep-alive) と組み合わせて使用したい場合はよくあります。これらのコンポーネントを正しく動作させるためには、ネストの順番が重要です。
```

2022-04-15 13:22 UTC, bobstrange commented
@jay-es 

レビューありがとうございます :bow:

https://github.com/vuejs-translations/docs-ja/pull/451#discussion_r851266323

同じ表現を使用している箇所がもう一つ有ったので、合わせて修正しました。

2022-04-18 12:13 UTC, jay-es approved these changes
ありがとうございます！
自分はOKです 🙆‍♂️

2022-04-19 16:07 UTC, kazupon approved these changes
翻訳ありがとうございます！
レヴュー 👀 遅くなりました 🙇 
確認したところよさそうです！

2022-04-19 16:07 UTC, merged