「Style Guide > Priority C Rules: Recommended」の翻訳
vuejs-translations/docs-ja pull request #452
Opened 2022-04-14 11:56 UTC by nabeken5

resolve #114

2022-04-15 12:47 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-04-15 12:47 UTC, jay-es commented on src/style-guide/rules-recommended.md
> +8. **イベント** (リアクティブイベントによるコールバック)
```suggestion
8. **イベント** (リアクティブイベントにトリガーされるコールバック)
```

2022-04-15 12:47 UTC, jay-es commented on src/style-guide/rules-recommended.md
> +   - ライフサイクルイベント (この順番に)
```suggestion
   - ライフサイクルイベント (呼び出される順番)
```

2022-04-15 12:47 UTC, jay-es commented on src/style-guide/rules-recommended.md
> +8. **その他の属性** (すべての未指定のバウンド＆アンバウンドアトリビュート)
```suggestion
8. **その他の属性** (すべての不特定のバインドされた/バインドされない属性)
```

2022-04-15 12:47 UTC, jay-es commented on src/style-guide/rules-recommended.md
> +// やはり見やすく、操作しやすいです。
ここは2行で一文として翻訳するのがよさそうです
```suggestion
// コンポーネントが読みやすく操作しやすければ、
// スペースなしでも構いません。
```

2022-04-15 12:47 UTC, jay-es commented on src/style-guide/rules-recommended.md
> +## シングルファイルコンポーネントのトップレベル要素の順序
```suggestion
## 単一ファイルコンポーネントのトップレベル要素の順序
```

2022-04-16 00:47 UTC, nabeken5 commented
@jay-es 修正しました！ありがとうございます。

2022-04-18 12:19 UTC, jay-es approved these changes
ありがとうございます。
自分はOKです 🙆‍♂️

2022-04-19 16:09 UTC, kazupon approved these changes
翻訳ありがとうございます！
レビュー 👀 しました。
よさそうです。

2022-04-19 16:09 UTC, merged