Guide essentials template refs
vuejs-translations/docs-ja pull request #453
Opened 2022-04-16 22:31 UTC by tanquar

resolve #18

2022-04-17 11:05 UTC, tanquar commented
翻訳しました。よろしくおねがいします。

2022-04-18 12:35 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-04-18 12:35 UTC, jay-es commented on src/guide/essentials/template-refs.md
> +`<script setup>` を使用しない場合は、以下のように `setup()` で参照を一緒に返す必要があります:
```suggestion
`<script setup>` を使用しない場合は、`setup()` から ref を返す必要もあります:
```

2022-04-18 12:35 UTC, jay-es commented on src/guide/essentials/template-refs.md
> +    // 要素がまだマウントされていない、またはアンマウントされた (v-if など)
```suggestion
    // 要素がまだマウントされていない、または（v-if などによって）アンマウントされた
```

2022-04-18 12:35 UTC, jay-es commented on src/guide/essentials/template-refs.md
> +特例は、`<script setup>` を使用するコンポーネントです。このようなコンポーネントは、デフォルトで**プライベート**となります。`<script setup>` が使われている子コンポーネントを親コンポーネントから参照する場合、親コンポーネントは、子コンポーネントで `defineExpose` マクロを使って選択されたパブリックインターフェース以外のものにアクセスすることができ
```suggestion
特例は、`<script setup>` を使用するコンポーネントです。このようなコンポーネントは、**デフォルトでプライベート**となります。`<script setup>` が使われている子コンポーネントを親コンポーネントから参照する場合、親コンポーネントは、子コンポーネントで `defineExpose` マクロを使って選択されたパブリックインターフェース以外のものにアクセスすることができません:
```

2022-04-18 12:35 UTC, jay-es commented on src/guide/essentials/template-refs.md
> +親がテンプレート参照を用いてこのコンポーネントのインスタンスを取得する場合、取得されるインスタンスは `{ a: number, b: number }` の形になります (通常のインスタンスと同様に、参照は自動的にアンラップされます)。
```suggestion
親がテンプレート参照を用いてこのコンポーネントのインスタンスを取得する場合、取得されるインスタンスは `{ a: number, b: number }` の形になります (通常のインスタンスと同様に、ref は自動的にアンラップされます)。
```

2022-04-19 16:14 UTC, kazupon reviewed
翻訳ありがとうございます！
レビュー 👀 しました。
よさそうです。

2022-04-19 16:14 UTC, kazupon commented
jay-es さんの指摘事項の修正お願いします。

2022-04-20 19:15 UTC, tanquar commented
ありがとうございます!
修正しました。よろしくおねがいします。

2022-04-21 11:23 UTC, jay-es approved these changes
ありがとうございます！

2022-04-21 11:24 UTC, merged