Update README.md and fix a typo
vuejs-translations/docs-ja pull request #465
Opened 2022-04-20 18:42 UTC by unlimish

resolve #443

2022-04-21 11:22 UTC, jay-es requested changes

2022-04-21 11:22 UTC, jay-es commented on README.md
> +このプロジェクトで使用するNode.jsは、Optional chainingなどのJavaScriptの新機能をコード内で使用するため、 `v14.0.0` 以降である必要があります。
package.json のバージョンに合わせ、元と同じように空行追加お願いします:pray:
```suggestion
このプロジェクトで使用するNode.jsは、Optional chainingなどのJavaScriptの新機能をコード内で使用するため、 `v14.19.0` 以降である必要があります。


```

2022-04-22 13:28 UTC, jay-es requested changes

2022-04-22 13:28 UTC, jay-es commented on README.md
> +このプロジェクトで使用するNode.jsは、Optional chainingなどのJavaScriptの新機能をコード内で使用するため、 `v14.19.0` 以降である必要があります。
たびたびすみません。textlint でエラーになるので、スペース追加お願いします:pray:
```suggestion
このプロジェクトで使用する Node.js は、Optional chaining などの JavaScript の新機能をコード内で使用するため、 `v14.19.0` 以降である必要があります。
```

2022-04-22 17:49 UTC, unlimish commented
スペース追加しました！もしかするとmainの [.textlintrc](https://github.com/vuejs-translations/docs-ja/blob/b1c19938c2723924be9dbb1d78255345b77043e4/.textlintrc) にスペースの設定が書かれてないっぽくこちら側ではエラーになりませんでした…

2022-04-25 12:00 UTC, jay-es approved these changes
ありがとうございます！
`preset-vuejs-jp` をベースとして読み込んでいるのでエラーが出る & `lint-staged` によってコミットが弾かれるはずなのですが...

2022-04-25 12:01 UTC, merged