translate provide-inject.md
vuejs-translations/docs-ja pull request #466
Opened 2022-04-21 10:42 UTC by hiro-lapis

resolve #25 

訳に悩んだ箇所があり、インラインでコメントを入れています。
よろしくお願いします🙇‍♂️

2022-04-21 10:43 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +## Prop ドリル
日本では`バケツリレー`の方が馴染みがある表現だと思うのですが、単語の意味がまるっきり変わってしまうので、原文(世界基準)に即した訳にしました。

2022-04-21 10:44 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +props ドリルは `provide` と `inject` で解決できます。親コンポーネントは、そのすべての子孫コンポーネントに対して **依存関係を提供するプロバイダー (dependency provider)** として機能することができます。子孫ツリー内のどのコンポーネントも、その深さに関係なく、親チェーン内の上位コンポーネントが提供する依存性を**注入 (inject)** するこ
プログラムとしてのprovide inject
処理の実質的意味合いとして注入
依存性の注入を実現する機能としてのプロバイダーとインジェクション

ニュアンスに応じて訳を変えた方が分かりやすいかと思い、文章ごとで訳を分けていますが、不適切・不備があれば指摘おねがいします🙇‍♂️

2022-04-21 11:54 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +## Prop ドリル
「Prop ドリル」だと見慣れない言葉になってしまうので、英語と併記するのが良いと思います
```suggestion
## props のバケツリレー（Prop Drilling）
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +`<Footer>` コンポーネントはこれらの props を全く気にしないかもしれませんが、`<DeepChild>` がそれらにアクセスできるように宣言して渡す必要があることに注意してください。さらに長い親チェーンがある場合、より多くのコンポーネントが影響を受けることになります。これは "props ドリル (props drilling)" と呼ばれていて、対処するのが楽しいことでないこと
```suggestion
`<Footer>` コンポーネントはこれらの props を全く気にしないかもしれませんが、`<DeepChild>` がそれらにアクセスできるように宣言して渡す必要があることに注意してください。さらに長い親チェーンがある場合、より多くのコンポーネントが影響を受けることになります。これは "props のバケツリレー（Prop Drilling）" と呼ばれていて、対処するのが楽しいことでないことは明らかです。
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +props ドリルは `provide` と `inject` で解決できます。親コンポーネントは、そのすべての子孫コンポーネントに対して **依存関係を提供するプロバイダー (dependency provider)** として機能することができます。子孫ツリー内のどのコンポーネントも、その深さに関係なく、親チェーン内の上位コンポーネントが提供する依存性を**注入 (inject)** するこ
```suggestion
props のバケツリレーは `provide` と `inject` で解決できます。親コンポーネントは、そのすべての子孫コンポーネントに対して **依存関係を提供するプロバイダー (dependency provider)** として機能することができます。子孫ツリー内のどのコンポーネントも、その深さに関係なく、親チェーン内の上位コンポーネントが提供する依存性を**注入 (inject)** することができます。
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +第 2 引数は提供された値です。この値は refs のようなリアクティブな状態を含む、任意の型であることができます:
```suggestion
第 2 引数は提供される値です。この値は refs のようなリアクティブな状態を含む、任意の型にすることができます:
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +    // `this` でアクセスできる関数構文を使用します
```suggestion
    // `this` にアクセスできるように関数構文を使用します
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +繰り返しますが、もし `<script setup>` を使用しないのであれば、`inject()` は `setup()` の内部でのみ同期的に呼び出されるべきです:
```suggestion
繰り返しますが、もし `<script setup>` を使用しないのであれば、`inject()` は `setup()` の内部でのみ同期的に呼び出す必要があります:
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +### デフォルト値のインジェクション
```suggestion
### インジェクションのデフォルト値
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +      from: 'message', // 同じキーで注入する時に任意で使います
```suggestion
      from: 'message', // 同じキーで注入する場合、これは省略可能です
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +`computed()` 関数は、通常 Composition API のコンポーネントで使用されますが、Options API の特定のユースケースを補完するために使用することもできます。[リアクティビティの基礎](/guide/essentials/reactivity-fundamentals.html)と[算出プロパティ](/guide/essentials/computed.html)
```suggestion
`computed()` 関数は、通常 Composition API のコンポーネントで使用されますが、Options API の特定のユースケースを補完するために使用することもできます。API Preference を Composition API に設定して[リアクティビティの基礎](/guide/essentials/reactivity-fundamentals.html)と[算出プロパティ](/guide/essentials/computed.html)を読むと、より詳しい使い方を学ぶことができます。
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +上記の使い方では、`app.config.unwrapInjectedRef = true` を設定して、インジェクションが自動的に計算された参照をアンラップするようにする必要があります。これは Vue 3.3 でデフォルトの動作になり、この設定は破損を避けるために一時的に導入されています。3.3 以降では不要になります。
```suggestion
上記の使い方では、`app.config.unwrapInjectedRef = true` を設定して、インジェクションが自動的に算出 ref をアンラップするようにする必要があります。これは Vue 3.3 でデフォルトの動作になり、この設定は破損を避けるために一時的に導入されています。3.3 以降では不要になります。
```

2022-04-21 11:54 UTC, jay-es commented on src/guide/components/provide-inject.md
> +:::warning 一時的に必要な設定
```suggestion
:::warning 一時的な設定が必要
```

2022-04-22 03:37 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +## Prop ドリル
ありがとうございます。
併記が分かりやすく、かつ英語圏の表現を知るきっかけになっていいですね！
修正しました！

2022-04-22 03:37 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +`<Footer>` コンポーネントはこれらの props を全く気にしないかもしれませんが、`<DeepChild>` がそれらにアクセスできるように宣言して渡す必要があることに注意してください。さらに長い親チェーンがある場合、より多くのコンポーネントが影響を受けることになります。これは "props ドリル (props drilling)" と呼ばれていて、対処するのが楽しいことでないこと
こちらも修正しました！

2022-04-22 03:38 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +props ドリルは `provide` と `inject` で解決できます。親コンポーネントは、そのすべての子孫コンポーネントに対して **依存関係を提供するプロバイダー (dependency provider)** として機能することができます。子孫ツリー内のどのコンポーネントも、その深さに関係なく、親チェーン内の上位コンポーネントが提供する依存性を**注入 (inject)** するこ
修正しました！

2022-04-22 03:38 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +第 2 引数は提供された値です。この値は refs のようなリアクティブな状態を含む、任意の型であることができます:
変な日本語になっちゃってましたね。。。
修正しました！

2022-04-22 03:38 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +    // `this` でアクセスできる関数構文を使用します
修正しました！

2022-04-22 03:39 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +繰り返しますが、もし `<script setup>` を使用しないのであれば、`inject()` は `setup()` の内部でのみ同期的に呼び出されるべきです:
修正しました！

2022-04-22 03:39 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +### デフォルト値のインジェクション
意味が変わってしまってましたね。。。失礼しました。
こちらも修正しました。

2022-04-22 03:39 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +      from: 'message', // 同じキーで注入する時に任意で使います
修正しました！

2022-04-22 03:39 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +`computed()` 関数は、通常 Composition API のコンポーネントで使用されますが、Options API の特定のユースケースを補完するために使用することもできます。[リアクティビティの基礎](/guide/essentials/reactivity-fundamentals.html)と[算出プロパティ](/guide/essentials/computed.html)
修正しました！

2022-04-22 03:40 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +上記の使い方では、`app.config.unwrapInjectedRef = true` を設定して、インジェクションが自動的に計算された参照をアンラップするようにする必要があります。これは Vue 3.3 でデフォルトの動作になり、この設定は破損を避けるために一時的に導入されています。3.3 以降では不要になります。
修正しました！

2022-04-22 03:53 UTC, hiro-lapis commented on src/guide/components/provide-inject.md
> +:::warning 一時的に必要な設定
修正しました！

2022-04-22 13:30 UTC, jay-es approved these changes
ありがとうございます！
自分はOKです 🙆‍♂️

2022-04-25 14:38 UTC, kazupon approved these changes
レビュー遅くなりました。
いつも翻訳ありがとうございます！
jay-esさんのコメント以外には見つかりませんでした。
LGTMです！

2022-04-25 14:38 UTC, merged