Guide components registration
vuejs-translations/docs-ja pull request #489
Opened 2022-04-25 20:19 UTC by tanquar

resolve #20

2022-04-25 20:19 UTC, tanquar commented
翻訳しました。よろしくおねがいします。

2022-04-26 13:48 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-04-26 13:48 UTC, jay-es commented on src/guide/components/registration.md
> +SFC を使用する場合は、以下のように `.vue` ファイルをインポートして登録します:
```suggestion
SFC を使用する場合は、インポートした `.vue` ファイルを登録します:
```

2022-04-26 13:48 UTC, jay-es commented on src/guide/components/registration.md
> +SFC と `<script setup>` の組み合わせを用いる場合、コンポーネントはインポートするだけで自動的にローカル登録されます:
```suggestion
SFC と `<script setup>` の組み合わせを用いる場合、インポートしたコンポーネントは自動的にローカル登録されます:
```

2022-04-26 14:15 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2022-04-26 14:15 UTC, kazupon commented on src/guide/components/registration.md
> +これは、サブコンポーネントにもすべて適用されます。そのため、上の 3 つのコンポーネントはどれもお互いの内側で使える、ということになります。
ここの `all subcomponents` ですが、構文的には、`to` かかる目的語だと思うので、以下のようになるかと思います。
後、`inside each other` のmarkdown の斜体と、その訳も以下のようにすると分かりやくなります。

```suggestion
これは、すべてのサブコンポーネントにも適用されます。そのため、上の 3 つのコンポーネントは _それぞれコンポーネント内_ で使える、ということになります。
```

2022-04-30 22:16 UTC, tanquar commented on src/guide/components/registration.md
> +これは、サブコンポーネントにもすべて適用されます。そのため、上の 3 つのコンポーネントはどれもお互いの内側で使える、ということになります。
ありがとうございます!
この部分はどのように訳すかとても悩みました。
最初の文は、「すべての」としてしまうと、日本語の文としてシンプルになりすぎて、後半の要約であるということを伝えきれない恐れがあるとおもいます。特にevenの重みが、英語と比べてずいぶん軽くなってしまいます。allは、「数量的に全体のどの程度か」「実在する具体的なオブジェクトのうち全数なのか」という意味なら「すべての」と形容詞的に訳してよいですが、ここでは「確率的に必ずなのか」「論理的な守備範囲として全体なのか」の意味のようなので、もう少しそれが伝わりやすい訳を考えてみました。

副詞的に:
`これは、サブコンポーネントにも漏れなく適用されます。`
`これは、サブコンポーネントであっても漏れなく適用されます。`

あえてallの訳語を外してevenを際立たせる:
`これは、サブコンポーネントにも適用されます。`
(allがなくても、必ず起きるものとして読める)

後半は、グローバル登録なら、サブコンポーネントの中で別のサブコンポーネントを呼ぶ準備さえも整っている、ということを伝えるのが趣旨であると捉えました。all threeとeach otherの重みが英語に比べて低下しないようにする必要があると思います。ただし、「相互」と訳すと無限ループを積極的に作るように読めるので、それは避けたいところです(実験したら無限ループになるパターンではMaximum call stack size exceededのエラーが起きました)。

1 `これは、サブコンポーネントにも漏れなく適用されます。そのため、上の 3 つのコンポーネントはすべて _互いのコンポーネント内_ でも使える、ということになります。`
2 `これは、サブコンポーネントにも漏れなく適用されます。そのため、上の 3 つのコンポーネントはすべて _それぞれのコンポーネント内でも_ 使える、ということになります。`
3 `これは、サブコンポーネントにも漏れなく適用されます。そのため、上の 3 つのコンポーネントは _それぞれのコンポーネント内でもすべて互いに_ 使える、ということになります。`
4 `これは、サブコンポーネントにも漏れなく適用されます。そのため、上の 3 つのコンポーネントはすべて _各コンポーネント内でも互いに_ 使える、ということになります。`

いくつかパターンを考えましたが、4でいかがでしょうか。

2022-05-01 00:52 UTC, kazupon commented on src/guide/components/registration.md
> +これは、サブコンポーネントにもすべて適用されます。そのため、上の 3 つのコンポーネントはどれもお互いの内側で使える、ということになります。
いくつか候補して頂きありがとうございます！
確かにそうですね。原文書いた人に聞かないと分からないところもありますが、パターン4 が無難なので、その内容でしましょう。

2022-05-01 02:14 UTC, tanquar commented on src/guide/components/registration.md
> +これは、サブコンポーネントにもすべて適用されます。そのため、上の 3 つのコンポーネントはどれもお互いの内側で使える、ということになります。
ご確認ありがとうございます!
4を適用して更新しました。よろしくおねがいします。

2022-05-01 02:16 UTC, kazupon approved these changes

2022-05-01 02:17 UTC, kazupon commented
ありがとうございます。自分はLGTMです。
jay-esさんが確認したらマージされると思います！

2022-05-02 11:11 UTC, jay-es approved these changes
ありがとうございます！

2022-05-02 11:12 UTC, merged