Guide Best Practices Security
vuejs-translations/docs-ja pull request #495
Opened 2022-04-29 08:34 UTC by hiro-lapis

resolve #44 

今回もレビューよろしくお願いします🙇‍♂️
数点インラインでコメントさせてもらっています。

2022-04-29 08:37 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +Vue のテンプレートは JavaScript にコンパイルされ、テンプレート内の式はレンダリングプロセスの一部として実行されます。式は特定のレンダリングコンテキストを対象に評価されます。ですが、潜在的なグローバル実行環境の複雑性のため、Vue のようなフレームワークが非現実的なパフォーマンスのオーバーヘッドを発生させずに潜在的な悪意のあるコードの実行から完全に守ることは実用的ではありません。こ
`Although the expressions are`の一文が難しい内容かつ長文なので二文にわけました。

2022-04-29 08:39 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +例えば、CodePen や JSFiddle のようなサービスでは、ユーザーが提供したコンテンツを実行することができます。しかし、それらはコンテンツの実行が想定されている状況であり、かつ iframe 内である程度サンドボックス化されたものです。重要な機能が本質的にある程度の脆弱性を必要とする場合、機能と脆弱性によって起こりうる最悪のシナリオのどちらを重視するかは、チーム次第です。
ここも長文のため`For example, services like ~`を二分に分けました。

2022-04-29 14:10 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +Vue のテンプレートは JavaScript にコンパイルされ、テンプレート内の式はレンダリングプロセスの一部として実行されます。式は特定のレンダリングコンテキストを対象に評価されます。ですが、潜在的なグローバル実行環境の複雑性のため、Vue のようなフレームワークが非現実的なパフォーマンスのオーバーヘッドを発生させずに潜在的な悪意のあるコードの実行から完全に守ることは実用的ではありません。こ
@jay-es 
ありがとうございます！
提案してもらった訳の方が意味が通ってますね。

修正させてもらったので、ご都合の良いときに再レビューいただいてもいいでしょうか🙇‍♂️

2022-04-30 13:16 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-01 01:09 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
確認お願いします！

2022-05-01 01:09 UTC, kazupon commented on src/guide/best-practices/security.md
> +テンプレートとレンダー関数のどちらを使用しても、コンテンツは自動的にエスケープされます。つまり、このテンプレートで:
render functions は [wiki](https://github.com/vuejs-translations/docs-ja/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E) にもある通り、以下でお願いします！
```suggestion
テンプレートと Render 関数のどちらを使用しても、コンテンツは自動的にエスケープされます。つまり、このテンプレートで:
```

2022-05-01 01:09 UTC, kazupon commented on src/guide/best-practices/security.md
> +- レンダー関数の使用:
ここの render functions も以下でお願いします。
```suggestion
- Render 関数の使用:
```

2022-05-01 01:09 UTC, kazupon commented on src/guide/best-practices/security.md
> +- JSX とレンダー関数の使用:
ここも同じく。
```suggestion
- JSX とRender 関数の使用:
```

2022-05-01 01:09 UTC, kazupon commented on src/guide/best-practices/security.md
> +テンプレートやレンダー関数に副作用があってはならないので、Vue で `<script>` 要素をレンダリングすることは控えてください。しかし、実行時に JavaScript として評価される文字列を含める方法は、これだけではありません。
ここも同じく。
```suggestion
テンプレートや Render 関数に副作用があってはならないので、Vue で `<script>` 要素をレンダリングすることは控えてください。しかし、実行時に JavaScript として評価される文字列を含める方法は、これだけではありません。
```

2022-05-01 11:43 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +新たな脆弱性が発見されることは稀ですが、アプリケーションを可能な限り安全に保つために、常に最新バージョンの Vue と公式コンパニオン・ライブラリーを使用することも推奨しています。
提案いただいた訳の方が分かりやすいですね。ありがとうございます！

2022-05-01 11:44 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +Vue を使用する際の最も重要なセキュリティールールは、**信頼できないコンテンツをコンポーネントテンプレートとして使用しないこと**です。これはアプリケーション内で恣意的な JavaScript の実行を許可することと同じです。さらに悪いことに、そのコードがサーバーサイドレンダリング中に実行されると、サーバー侵害につながる可能性があります。そのような使い方の例:
指摘もらった通りですね、修正しました！

2022-05-01 11:47 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +テンプレートとレンダー関数のどちらを使用しても、コンテンツは自動的にエスケープされます。つまり、このテンプレートで:
失礼しました🙇‍♂️修正しました。

2022-05-01 11:47 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +- レンダー関数の使用:
失礼しました🙇‍♂️修正しました。

2022-05-01 11:47 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +- JSX とレンダー関数の使用:
失礼しました🙇‍♂️修正しました。

2022-05-01 11:47 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +- JSX とレンダー関数の使用:
失礼しました🙇‍♂️修正しました。

2022-05-01 11:48 UTC, hiro-lapis commented on src/guide/best-practices/security.md
> +テンプレートやレンダー関数に副作用があってはならないので、Vue で `<script>` 要素をレンダリングすることは控えてください。しかし、実行時に JavaScript として評価される文字列を含める方法は、これだけではありません。
修正しました。

2022-05-01 11:51 UTC, hiro-lapis commented
@jay-es @kazupon 

連休中にもかかわらずレビューしてくださり、ありがとうございます。
修正をpushしたので、都合よろしい時に再レビューおねがいします🙇‍♂️

2022-05-01 13:47 UTC, kazupon approved these changes

2022-05-01 13:47 UTC, merged

2022-05-01 13:48 UTC, kazupon commented
ありがとうございました！