本家とsyncするため修正
vuejs-translations/docs-ja pull request #502
Opened 2022-05-02 22:53 UTC by nabeken5

resolve #431
本家とsyncするための修正です。

2022-05-03 00:18 UTC, jay-es requested changes
`src/partners/components/PartnerCard.vue` の差分がおかしくなっているので、
#476 の内容（本家ではこちらが先にコミットされている）も併せて取り込んでいただくか、
#475 は別のPRにて対応いただけますでしょうか。

2022-05-03 00:18 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +2. Vue のリアクティビティ追跡はプロパティアクセス上で動作するため、リアクティブなオブジェクトへの参照を常に同じに保つ必要があります。つまり、最初の参照へのリアクティブな接続が失われるため、リアクティブなオブジェクトを簡単に「置き換える」ことはできません。
原文の末尾がコロンなので修正お願いします:pray:
```suggestion
2. Vue のリアクティビティ追跡はプロパティアクセス上で動作するため、リアクティブなオブジェクトへの参照を常に同じに保つ必要があります。つまり、最初の参照へのリアクティブな接続が失われるため、リアクティブなオブジェクトを簡単に「置き換える」ことはできません:
```

2022-05-03 00:18 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +
スペース削除
```suggestion

```

2022-05-03 00:18 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> +   // 上記の参照（{ count: 0 }）は、もはや追跡されていません（リアクティブな接続が失われました！）。
句点不要
```suggestion
   // 上記の参照（{ count: 0 }）は、もはや追跡されていません（リアクティブな接続が失われました！）
```

2022-05-03 13:04 UTC, nabeken5 commented
@jay-es 修正しました！

2022-05-04 10:44 UTC, jay-es requested changes
#476 を取り込むのであれば以下のファイルも差分を反映お願いします:pray:
- `src/partners/components/type.ts`
- `src/partners/components/utils.ts`
- `src/partners/partners.json`
- `src/public/images/partners/passionatepeople-dark.png`
- `src/public/images/partners/vehikl-dark.svg`

2022-05-04 10:44 UTC, jay-es commented on src/guide/essentials/reactivity-fundamentals.md
> -
行がずれているので、改行追加お願いします

2022-05-05 11:49 UTC, nabeken5 commented
@jay-es 色々とすみません。できました。

2022-05-05 12:14 UTC, jay-es approved these changes

2022-05-05 12:15 UTC, merged