translate guide/components/async.md
vuejs-translations/docs-ja pull request #503
Opened 2022-05-04 06:17 UTC by shuuji3

resolve #26

こちらのレポジトリには初めてのコントリビューションです。レビューよろしくお願いします。

2022-05-04 10:59 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-05-04 10:59 UTC, jay-es commented on src/guide/components/async.md
> +  // ローディングコンポーネント表示前の遅延。デフォルト: ms200。
```suggestion
  // ローディングコンポーネント表示前の遅延。デフォルト: 200ms。
```

2022-05-04 10:59 UTC, jay-es commented on src/guide/components/async.md
> +  // 読み込みに失敗した場合にコンポーネント
```suggestion
  // 読み込みに失敗した場合に使用するコンポーネント
```

2022-05-04 10:59 UTC, jay-es commented on src/guide/components/async.md
> +ローディングコンポーネントが与えられた場合、内側のコンポーネントが読み込まれている間に表示されます。ローディングコンポーネントが表示されるまでに、デフォルトで 200ms の遅延があります。このようになっているのは、高速なネットワークではローディング状態が短く、置き換えが速すぎて、ちらつきのように見えてしまう恐れがあるためです。
行がずれているので、改行追加お願いします:pray:
```suggestion

ローディングコンポーネントが与えられた場合、内側のコンポーネントが読み込まれている間に表示されます。ローディングコンポーネントが表示されるまでに、デフォルトで 200ms の遅延があります。このようになっているのは、高速なネットワークではローディング状態が短く、置き換えが速すぎて、ちらつきのように見えてしまう恐れがあるためです。
```

2022-05-04 11:38 UTC, shuuji3 commented on src/guide/components/async.md
> +  // ローディングコンポーネント表示前の遅延。デフォルト: ms200。
すみません、これともう1つはエディタの不調による誤字ですね…。修正提案ありがとうございます。

2022-05-04 11:39 UTC, shuuji3 commented
@jay-es レビューありがとうございます！ 修正を反映しました。

2022-05-05 11:46 UTC, jay-es approved these changes
ありがとうございます！
自分はこの内容でOKです:pray:

2022-05-05 14:51 UTC, kazupon approved these changes
翻訳ありがとうございます！
確認 👀 しました。
LGTMです！

2022-05-05 14:51 UTC, merged