「Guide > Scaling Up > Server-Side Rendering (SSR)」の翻訳
vuejs-translations/docs-ja pull request #520
Opened 2022-05-05 13:52 UTC by hiro-lapis

resolve #40 

今回もよろしくおねがいします🙇‍♂️
例によって訳に悩む箇所がありましたので、コメント付けています。

2022-05-05 13:53 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +- **コンテンツ表示速度の高速化**: これは、低速のインターネットや低速のデバイスでより顕著です。サーバーレンダリングのマークアップは、すべての JavaScript のダウンロードと実行が完了するまで表示されるのを待つ必要がないため、ユーザーはより早く、完全にレンダリングされたページを見ることができます。さらに、初回アクセス時のデータ取得はサーバーサイドで行われるため、クライアントよりもデ
`time-to-content　`
`time`なので、直訳ならコンテンツ表示時間となりますが、日本では広くコンテンツ表示速度と呼ばれているため、この訳にしていました。

2022-05-05 13:54 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +  現時点で Google と Bing は、同期型の JavaScript アプリケーションを問題なくインデックスできます。ここでのキーワードは同期です。アプリケーションがローディングスピナー（ロード状態）と共に始まり、Ajax でコンテンツを取得する場合、クローラーはアプリケーションの終了を待ちません。つまり、SEO が重要なページで非同期にコンテンツを取得する場合、SSR が必要になるかも
`loading spinner`
直訳だと意味がわかりにくいかと思い、補足を入れています

2022-05-05 13:58 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +もしあなたが一握りのマーケティングページ（例：`/` 、`/about` 、`/contact` など）の SEO を改善するためだけに SSR を調べているなら、おそらく SSR の代わりに SSG が適しているでしょう。SSG は、ドキュメントサイトやブログのようなコンテンツベースのウェブサイトにも適しています。実際、あなたが今読んでいるこのウェブサイトは、Vue を利用した静的サイトジェネ
`you probably want SSG instead of SSR`
`望む`、`必要となる`、と訳すと不自然なため意訳してにしていました。

2022-05-05 14:00 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +完全な実装をするのは非常に複雑で、かつ、あなたが選んだビルドツールチェーンに依存します。したがって、私たちの考えた、複雑性を抽象化し、上位レベルのソリューションを利用することを強くお勧めします。以下では、Vue のエコシステムで推奨されるいくつかの SSR ソリューションを紹介します。
`opinionated solution`
調べてみたところ`自説を固執する`、`お気に入りの`などの訳があったのですが、しっくりくる訳がなかったので、
`vueコミュニティが推奨する解決策`というニュアンスを含んだ意訳にしました。

2022-05-05 14:01 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +ユニバーサルコードはプラットフォーム固有の API へのアクセスを想定できないため、`window` や `document` のようなブラウザー専用のグローバルクラスを直接使用したコードは、Node.js で実行するとエラーが発生します。また、その逆も同様です。
`global`
グローバルとだけ訳すと分かりにくいため`クラス`を付けています

2022-05-05 14:02 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +サードパーティのライブラリーがユニバーサルでの使用を念頭に置いて書かれていない場合、サーバーレンダリングされたアプリケーションに統合するのは困難な可能性があることに注意してください。グローバルクラスのいくつかをモックすることで動作させることができるかもしれません。しかし、それは場当たり的な対応に過ぎず、他のライブラリーの環境検出コードに干渉してしまう可能性があります。
`hacky`
スラングでいろいろな訳し方があるようでしたが、[こちら](https://hinative.com/ja/questions/13824464)を参考に訳にしてみました。

2022-05-05 14:04 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +推奨される解決策は、ルーターやグローバルストアを含むアプリケーション全体の新しいインスタンスを、リクエストごとに作成することです。それから、コンポーネントで直接インポートするのではなく、[アプリケーションレベルの Provide](/guide/components/provide-inject.html#app-level-provide) を使って共有する状態を提供し、それを必要とするコンポ
リンクテキストはリンク先となる[Provide/Inject](https://github.com/vuejs-translations/docs-ja/pull/466)の翻訳と合わせています。

2022-05-05 15:25 UTC, kazupon requested changes
いつも翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
確認お願いします！

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +アプリケーションに SSR を用いる前に、まず問うべき質問は、それが本当に必要かどうかということです。これは、アプリケーションにとってコンテンツ表示速度がどれだけ重要であるか次第です。例えば、チーム内のダッシュボードを作成していて、数百ミリ秒の初期ロードがあってもそれほど重要ではない場合、SSR はオーバーエンジニアリングになります。ですが、コンテンツ表示速度が絶対的に重要であるケースにおいては
よいと思います！ 👍

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +**スタティックサイトジェネレーション (SSG)** は、プリレンダリングとも呼ばれ、高速なウェブサイトを構築する、もう 1 つのポピュラーな技術です。ページのサーバーレンダリングに必要なデータが、全てのユーザーに対して同じであれば、リクエストが来るたびにページをレンダリングする代わりに、あらかじめビルド時に一度だけレンダリングしておくことができます。プリレンダリングされたページは、静的な H
`Static Site` はここ最近 web 関連の front-end 系のブログ等で `静的サイト` と書いてあることがあるので、そのように訳してもよさそうです。

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +**スタティックサイトジェネレーション (SSG)** は、プリレンダリングとも呼ばれ、高速なウェブサイトを構築する、もう 1 つのポピュラーな技術です。ページのサーバーレンダリングに必要なデータが、全てのユーザーに対して同じであれば、リクエストが来るたびにページをレンダリングする代わりに、あらかじめビルド時に一度だけレンダリングしておくことができます。プリレンダリングされたページは、静的な H
`popular technique` は良く使われていることを意味しているので、カタカナ日本語ではなく`代表的な技術` と意訳気味にしてもよい気がします。

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +もしあなたが一握りのマーケティングページ（例：`/` 、`/about` 、`/contact` など）の SEO を改善するためだけに SSR を調べているなら、おそらく SSR の代わりに SSG が適しているでしょう。SSG は、ドキュメントサイトやブログのようなコンテンツベースのウェブサイトにも適しています。実際、あなたが今読んでいるこのウェブサイトは、Vue を利用した静的サイトジェネ
そのまま訳すと確かにそうなので、意訳気味でいいかと思います！:+1:

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +## ベーシックチュートリアル
`Basic` は以下のように `基本` と訳してもよさそうです。
```suggestion
## 基本チュートリアル
```

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +完全な実装をするのは非常に複雑で、かつ、あなたが選んだビルドツールチェーンに依存します。したがって、私たちの考えた、複雑性を抽象化し、上位レベルのソリューションを利用することを強くお勧めします。以下では、Vue のエコシステムで推奨されるいくつかの SSR ソリューションを紹介します。
いいと思います！ 👍

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +ユニバーサルコードはプラットフォーム固有の API へのアクセスを想定できないため、`window` や `document` のようなブラウザー専用のグローバルクラスを直接使用したコードは、Node.js で実行するとエラーが発生します。また、その逆も同様です。
`クラス` はこの文脈では使わずに、そのまま `グローバル` でよい気がします。
`クラス` は web では、 DOM の `class` や、JavaScript / プログラミング言語の `class` といったり、様々な方面で使われているので。

2022-05-05 15:25 UTC, kazupon commented on src/guide/scaling-up/ssr.md
> +サードパーティのライブラリーがユニバーサルでの使用を念頭に置いて書かれていない場合、サーバーレンダリングされたアプリケーションに統合するのは困難な可能性があることに注意してください。グローバルクラスのいくつかをモックすることで動作させることができるかもしれません。しかし、それは場当たり的な対応に過ぎず、他のライブラリーの環境検出コードに干渉してしまう可能性があります。
`hacky` の訳はいいですね！ 👍 

ここでも、`グローバルクラス` という訳がありますが、`グローバル` でよさそうです。

2022-05-06 03:32 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +ユニバーサルコードはプラットフォーム固有の API へのアクセスを想定できないため、`window` や `document` のようなブラウザー専用のグローバルクラスを直接使用したコードは、Node.js で実行するとエラーが発生します。また、その逆も同様です。
指摘いただいた通りですね。。。修正します！

2022-05-06 03:33 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +サードパーティのライブラリーがユニバーサルでの使用を念頭に置いて書かれていない場合、サーバーレンダリングされたアプリケーションに統合するのは困難な可能性があることに注意してください。グローバルクラスのいくつかをモックすることで動作させることができるかもしれません。しかし、それは場当たり的な対応に過ぎず、他のライブラリーの環境検出コードに干渉してしまう可能性があります。
ありがとうございます！
こちらも指摘いただいた通りなので修正します！

2022-05-06 03:36 UTC, hiro-lapis commented
@kazupon 
ありがとうございます！
指摘いただいた箇所の修正をしたので、都合よろしい時に再レビューおねがいします🙇‍♂️

2022-05-06 13:33 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-05-06 13:33 UTC, jay-es commented on src/guide/scaling-up/ssr.md
> +実行するには以下のようにします:
```suggestion
次に以下を実行します:
```

2022-05-06 13:33 UTC, jay-es commented on src/guide/scaling-up/ssr.md
> +クライアントエントリーは、ユニバーサルコードを取り込み、アプケーションを作成し、マウントを実行します:
```suggestion
クライアントエントリーは、ユニバーサルコードをインポートしてアプリケーションを作成し、マウントを実行します:
```

2022-05-06 13:33 UTC, jay-es commented on src/guide/scaling-up/ssr.md
> +## 上位レベルの解決法
「上位」だと若干ニュアンスが変わってしまうので変更
```suggestion
## より高度な解決法
```

2022-05-06 13:33 UTC, jay-es commented on src/guide/scaling-up/ssr.md
> +プリレンダリングされた HTML の DOM 構造がクライアント側のアプリケーションが期待する内容と異なったときは、ハイドレーション・ミスマッチエラーになります。多くのケースでは、ブラウザーがネィティブ HTML を無効な HTML 文字列を正しい構造にパースしようとした時の動作によって起こります。 例えば、一般的な例として [`<div>` は `<p>` の内部に配置できない](https:
```suggestion
プリレンダリングされた HTML の DOM 構造がクライアント側のアプリケーションが期待する内容と異なったときは、ハイドレーション・ミスマッチエラーになります。多くのケースでは、ブラウザーのネイティブな HTML パース処理が、HTML 文字列の無効な構造を修正しようとした時に起こります。 例えば、一般的な例として [`<div>` は `<p>` の内部に配置できない](https://stackoverflow.com/questions/8397852/why-cant-the-p-tag-contain-a-div-tag-inside-it)ことなどがあります:
```

2022-05-07 13:34 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +Vue.js は、クライアントサイドのアプリケーションを構築するためのフレームワークです。デフォルトでは、Vue コンポーネントは、ブラウザー内の出力としてコンポーネントを生成し、DOM を操作します。ですが、同じコンポーネントをサーバー上で HTML 文字列にレンダリングし、それをブラウザーに直接送信し、最終的にクライアント上で完全にインタラクティブなアプリケーション内に静的なマークアップを"
ありがとうございます！
提案もらった文章の方が分かりやすいですね、修正します。

2022-05-07 13:35 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +アプリケーションに SSR を用いる前に、まず問うべき質問は、それが本当に必要かどうかということです。これは、アプリケーションにとってコンテンツ表示速度がどれだけ重要であるか次第です。例えば、チーム内のダッシュボードを作成していて、数百ミリ秒の初期ロードがあってもそれほど重要ではない場合、SSR はオーバーエンジニアリングになります。ですが、コンテンツ表示速度が絶対的に重要であるケースにおいては
確かにそうですね、修正します。

2022-05-07 13:36 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +SSG は SSR アプリケーションと同じパフォーマンス特性を持っており、優れたコンテンツ表示速度性能を提供します。同時に、出力内容が静的な　HTML　とアセットであるため、SSR　アプリケーションよりも低コストで簡単なデプロイが可能です。ここで重要なのは **static (静的)** というキーワードです: SSG は静的なデータ、つまりビルド時に既に内容が分かっていて、デプロイ時に変更され
失礼しました、修正します。

2022-05-07 13:37 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +実行するには以下のようにします:
修正します！

2022-05-07 13:38 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +クライアントエントリーは、ユニバーサルコードを取り込み、アプケーションを作成し、マウントを実行します:
こちらも修正します！

2022-05-07 13:39 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +## 上位レベルの解決法
上位だと優劣を感じさせてしまいますね😅修正します。

2022-05-07 13:50 UTC, hiro-lapis commented
@jay-es 
ありがとうございます！

遅れてすみませんが、
修正をpushさせていただいたので、手隙の際にレビューいただけますか🙇‍♂️

2022-05-07 13:50 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +プリレンダリングされた HTML の DOM 構造がクライアント側のアプリケーションが期待する内容と異なったときは、ハイドレーション・ミスマッチエラーになります。多くのケースでは、ブラウザーがネィティブ HTML を無効な HTML 文字列を正しい構造にパースしようとした時の動作によって起こります。 例えば、一般的な例として [`<div>` は `<p>` の内部に配置できない](https:
こちらも修正します！

2022-05-09 11:48 UTC, jay-es approved these changes
修正ありがとうございます！
kazupon さんの指摘箇所がいくつか残っているので対応お願いします

2022-05-09 13:38 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +**スタティックサイトジェネレーション (SSG)** は、プリレンダリングとも呼ばれ、高速なウェブサイトを構築する、もう 1 つのポピュラーな技術です。ページのサーバーレンダリングに必要なデータが、全てのユーザーに対して同じであれば、リクエストが来るたびにページをレンダリングする代わりに、あらかじめビルド時に一度だけレンダリングしておくことができます。プリレンダリングされたページは、静的な H
こちら確認もれてましてすみません、
修正します！

2022-05-09 13:38 UTC, hiro-lapis commented on src/guide/scaling-up/ssr.md
> +## ベーシックチュートリアル
確かにそうですね、修正します！

2022-05-09 14:38 UTC, kazupon approved these changes

2022-05-09 14:39 UTC, kazupon commented
@hiro-lapis 
ありがとうございます！確認したのでマージしますね！

2022-05-09 14:39 UTC, merged