「Guide > Built-in Components > KeepAlive」の翻訳
vuejs-translations/docs-ja pull request #531
Opened 2022-05-07 06:38 UTC by shuuji3

resolve #32

翻訳しました。よろしくお願いします。

2022-05-09 11:44 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-05-09 11:44 UTC, jay-es commented on src/guide/built-ins/keep-alive.md
> +`<KeepAlive>` は、複数のコンポーエント間を動的に切り替えるときに、コンポーネントインスタンスを条件付きでキャッシュ可能にするビルトインコンポーネントです。
```suggestion
`<KeepAlive>` は、複数のコンポーネント間を動的に切り替えるときに、コンポーネントインスタンスを条件付きでキャッシュ可能にするビルトインコンポーネントです。
```

2022-05-09 11:44 UTC, jay-es commented on src/guide/built-ins/keep-alive.md
> +デフォルトでは、アクティブなコンポーネントのインスタンスは、別のコンポーネントに切り替えられたときにアンマウントされます。これによりい、保持している変更された状態は失われてしまいます。
```suggestion
デフォルトでは、アクティブなコンポーネントのインスタンスは、別のコンポーネントに切り替えられたときにアンマウントされます。これにより、保持している変更された状態は失われてしまいます。
```

2022-05-09 11:44 UTC, jay-es commented on src/guide/built-ins/keep-alive.md
> +`max` prop を使うと、キャッシュできるコンポーネントインスタンスの最大数を制限することができます。`max` が指定された場合、`<KeepAlive>` は [LRU キャッシュ](<https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)>) のように動作します。つまり、キャ
「最も最後」で重複しているのと、「最も直近にアクセスされた」という意味にも読めてしまうので修正
```suggestion
`max` prop を使うと、キャッシュできるコンポーネントインスタンスの最大数を制限することができます。`max` が指定された場合、`<KeepAlive>` は [LRU キャッシュ](<https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)>) のように動作します。つまり、キャッシュインスタンスの数が指定された最大数を越えようとした時点で、最も過去にアクセスされたキャッシュインスタンスが破棄され、新しいキャッシュ用のスペースが作られます。
```

2022-05-09 11:44 UTC, jay-es commented on src/guide/built-ins/keep-alive.md
> +    // キャッシュから再挿入されるたびに呼ばれる
L99-100 の訳に合わせる
```suggestion
    // 最初のマウントと
    // キャッシュからの再挿入のたびに呼ばれる
```

2022-05-09 11:44 UTC, jay-es commented on src/guide/built-ins/keep-alive.md
> +  // アンマウント時に呼ばれる
L122-123 の訳に合わせる
```suggestion
  // DOM から削除されてキャッシュに挿入されるときと
  // アンマウントされるときにも呼ばれる
```

2022-05-09 14:51 UTC, kazupon requested changes
翻訳ありがとうございます！
レビュー 👀 コメント 💬 しました。
確認お願いします。

2022-05-09 14:51 UTC, kazupon commented on src/guide/built-ins/keep-alive-demos/CompA.vue
> +  <p>現在のコンポーネント: A</p>
コードの翻訳方針として、コメント (js の場合は `// ` or `/* */` 、htmlの場合は、`<!-- -->`)のみとなっているので、このケースの template 内のコードはしなくても大丈夫です！

ここの指摘以外にもされているかと思いますので、お手数ですが原文と同じ形にしておいてください。

2022-05-10 09:19 UTC, shuuji3 commented on src/guide/built-ins/keep-alive-demos/CompA.vue
> +  <p>現在のコンポーネント: A</p>
なるほど、了解しました。全体を見直して元に戻しますね。

2022-05-10 09:53 UTC, shuuji3 commented on src/guide/built-ins/keep-alive-demos/CompA.vue
> +  <p>現在のコンポーネント: A</p>
確認したところ、`CompA.vue` 以外には `CompB.vue` でのみ同じような翻訳をしてしまっていたので、両方とも原文の状態に戻しました。

2022-05-10 09:56 UTC, shuuji3 commented
レビューありがとうございました。提案していただいた修正の反映と、不必要に翻訳してしまった Vue テンプレート内のテキストのリバートをしました。

2022-05-10 12:45 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-17 15:35 UTC, kazupon approved these changes

2022-05-17 15:35 UTC, kazupon commented
すいません。遅くなりした。
ありがとうございました！マージします！

2022-05-17 15:35 UTC, merged

2022-05-17 23:06 UTC, shuuji3 commented
ありがとうございます！😀