本家とsyncするため修正
vuejs-translations/docs-ja pull request #532
Opened 2022-05-07 14:24 UTC by nabeken5

resolve #499
| このPRのコミット | docs-jaのissue | 本家のPR | 本家のコミット | 本家のコミットタイトル |
|---|---|---|---|---|
| https://github.com/vuejs-translations/docs-ja/commit/92e24bfb34b7c1d5708639af2edf833b9b4323d3 | https://github.com/vuejs-translations/docs-ja/issues/499 | https://github.com/vuejs/docs/pull/1682 | https://github.com/vuejs/docs/commit/65f5d62f783a05a30de2a78170cf4232b96fc930 | Fix wording about component use in script setup |

2022-05-07 14:40 UTC, nabeken5 commented on src/guide/essentials/template-syntax.md
> -この `disabled` という属性は、`isButtonDisabled` が [真値 (truthy value)](https://developer.mozilla.org/ja/docs/Glossary/Truthy) である場合に要素に含まれます。また、`<button disabled="">` との一貫性を保つため、値が空の文字列である場合にも含まれます。それ以外の偽値 (f
- リンクの位置に迷いました。これで良いでしょうか？
- `value` → `values`に変更されていたのでこちらも変更しました。

2022-05-07 14:41 UTC, nabeken5 commented on src/guide/essentials/template-syntax.md
> +この `disabled` という属性は、`isButtonDisabled` が [真値 (truthy value)](https://developer.mozilla.org/ja/docs/Glossary/Truthy) である場合に要素に含まれます。また、`<button disabled="">` との一貫性を保つため、値が空の文字列である場合にも含まれます。それ以外の偽値 ([
- リンクの位置に迷いました。これで良いでしょうか？
- `value` → `values`に変更されていたのでこちらも変更しました。

2022-05-09 12:02 UTC, jay-es requested changes
2点修正お願いします。
また、たくさんの issue をまとめると diff が混ざってレビューが大変になるので、1つずつ対応いただけると助かります:pray:（関連している issue の場合はまとめてもOKです）

2022-05-09 13:20 UTC, nabeken5 commented
@jay-es 修正しました。気をつけます。

2022-05-10 12:37 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-10 12:37 UTC, merged