Guide components in depth props
vuejs-translations/docs-ja pull request #554
Opened 2022-05-14 21:57 UTC by tanquar

resolve #21

2022-05-14 22:14 UTC, tanquar commented
翻訳しました。よろしくおねがいします。

2022-05-16 11:57 UTC, jay-es requested changes
props がそのままの箇所と「プロパティ」と翻訳している箇所があるのでどちらかに統一したいですが、他の方の意見も伺いたいです

- props で統一
  - 単数形の prop の訳に困る
- プロパティで統一
  - 原文に property もあるので、両者の違いが分からなくなる
  - 明確に使い分けられているかは不明

---
@tanquar 毎回同じブランチで作業しているように見えるので、次回以降はローカルに最新の `vuejs-translations/docs-ja` を取り込み、main から新しいブランチを生やしてください:pray:

2022-05-16 11:57 UTC, jay-es commented on src/guide/components/props.md
> +`defineProps()` に渡している引数と、Options API の `props` オプションに渡している値が同じであることに注目してください。props 用の同じ Options API が、2 つの宣言スタイル間で共有されています。
```suggestion
`defineProps()` に渡している引数と、Options API の `props` オプションに渡している値が同じであることに注目してください。同じ props オプションの API が、2 つの宣言スタイル間で共有されています。
```

2022-05-16 11:57 UTC, jay-es commented on src/guide/components/props.md
> +オブジェクト宣言の構文に含める各プロパティについて、キーにはプロパティの名前、値には目的の型のコンストラクタ関数を指定します。
```suggestion
オブジェクト宣言の構文に含める各プロパティについて、キーにはプロパティの名前、値には目的の型のコンストラクター関数を指定します。
```

2022-05-16 11:57 UTC, jay-es commented on src/guide/components/props.md
> +### 異なる種類の値を渡す
```suggestion
### いろいろな種類の値を渡す
```

2022-05-16 11:57 UTC, jay-es commented on src/guide/components/props.md
> +   // 算出プロパティ。プロパティが変更されると自動的に更新される。
L356 と同じに
```suggestion
   // プロパティが変更されると自動的に更新される算出プロパティ
```

2022-05-16 11:57 UTC, jay-es commented on src/guide/components/props.md
> +      // 受け取った生の各プロパティを引数として受け取ります。
```suggestion
    // オブジェクトと配列のデフォルトは、ファクトリー関数を使って
    // 返す必要があります。ファクトリー関数は、コンポーネントが
    // 受け取った生の各プロパティを引数として受け取ります。
```

2022-05-16 11:57 UTC, jay-es commented on src/guide/components/props.md
> +`type` には、以下のネイティブコンストラクタを指定することができます:
```suggestion
`type` には、以下のネイティブコンストラクターを指定することができます:
```

2022-05-16 11:57 UTC, jay-es commented on src/guide/components/props.md
> +加えて、`type` にはカスタムのクラスやコンストラクタ関数を指定することもできます。その場合、`instanceof` チェックによってアサーションが行われます。例えば、次のクラスがあったとします:
```suggestion
加えて、`type` にはカスタムのクラスやコンストラクター関数を指定することもできます。その場合、`instanceof` チェックによってアサーションが行われます。例えば、次のクラスがあったとします:
```

2022-05-16 23:46 UTC, tanquar commented
ありがとうございます! 翻訳したときの判断基準は概ねこうです。

- > 外部からコンポーネントに渡された props を
- > // setup() は第 1 引数に props を受け取ります。

↑構造上のpropsを言っているので「props」。

- > オブジェクトに含まれるすべてのプロパティを props として渡したい場合には

↑最も困ったポイント。「構造上のpropsを言っているのでprops」を踏襲して解決。

- > props は、以下のように [`props`](/api/options-state.html#props) オプションを使って宣言します:
- > `defineProps()` マクロを使って props を宣言します
- > 型アノテーションをそのまま使って props を宣言することも可能です

↑グレー。構造上のpropsとも、総称とも取れる。「構造上のpropsを言っているのでprops」を踏襲。
「プロパティ」に統一してもよいかもしれない。すぐサンプルコードでわかるので、読者は困らない。

- > // props は `this` 上で公開されます。
- > props の宣言には、文字列の配列に加え、オブジェクト構文を用いることもできます

↑グレー。より全体のことを言っているように見える。
総称で「プロパティ」にしたほうがよいかもしれない。

- > Props with `Boolean` type has → `Boolean` 型のプロパティは、

↑総称なので「プロパティ」。
日本語で「`Boolean` 型の props は」にすると、props自体が単一のBoolean値に見えて、
正しく理解されない恐れが高い。

- > コンポーネントの props の型付け
- > 型のみの props 宣言

↑翻訳済みの別ページのタイトルを引用。
より全体のことを言っているように見える。
総称で「プロパティ」にしたほうがよいかもしれない。

-> prop validation → プロパティのバリデーション

↑総称なので「プロパティ」。
「コンポーネントの props の型付け」と同じ意味レベルに思えるので、そちらがpropsなら、ここも連動させて「props のバリデーション」にしたい。
ここでprops validationと書けないのは英語特有の事情(名詞の形容詞的用法では単数形を用いる)で、本来は原文がprops validationと書いてあるものとして解釈したい。

2022-05-18 11:26 UTC, tanquar commented
ありがとうございます!
修正と、適用箇所の再確認は、今週末に試みます。

2022-05-24 11:42 UTC, jay-es approved these changes
ありがとうございます:pray:

2022-05-24 11:44 UTC, merged