「Guide > Scaling Up > Testing」の翻訳
vuejs-translations/docs-ja pull request #557
Opened 2022-05-16 16:08 UTC by hiro-lapis

resolve #39 

例によってPR内にコメントしています。
よろしくお願いします🙇‍♂️

2022-05-16 16:09 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +   "ブラックボックステスト"は、コンポーネントの実装の詳細については意識しません。これらのテストは、コンポーネントとシステム全体の統合をテストするために、できるだけモックを少なくします。通常、子コンポーネントをすべてレンダリングするため、より"統合テスト"に近いものと考えられています。以下、[コンポーネントテストの推奨事項](#component-testing)を参照してください。
一旦忠実に`"ホワイトボックステスト"のテストは、`と訳しましたが、不自然な文章に感じたので調整しました。ブラックボックステストの方も同様です。

2022-05-16 16:13 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +Vue アプリケーションでは、コンポーネントは UI の主要なビルディングブロックです。したがって、アプリケーションの動作を検証する時の分離の単位として、コンポーネントは自然な単位といえます。粒度の観点からは、コンポーネントテストはユニットテストの上のどこかに位置し、かつ統合テストの一形態とも考えることができます。Vue アプリケーションの多くはコンポーネントテストでカバーされるべきであり、各
`したがって、アプリケーションの動作を検証する時に、コンポーネントは分離するための自然な単位です。`
直訳だと↑みたいになるので、語句を少し足して意訳気味にしています。

2022-05-16 16:18 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +- [Vitest](https://vitest.dev/) はヘッドレスでレンダリングするコンポーネントやコンポーザブルのためのライブラリーです（例: VueUse の[`useFavicon`](https://vueuse.org/core/useFavicon/#usefavicon)関数など）。コンポーネントと DOM は [@testing-library/vue](https:/
タイポ（e.gの箇所のカッコに閉じカッコがない）がありましたが、訳では一旦カッコを入れて訳しました。
タイポについては[本家にプルリク](https://github.com/vuejs/docs/pull/1719)を立ててあります。

2022-05-16 16:19 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +Vitest とブラウザーベースのランナーの主な違いは、スピードと実行コンテキストです。つまり、Cypress のようなブラウザーベースのランナーは Vitest のようなノードベースのランナーでは捕捉できない問題（例: スタイルの問題、本物のネイティブ DOM イベント、クッキー、ローカルストレージ、ネットワーク障害など）をキャッチすることができます。ですが、ブラウザーベースのランナーは、ブラ
こちらも原文の * が不足してますが、訳に際して足してあります。
こちらも[本家にPRを](https://github.com/vuejs/docs/pull/1721)立ててあります。

2022-05-17 14:22 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

また全体的に interface の訳は「インターフェース」に統一お願いします:pray:

2022-05-17 14:22 UTC, jay-es commented on src/guide/scaling-up/testing.md
> +Vitest とブラウザーベースのランナーの主な違いは、スピードと実行コンテキストです。つまり、Cypress のようなブラウザーベースのランナーは Vitest のようなノードベースのランナーでは捕捉できない問題（例: スタイルの問題、本物のネイティブ DOM イベント、クッキー、ローカルストレージ、ネットワーク障害など）をキャッチすることができます。ですが、ブラウザーベースのランナーは、ブラ
アスタリスク1つは斜体での強調なので間違いというわけではなさそう...

2022-05-17 14:22 UTC, jay-es commented on src/guide/scaling-up/testing.md
> +    // happy-dom 環境の DOM をシミュレーションします
```suggestion
    // happy-dom で DOM をシミュレーションします
```

2022-05-18 13:29 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +Vitest とブラウザーベースのランナーの主な違いは、スピードと実行コンテキストです。つまり、Cypress のようなブラウザーベースのランナーは Vitest のようなノードベースのランナーでは捕捉できない問題（例: スタイルの問題、本物のネイティブ DOM イベント、クッキー、ローカルストレージ、ネットワーク障害など）をキャッチすることができます。ですが、ブラウザーベースのランナーは、ブラ
指摘いただいた通り斜体強調していただけで修正必要ありませんでした🙇‍♂️
本家のPR close + 修正翻訳の修正をします。

2022-05-18 13:32 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +Vue 固有のセクションが 1 つあり、そこではコンポーザブル関数をカバーしています。詳しくは、以下の [コンポーザブル関数 のテスト](#testing-composables)を参照してください。
自然な訳の提案ありがとうございます！
修正します。

2022-05-18 13:34 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +- **ユニット**: 関数、クラス、あるいはコンポーザブル関数へ与えられた入力が、期待される出力や副作用を作っているかどうかをチェックします。
修正します！

2022-05-18 13:34 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +- **コンポーネント**: コンポーネントのマウント、レンダリング、それらがインタラクティブであるか、期待通りのふるまいであるかをチェックします。これらのテストはユニットテストよりも多くのコードをインポートし、より複雑で、実行に多くの時間を必要とします。
指摘の通りですね、修正します！

2022-05-18 14:12 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +  `create-vue` で作成される公式の設定は [Vite](https://vitejs.dev/) をベースにしているので、Vite と同じ設定・変換パイプラインを直接利用できるユニットテストフレームワークを使用することをお勧めします。[Vitest](https://vitest.dev/) は、この目的のために特別に設計されたユニットテストフレームワークで、Vue / Vite
修正します。

2022-05-18 14:13 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +コンポーネントテストは、コンポーネントのプロップス、イベント、提供するスロット、スタイル、クラス、ライフサイクルフックなどに関する問題を検出するようにする必要があります。
その通りですね！修正します。

2022-05-18 14:14 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +コンポーネントテストでは、子コンポーネントをモックするのではなく、代わりにユーザーと同じようにコンポーネントと相互的な操作を行い、 コンポーネントとその子コンポーネントの間のインタラクションをテストするのが望ましいです。例えば、コンポーネントテストでは、プログラムでコンポーネントとやりとりするのではなく、 ユーザーが行うように要素をクリックするようにしなければなりません。
余計なスペース失礼しました。修正します。

2022-05-18 14:16 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +- **やらないこと**
指摘いただいた方が適切な訳ですね、修正します！

2022-05-18 14:18 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +ユニットテストは開発者にある程度の信頼性を与えますが、ユニットテストやコンポーネントテストは、本番環境に展開したときにアプリケーションの総合的なカバレッジを提供する性能が制限されます。その結果として、E2E（エンドツーエンド）テストは、アプリケーションの最も重要な側面に関するカバレッジを提供します: すなわち、ユーザーが実際にアプリケーションを使用するときに何が起こるか、です。
デプロイの方がしっくりきますね、修正します！

2022-05-18 14:22 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +従来の開発者はテストで何が問題だったかを判断するための方法としてターミナルウィンドウのログ調査に頼っていましたが、最新のエンドツーエンド（E2E）テストフレームワークでは、開発者がすでに使い慣れているツール、例えばブラウザーの開発者ツールを活用することができます。
`従来の開発者`だと変ですね😅
修正します。

2022-05-18 14:23 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +次に、 Vite の設定を更新して `test` オプションブロックを追加します:
すみません、こちらも修正します。

2022-05-18 14:23 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +    // happy-dom 環境の DOM をシミュレーションします
修正します！

2022-05-18 14:26 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +コンポーザブルをテストする場合、2 つのカテゴリーに分割することができます:ホストコンポーネントのインスタンスに依存しないコンポーザブルと、依存するコンポーザブルです。
修正します！

2022-05-18 14:35 UTC, hiro-lapis commented
本家で行った修正の影響で、216行目にコンフリクトが発生していました。
翻訳後の文章を残す形で解消しています。

![image](https://user-images.githubusercontent.com/53115998/169067269-9427d5b4-3c35-4864-ab97-01a4c9411d19.png)

2022-05-18 14:40 UTC, hiro-lapis commented
@jay-es 
多数の指摘、お手数かけました。
修正させてもらいましたので手隙の際に再レビューいただけますか🙇‍♂️

2022-05-19 11:58 UTC, jay-es requested changes
ありがとうございます！
1箇所修正お願いします:pray:

2022-05-19 11:58 UTC, jay-es commented on src/guide/scaling-up/testing.md
> +- **やってはいけないこ**
```suggestion
- **やってはいけないこと**
```

2022-05-19 14:00 UTC, hiro-lapis commented
@jay-es 
ケアレスミス失礼しました🙇‍♂️
suggestを受け入れる形で修正させてもらいました。

2022-05-20 12:18 UTC, jay-es approved these changes
ありがとうございます:pray:

2022-05-27 04:32 UTC, hiro-lapis commented
@kazupon 
お世話になってます。
こちら手隙の際にレビューいただけますか🙇‍♂️

2022-05-28 15:54 UTC, kazupon requested changes
いつも翻訳ありがとうございます！
レビュー 👀 が遅くなってすません。
コメント箇所 💬 確認お願いします。

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +Vitest は比較的新しく、現在も急速に開発が進んでいます。まだ安定しているとは言えませんが、チームはプロダクションレディの状態にするために懸命に動いています。
`production ready` の翻訳ですが、そのままカタカナ和訳にすると違和感があるので、以下のようの意訳気味でよいと思います。
```suggestion
Vitest は比較的新しく、現在も急速に開発が進んでいます。まだ安定しているとは言えませんが、チームは本番環境で利用可能な状態にするために懸命に動いています。
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +- [Jest](https://jestjs.io/) はポピュラーなユニットテストフレームワークで、[vite-jest](https://github.com/sodatea/vite-jest) パッケージによって Vite で動作させることができます。ですが、Jest を推奨するのは既存の Jest テストスイートを Vite ベースのプロジェクトに移行する必要がある場合のみです。Vi
`popular` の訳も、以下のように訳すと違和感がないと思います。
```suggestion
- [Jest](https://jestjs.io/) はよく知られたユニットテストフレームワークで、[vite-jest](https://github.com/sodatea/vite-jest) パッケージによって Vite で動作させることができます。ですが、Jest を推奨するのは既存の Jest テストスイートを Vite ベースのプロジェクトに移行する必要がある場合のみです。Vitest はよりシームレスな統合と優れたパフォーマンスを提供するからです。
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +## ユニットテスト
`Unit Testing`  や `Unit Test` は、日本で `単体テスト` という用語が一般的になっているので、そのように訳しましょう。
```suggestion
## 単体テスト
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +## ユニットテスト
以降で、`ユニットテスト` と翻訳している部分もお願いも修正お願いします！ 🙏

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +Vue アプリケーションでは、コンポーネントは UI の主要なビルディングブロックです。したがって、アプリケーションの動作を検証する時の分離の単位として、コンポーネントは自然な単位といえます。粒度の観点からは、コンポーネントテストはユニットテストの上のどこかに位置し、かつ統合テストの一形態とも考えることができます。Vue アプリケーションの多くはコンポーネントテストでカバーされるべきであり、各
いいと思います！ 👍

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +コンポーネントテストは、コンポーネントの props、イベント、提供するスロット、スタイル、クラス、ライフサイクルフックなどに関する問題を検出するようにする必要があります。
`props` も、この文章のコンテキストでは、Vue のコンポーネントが提供するプロパティのこと指しているので、`プロパティ` と訳しましょう。
```suggestion
コンポーネントテストは、コンポーネントのプロパティ、イベント、提供するスロット、スタイル、クラス、ライフサイクルフックなどに関する問題を検出するようにする必要があります。
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +コンポーネントのテストでは、内部実装の詳細よりもそのコンポーネントのパブリックなインターフェイスに注目する必要があります。ほとんどのコンポーネントでは、公開インターフェースは発行されるイベント、props、スロットに限定されています。テストする際は**コンポーネントが何をするのかをテストするのであって、どのようにするのかをテストするのではない** ことを忘れないようにしましょう。
ここの `props` もそうですね。
```suggestion
コンポーネントのテストでは、内部実装の詳細よりもそのコンポーネントのパブリックなインターフェイスに注目する必要があります。ほとんどのコンポーネントでは、公開インターフェースは発行されるイベント、プロパティ、スロットに限定されています。テストする際は**コンポーネントが何をするのかをテストするのであって、どのようにするのかをテストするのではない** ことを忘れないようにしましょう。
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +- **ビジュアル** のロジック: 入力されたプロップスとスロットに基づくレンダリング結果の正しさを評価します。
ここの `props` は `プロップス` ではなく、`プロパティ` ですね。
```suggestion
- **ビジュアル** のロジック: 入力されたプロパティとスロットに基づくレンダリング結果の正しさを評価します。
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +  以下の例では、"increment" というラベルの付いた DOM 要素を持ち、クリックすることができるステッパー・コンポーネントを示しています。`max` という props を渡すことで、ステッパーが `2` を超えてインクリメントすることを防ぎます。したがって、ボタンを 3 回クリックしても、UI は `2` と表示されるはずです。
`Stepper` の意味としては、ここでは `increment` によって値が次々に増えていくことを意味していますが、一言で翻訳するのが難しいので、カッコ付けで以下のように最初に用語がでてきたところで、以下のように注釈気味な形にしておきましょう。
あと、`props` もこの文章の文脈では`プロパティ`で大丈夫ですね。
```suggestion
  以下の例では、"increment" というラベルの付いた DOM 要素を持ち、クリックすることができるステッパー(Stepper:値が増えていく)コンポーネントを示しています。`max` というプロパティを渡すことで、ステッパーが `2` を超えてインクリメントすることを防ぎます。したがって、ボタンを 3 回クリックしても、UI は `2` と表示されるはずです。
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +  私たちはステッパーの実装について何も知りません。ただ、"入力"が `max` props で、"出力"がユーザーが見る DOM の状態であることだけが分かっています。
```suggestion
  私たちはステッパーの実装について何も知りません。ただ、"入力"が `max` プロパティで、"出力"がユーザーが見る DOM の状態であることだけが分かっています。
```

2022-05-28 15:54 UTC, kazupon commented on src/guide/scaling-up/testing.md
> +  スナップショットテストだけに頼らないでください。HTML 文字列のアサーションは正しさを表すものではありません。意図を持ってテストを書いてください。
`Asserting` はここでは、`評価` にしておくとよさそうです。
```suggestion
  スナップショットテストだけに頼らないでください。HTML 文字列の評価は正しさを表すものではありません。意図を持ってテストを書いてください。
```

2022-05-29 01:39 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +Vitest は比較的新しく、現在も急速に開発が進んでいます。まだ安定しているとは言えませんが、チームはプロダクションレディの状態にするために懸命に動いています。
提案いただいた文の方が自然ですね、修正します！

2022-05-29 01:40 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +- [Jest](https://jestjs.io/) はポピュラーなユニットテストフレームワークで、[vite-jest](https://github.com/sodatea/vite-jest) パッケージによって Vite で動作させることができます。ですが、Jest を推奨するのは既存の Jest テストスイートを Vite ベースのプロジェクトに移行する必要がある場合のみです。Vi
ありがとうございます、修正します！

2022-05-29 01:42 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +## ユニットテスト
ありがとうございます、該当箇所すべて修正します🏃‍♂️

2022-05-29 01:44 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +コンポーネントテストは、コンポーネントの props、イベント、提供するスロット、スタイル、クラス、ライフサイクルフックなどに関する問題を検出するようにする必要があります。
文をちゃんと読めてなかったですね🙇‍♂️指摘の通り修正します。

2022-05-29 01:45 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +コンポーネントのテストでは、内部実装の詳細よりもそのコンポーネントのパブリックなインターフェイスに注目する必要があります。ほとんどのコンポーネントでは、公開インターフェースは発行されるイベント、props、スロットに限定されています。テストする際は**コンポーネントが何をするのかをテストするのであって、どのようにするのかをテストするのではない** ことを忘れないようにしましょう。
修正します。

2022-05-29 01:46 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +- **ビジュアル** のロジック: 入力されたプロップスとスロットに基づくレンダリング結果の正しさを評価します。
ですね😅修正します🙇‍♂️

2022-05-29 01:53 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +  以下の例では、"increment" というラベルの付いた DOM 要素を持ち、クリックすることができるステッパー・コンポーネントを示しています。`max` という props を渡すことで、ステッパーが `2` を超えてインクリメントすることを防ぎます。したがって、ボタンを 3 回クリックしても、UI は `2` と表示されるはずです。
ありがとうございます、
提案いただいた内容の方が、ステッパーの実装経験がない方にも読む方に分かりやすいですね。
修正します！

2022-05-29 01:55 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +  私たちはステッパーの実装について何も知りません。ただ、"入力"が `max` props で、"出力"がユーザーが見る DOM の状態であることだけが分かっています。
修正します🏃‍♀️

2022-05-29 01:55 UTC, hiro-lapis commented on src/guide/scaling-up/testing.md
> +  スナップショットテストだけに頼らないでください。HTML 文字列のアサーションは正しさを表すものではありません。意図を持ってテストを書いてください。
修正します！

2022-05-29 02:21 UTC, hiro-lapis commented
@kazupon 
ありがとうございます🙌  指摘いただいた箇所の修正をさせてもらいました。
手隙の際に再レビューよろしくおねがいします!

2022-05-30 14:26 UTC, kazupon approved these changes

2022-05-30 14:26 UTC, kazupon commented
@hiro-lapis 
ありがとうございます！
マージします！

2022-05-30 14:26 UTC, merged