[#17] translation #17 into Japanese
vuejs-translations/docs-ja pull request #568
Opened 2022-05-21 11:11 UTC by okakyo

resolve #17 

ご確認のほど、よろしくお願いいたします 🙇🏻

2022-05-23 12:58 UTC, jay-es requested changes
レビューしました。
修正お願いします:pray:

誤字などが多いので、次回以降はレビュー依頼する前にご自身で見直していただけると助かります:bow:

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +        // 同じ値として認識されます。[](https://twitter.com/cx_mezamashi)
```suggestion
        // 等しくなります。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +リアクティブなオブジェクト上で、`watch()` 関数を直接呼び出すとき、暗黙的に deep watcher が生成されます。 - そのため、コールバックはすべてのネスト状のミューテーション状で実行されます。
```suggestion
リアクティブなオブジェクト上で、`watch()` 関数を直接呼び出すとき、暗黙的に deep watcher が生成されます。 - そのため、コールバックはすべてのネストした変更で実行されます:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +  // ネスト状のプロパティのミューテーションで実行されまず.
```suggestion
  // ネストしたプロパティの変更で実行されます
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +監視対象のオブジェクトでは、ネストされた全てのプロパティを Deep watch はトラバースする必要があるため、大きなデータ構造で使用するときにはコストが高くなります。使用するときは、どうしても必要なときにだけ使用し、パフォーマンスへの影響に注意しましょう。
不自然に感じたので主語を移動しました:bow:
```suggestion
deep watch は、監視対象のオブジェクトのネストされた全てのプロパティをトラバースする必要があるため、大きなデータ構造で使用するときにはコストが高くなります。使用するときは、どうしても必要なときにだけ使用し、パフォーマンスへの影響に注意しましょう。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +`watch()` は遅延して実行されます: 監視対象の値が変更するまでコールバックは実行されません。しかし、同様のコールバックのロジックを先に実行したい場合もあります。- たとえば、初期値のデータを読み込み、関連するステート値が変更されるたび、再びデータを読み込みたいときです。気づいたら次のようにしているかもしれません:
上の方で state は「状態」と訳されていたので統一
```suggestion
`watch()` は遅延して実行されます: 監視対象の値が変更するまでコールバックは実行されません。しかし、同様のコールバックのロジックを先に実行したい場合もあります。- たとえば、初期値のデータを読み込み、関連する状態が変更されるたび、再びデータを読み込みたいときです。気づいたら次のようにしているかもしれません:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +`watch` は、デフォルトでは、遅延して実行されます: 監視対象の値が変更するまでコールバックは実行されません。しかし、同様のコールバックのロジックを先に実行したい場合もあります。- たとえば、初期値のデータを読み込み、関連するステート値が変更されるたび、再びデータを読み込みたいときです。
上の方で state は「状態」と訳されていたので統一
```suggestion
`watch` は、デフォルトでは、遅延して実行されます: 監視対象の値が変更するまでコールバックは実行されません。しかし、同様のコールバックのロジックを先に実行したい場合もあります。- たとえば、初期値のデータを読み込み、関連する状態が変更されるたび、再びデータを読み込みたいときです。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +`handler` 関数や `immediate: true` オプションを設定したオブジェクトを利用して宣言することで、監視対象のコールバック関数をすぐ実行させることができます:
```suggestion
`handler` 関数と `immediate: true` オプションを設定したオブジェクトを利用して宣言することで、監視対象のコールバック関数をすぐ実行させることができます:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +      // 前倒しして、コールバックの実行を強制します。 force eager callback execution
```suggestion
      // 前倒しして、コールバックの実行を強制します。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +これは、[`watchEffect()`](/api/reactivity-core.html#watcheffect) によって簡略化されます。`watchEffect()` によって、effect のリアクティブな依存先を自動的に追跡している間、副作用をすぐに実行してくれるようになります。上記の例を次のように書き直すことができます:
while には同時の意味もあります
```suggestion
これは、[`watchEffect()`](/api/reactivity-core.html#watcheffect) によって簡略化できます。`watchEffect()` によって、effect のリアクティブな依存先を自動的に追跡しつつ、副作用をすぐに実行してくれるようになります。上記の例を次のように書き直すことができます:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +このように、コールバックはすぐに実行されます。実行している間、依存先 (計算済みのプロパティに似たもの) としての `url.value` を自動的に追跡してくれます。`url.value` が変更されるたびに、コールバックは再実行されます。
```suggestion
これで、コールバックはすぐに実行されます。実行している間、依存先（算出プロパティに似たもの）としての `url.value` を自動的に追跡してくれます。`url.value` が変更されるたびに、コールバックは再実行されます。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +`watchEffect` は **非同期な**処理を行っている間は、依存先しか追跡しません。非同期のコールバックと一緒に使用する場合、最初の `await` が追跡される前にのみプロパティはアクセスしません。
意味が変わってしまっているので修正
```suggestion
`watchEffect` は**同期的な**処理中のみ依存先を追跡します。非同期のコールバックで使用する場合、最初の `await` の前にアクセスされたプロパティのみが追跡されます。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +- `watch` は明示的に示されたソースしか監視しません。コールバック内でアクセスされたものは追跡しません。加えて、コーヅバックはソースが実際に変更したときにのみ実行されません。`watch` は依存性の追跡を副作用から分離します。それにより、コールバックが実行されるときにより正確にコントロールすることができます。
```suggestion
- `watch` は明示的に示されたソースしか監視しません。コールバック内でアクセスされたものは追跡しません。加えて、コールバックはソースが実際に変更したときにのみ実行されます。`watch` は依存性の追跡を副作用から分離します。それにより、コールバックをいつ実行するかをより正確にコントロールすることができます。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +##　コールバックが実行されるタイミング
```suggestion
## コールバックが実行されるタイミング
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +リアクティブのステートが変更されるとき、Vue コンポーネントの更新と生成された watcher コール’バックを実行します。
```suggestion
リアクティブな状態が変更されるとき、Vue コンポーネントの更新と生成された watcher コールバックを実行します。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +デフォルトでは、ユーザーが生成した watcher のコールバックは Vue コンポーネントが更新される**前に**呼ばれます。これはつまり、コールバックないの DOM へアクセスしようとするとき、Vue がすべての更新が適用される前は、DOM はステート内にあります。
```suggestion
デフォルトでは、ユーザーが生成した watcher のコールバックは Vue コンポーネントが更新される**前に**呼ばれます。これはつまり、コールバック内で DOM へアクセスしようとすると、DOM は Vue が更新を適用される前の状態です。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +もし Vue の更新**後**に watcher コールバック内の DOM へアクセスしたいとき、`flush: 'post'` オプションで指定する必要があります:
```suggestion
もし Vue の更新**後**に watcher コールバック内で DOM へアクセスしたいとき、`flush: 'post'` オプションで指定する必要があります:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
>  import { watchPostEffect } from 'vue'
333 行目も翻訳お願いします:pray:

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +また、[`メソッド内の $watch()`](/api/component-instance.html#watch) を使用して watcher を強制的に作成することが可能です:
```suggestion
また、[`$watch() インスタンスメソッド`](/api/component-instance.html#watch) を使用して watcher を強制的に作成することが可能です:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +親コンポーネントがマウントされなかったときに `watch` オプションを使って宣言した watchers、あるいは `$watch()` インスタンスメソッドは自動的に停止します。そのため、多くの場合において、watcher 自体が停止することを心配する必要はありません。
unmount の訳を修正。また「親コンポーネント」だと文脈が変わってしまうので変更
```suggestion
`watch` オプションを使って宣言した watchers、あるいは `$watch()` インスタンスメソッドは、オーナーコンポーネントがアンマウントされた自動的に停止します。そのため、多くの場合において、watcher 自体が停止することを心配する必要はありません。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +ごくまれに、親コンポーネントがマウントされなくなるよりも前に停止する必要になる場合には、`$watch()` API は次のような関数を返します:
```suggestion
ごくまれに、オーナーコンポーネントがアンマウントされる前に停止する必要がある場合には、`$watch()` API は次のような関数を返します:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +// ...wathcer がもはや必要なくなったとき
```suggestion
// ...wathcer がもはや必要なくなったとき:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +`setup()`, あるいは  `<script setup>` 内に同期的に宣言された watcher により、親コンポーネントのインスタンスにバインドされます。それにより、親コンポーネントがマウントされなかったときに自動的に停止されます。多くの場合、watcher 自体が停止することを心配する必要はありません。
```suggestion
`setup()`, あるいは  `<script setup>` 内に同期的に宣言された watcher により、オーナーコンポーネントのインスタンスにバインドされます。それにより、オーナーコンポーネントがアンマウントされたときに自動的に停止されます。多くの場合、watcher を自分で停止させることを心配する必要はありません。
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +ここで重要なのは、watcher **が同期的に** 生成されなければならないということです。もし watcher が非同期なコールバックで生成されたら、親コンポーネントはバインドされず、メモリーリークを避けるために手動で停止しなければいけないからです。それは次の通りです:
```suggestion
ここで重要なのは、watcher が**同期的に** 生成されなければならないということです。もし watcher が非同期なコールバックで生成されたら、オーナーコンポーネントにはバインドされず、メモリーリークを避けるために手動で停止しなければいけないからです。それは次の通りです:
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +// ...必要なくなっったときには後回しになります。
```suggestion
// ...あとで、もはや必要なくなったとき
```

2022-05-23 12:58 UTC, jay-es commented on src/guide/essentials/watchers.md
> +もし非同期のデータを待つ必要があるなら、watch のロジックの条件を代わりに作ることができます:
```suggestion
非同期的に watcher を作成する必要にある場合はほとんどになく、可能な限り同期的に作成する方が望ましいことに注意してください。もし非同期のデータを待つ必要があるなら、代わりに watch のロジックを条件付きにすることができます:
```

2022-05-28 16:02 UTC, kazupon requested changes
翻訳ありがとうございます！
私の方でも見ましたが、ほぼ jay-es さんの指摘箇所と同じなので、jay-es さんが指摘した箇所の対応お願いします！

2022-06-04 07:22 UTC, okakyo commented
修正を行いました。ご確認のほどよろしくお願いいたします 🙇🏻

2022-06-04 12:43 UTC, jay-es requested changes
修正ミスがあったのでコメントしました。
また前回コメントした箇所がいくつか残っているので対応お願いします（もし意図的に残している場合はコメントで知らせてください:pray:）

プッシュした後は以下のURLを見て、間違いや対応漏れなどがないかご確認お願いします:pray:
https://github.com/vuejs-translations/docs-ja/pull/568/files

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +//  watch 関数は ref を直接扱えます
スペースが増えているので削除お願いします
```suggestion
// watch 関数は ref を直接扱えます
```

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +`watch` の第一引数は、リアクティブな「ソース」のさまざまな型に対応しています: その引数には ref（算出された ref も含む）やリアクティブなオブジェクト、getter 関数、あるいは複数のソースの配列といったものです:
前回のサジェスト内容と異なっているので修正お願いします
```suggestion
`watch` の第一引数は、リアクティブな「ソース」のさまざまな型に対応しています: その引数には ref（算出 ref も含む）やリアクティブなオブジェクト、getter 関数、あるいは複数のソースの配列といったものです:
```

用語集に合わせるための修正です。再度ご確認お願いします:pray: 
https://github.com/vuejs-translations/docs-ja/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +`watch` はデフォルトではネストが浅い場合にしか対応していません: そのため、コールバックは監視対象のプロパティに新しい値が割り当てられた場合にしか実行されません。- そのため、そのため、ネストしたプロパティの変更があった場合には実行されません。もし、ネストしたすべての変更でコールバックが実行されるようにする場合、deep watcher を使用する必要があります。
「そのため」が2回になっています。
```suggestion
`watch` はデフォルトではネストが浅い場合にしか対応していません: そのため、コールバックは監視対象のプロパティに新しい値が割り当てられた場合にしか実行されません。- そのため、ネストしたプロパティの変更があった場合には実行されません。もし、ネストしたすべての変更でコールバックが実行されるようにする場合、deep watcher を使用する必要があります。
```

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +これは、[`watchEffect()`](/api/reactivity-core.html#watcheffect) によって簡略化できます。`watchEffect()` によって、effect のリアクティブな依存先を自動的に追跡しつつ、、副作用をすぐに実行してくれるようになります。上記の例を次のように書き直すことができます:
「、」が2回になっている
```suggestion
これは、[`watchEffect()`](/api/reactivity-core.html#watcheffect) によって簡略化できます。`watchEffect()` によって、effect のリアクティブな依存先を自動的に追跡しつつ、副作用をすぐに実行してくれるようになります。上記の例を次のように書き直すことができます:
```

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
>  Post-flush `watchEffect()` also has a convenience alias, `watchPostEffect()`:
原文が残っているので削除お願いします
```suggestion
```

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +オーナーコンポーネントがアンマウントされる前に停止する必要がある場合には、`$watch()` API は次のような関数を返します:
前回あった「ごくまれに、」が消えている
```suggestion
ごくまれに、オーナーコンポーネントがアンマウントされる前に停止する必要がある場合には、`$watch()` API は次のような関数を返します:
```

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +ここで重要なのは、watcher が**同期的に** 生成されなければならないということです。もし watcher が非同期なコールバックで生成されたら、オーナーコンポーネントはバインドされず、メモリーリークを避けるために手動で停止しなければいけないからです。それは次の通りです:
「に」が抜けている
```suggestion
ここで重要なのは、watcher が**同期的に** 生成されなければならないということです。もし watcher が非同期なコールバックで生成されたら、オーナーコンポーネントにはバインドされず、メモリーリークを避けるために手動で停止しなければいけないからです。それは次の通りです:
```

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +
行がずれているので、改行削除お願いします

2022-06-04 12:43 UTC, jay-es commented on src/guide/essentials/watchers.md
> +###　監視ソースの種類
全角スペースなのでマークダウンで見出しになっていない
```suggestion
### 監視ソースの種類
```

2022-06-04 13:00 UTC, okakyo commented
修正の対応を行いました。
何度も確認していただき申し訳ありません。
ご確認のほどよろしくお願いします！

2022-06-06 12:28 UTC, jay-es requested changes
修正もれがあるので対応お願いします

2022-06-06 12:28 UTC, jay-es commented on src/guide/essentials/watchers.md
> +リアクティブのステートが変更されるとき、Vue コンポーネントの更新と生成された watcher コールバックを実行します。
```suggestion
リアクティブな状態が変更されるとき、Vue コンポーネントの更新と生成された watcher コールバックを実行します。
```

2022-06-10 20:42 UTC, okakyo commented
修正対応しました！ご確認のほどよろしくお願いします！

2022-06-11 11:39 UTC, jay-es approved these changes
ありがとうございました:pray:

2022-06-11 11:39 UTC, merged