docs: translate state-management
vuejs-translations/docs-ja pull request #569
Opened 2022-05-21 14:18 UTC by bobstrange

resolve #38

2022-05-24 11:38 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-05-24 11:38 UTC, jay-es commented on src/guide/scaling-up/state-management.md
> +# 状態 (state) の管理
「状態管理」で浸透しているので、併記なしで問題ないと思います
```suggestion
# 状態管理
```

2022-05-24 11:38 UTC, jay-es commented on src/guide/scaling-up/state-management.md
コードコメントも翻訳お願いします:pray:

2022-05-24 11:38 UTC, jay-es commented on src/guide/scaling-up/state-management.md
> +## リアクティブ API によるシンプルな状態の管理
用語集に準拠
```suggestion
## リアクティビティ API によるシンプルな状態の管理
```

2022-05-24 11:38 UTC, jay-es commented on src/guide/scaling-up/state-management.md
> +オプション API では、リアクティブなデータは `data()` オプションによって宣言されます。内部的には、`data()` で返されたオブジェクトは、公開されている API として利用できる [`reactive()`](/api/reactivity-core.html#reactive) 関数によってリアクティブになります。
用語集に準拠
```suggestion
Options API では、リアクティブなデータは `data()` オプションによって宣言されます。内部的には、`data()` で返されたオブジェクトは、公開されている API として利用できる [`reactive()`](/api/reactivity-core.html#reactive) 関数によってリアクティブになります。
```

2022-05-24 11:38 UTC, jay-es commented on src/guide/scaling-up/state-management.md
> +- タイムライン、コンポーネントインスペクション、タイムとトラベルデバッグなどの Vue DevTools との統合
```suggestion
- タイムライン、コンポーネントインスペクション、タイムトラベルデバッグなどの Vue DevTools との統合
```

2022-05-24 11:38 UTC, jay-es commented on src/guide/scaling-up/state-management.md
> +- サーバサイドレンダリングのサポート
```suggestion
- サーバーサイドレンダリングのサポート
```

2022-05-25 12:05 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-05-28 16:05 UTC, kazupon approved these changes
いつも翻訳ありがとうございます！
確認しました！
jay-es さんが指摘箇所以外は特に問題はありませんでした！

2022-05-28 16:05 UTC, merged