「Guide > Extra Topics > Ways of Using Vue」の翻訳
vuejs-translations/docs-ja pull request #584
Opened 2022-05-29 05:40 UTC by KanDai

resolve #48

ご確認のほど、よろしくお願いします！

2022-05-29 14:52 UTC, kazupon requested changes
翻訳、ありがとうございます。
レビュー 👀 コメント 💬 しておきました。
確認お願いします。

2022-05-29 14:52 UTC, kazupon commented on src/guide/extras/ways-of-using-vue.md
> +## Jamstack / 静的サイトジェネレーション (SSG)
翻訳はガイドにもありますが、なるべく原文の内容を維持したいので、`JAMStack` のままでお願いします。 🙏 
```suggestion
## JAMStack / 静的サイトジェネレーション (SSG)
```

2022-05-29 14:52 UTC, kazupon commented on src/guide/extras/ways-of-using-vue.md
> +## Jamstack / 静的サイトジェネレーション (SSG)
他の部分も対応したところ、同様でお願いします。

2022-05-30 01:31 UTC, KanDai commented on src/guide/extras/ways-of-using-vue.md
> +## Jamstack / 静的サイトジェネレーション (SSG)
ありがとうございます！URL以外で2箇所あったので修正しました！

その他の表記もざっと確認しましたが大丈夫そうです。

2022-05-30 11:42 UTC, jay-es approved these changes
自分はOKです:ok_man:

2022-05-30 14:25 UTC, kazupon approved these changes

2022-05-30 14:25 UTC, kazupon commented
@KanDai 
翻訳ありがとうございました。
マージします！

2022-05-30 14:25 UTC, merged