「Guide > Scaling Up > Tooling」の翻訳
vuejs-translations/docs-ja pull request #597
Opened 2022-06-06 15:52 UTC by bobstrange

resolve #36

2022-06-06 15:55 UTC, bobstrange commented on src/guide/scaling-up/tooling.md
> +- 推奨の IDE の設定は [VSCode](https://code.visualstudio.com/) + [Volar](https://github.com/johnsoncodehk/volar) の拡張です。Volor は、シンタックスハイライト、TypeScript のサポート、テンプレートとコンポーネントの props の intellisense を提供します。
template expressions をテンプレート式と表記する逆に読みづらさがあったあったので、そのままテンプレートとしています。

以前の日本語ドキュメントや、今回リンクを変更した
https://github.com/vuejs-translations/docs-ja/pull/597/files#diff-8183105086d85d809928b7b13552d83f3079a479747b0ec0ec3b32160356f52cR42
でもテンプレート式という表現があるにはあるので、テンプレート式と表現した方が良さそうでしたら変更します。

2022-06-07 11:31 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-06-07 11:31 UTC, jay-es commented on src/guide/scaling-up/tooling.md
> +Vue をビルドステップなしで使用する場合、コンポーネントテンプレートページの HTML に直接もしくはインラインの JavaScript の文字列として書き込まれます。Vue はオンザフライでテンプレートのコンパイルを実行するために、テンプレートコンパイラーをブラウザーに同梱する必要があります。一方、ビルドステップでテンプレートをプリコンパイルすれば、コンパイラーは不要になります。Vue は、
「は」を追加しました
```suggestion
Vue をビルドステップなしで使用する場合、コンポーネントテンプレートはページの HTML に直接もしくはインラインの JavaScript の文字列として書き込まれます。Vue はオンザフライでテンプレートのコンパイルを実行するために、テンプレートコンパイラーをブラウザーに同梱する必要があります。一方、ビルドステップでテンプレートをプリコンパイルすれば、コンパイラーは不要になります。Vue は、クライアントのバンドルサイズを小さくするために、ユースケースごとに最適化された [さまざまな「ビルド」](https://unpkg.com/browse/vue@3/dist/) を提供しています。
```

2022-06-07 11:31 UTC, jay-es commented on src/guide/scaling-up/tooling.md
> +デフォルトのツールのセットアップでは、SFC 内の全てのテンプレートがコンパイル済みのため、ランタイムのみのビルドを使用しまし。もし、何らかの理由でビルドステップが有ってもブラウザー上でのコンパイルが必要な場合は、`vue` の代わりに `vue/dist/vue.esm-bundler.js` にエイリアスするようにビルドツールを設定すれば、コンパイルできるようになります。
```suggestion
デフォルトのツールのセットアップでは、SFC 内の全てのテンプレートがコンパイル済みのため、ランタイムのみのビルドを使用します。もし、何らかの理由でビルドステップが有ってもブラウザー上でのコンパイルが必要な場合は、`vue` の代わりに `vue/dist/vue.esm-bundler.js` にエイリアスするようにビルドツールを設定すれば、コンパイルできるようになります。
```

2022-06-07 11:31 UTC, jay-es commented on src/guide/scaling-up/tooling.md
> +ビルドステップが無いより軽量なものをお探しの場合は、[petie-vue](https://github.com/vuejs/petite-vue) をチェックしてみてください。
```suggestion
ビルドステップが無いより軽量なものをお探しの場合は、[petite-vue](https://github.com/vuejs/petite-vue) をチェックしてみてください。
```

2022-06-07 11:31 UTC, jay-es commented on src/guide/scaling-up/tooling.md
> +- 推奨の IDE の設定は [VSCode](https://code.visualstudio.com/) + [Volar](https://github.com/johnsoncodehk/volar) の拡張です。Volor は、シンタックスハイライト、TypeScript のサポート、テンプレートとコンポーネントの props の intellisense を提供します。
"template expressions" を「テンプレート」にしてしまうと意味が変わってしまうので、「テンプレート式」か「テンプレート内の式」などに変更お願いします:pray:

2022-06-07 11:31 UTC, jay-es commented on src/guide/scaling-up/tooling.md
>  - Use [`vue-tsc`](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc) for performing the same type checking from the command line, or for generating `d.ts` files for SFCs.
原文が残っているので削除お願いします:pray:
```suggestion
```

2022-06-07 13:48 UTC, bobstrange commented on src/guide/scaling-up/tooling.md
> +- 推奨の IDE の設定は [VSCode](https://code.visualstudio.com/) + [Volar](https://github.com/johnsoncodehk/volar) の拡張です。Volor は、シンタックスハイライト、TypeScript のサポート、テンプレートとコンポーネントの props の intellisense を提供します。
テンプレート内の式とか、テンプレート内の JavaScript の方が適して要ると思われるので、テンプレート内の式に変更しようと思います :bow:

2022-06-07 13:49 UTC, bobstrange commented on src/guide/scaling-up/tooling.md
> +- 推奨の IDE の設定は [VSCode](https://code.visualstudio.com/) + [Volar](https://github.com/johnsoncodehk/volar) の拡張です。Volor は、シンタックスハイライト、TypeScript のサポート、テンプレートとコンポーネントの props の intellisense を提供します。
```suggestion
- 推奨の IDE の設定は [VSCode](https://code.visualstudio.com/) + [Volar](https://github.com/johnsoncodehk/volar) の拡張です。Volor は、シンタックスハイライト、TypeScript のサポート、テンプレート内の式とコンポーネントの props の intellisense を提供します。
```

2022-06-07 13:50 UTC, bobstrange commented on src/guide/scaling-up/tooling.md
> +- [Volar](https://github.com/johnsoncodehk/volar) は `<script lang="ts">` ブロックを使用した SFC に対して、テンプレートやコンポーネント間のプロパティの検証を含む型チェックを提供します。
```suggestion
- [Volar](https://github.com/johnsoncodehk/volar) は `<script lang="ts">` ブロックを使用した SFC に対して、テンプレート内の式やコンポーネント間のプロパティの検証を含む型チェックを提供します。
```

2022-06-07 14:06 UTC, bobstrange commented
@jay-es 

レビューありがとうございます :bow:
以下、修正しましたので、再度よろしくお願いします。

- レビュー内容の修正 [db7c943](https://github.com/vuejs-translations/docs-ja/pull/597/commits/db7c943dda8afa8b44a240f26f171d7a20b03ee1)
- テンプレート式 -> テンプレート内の式に変更 [ca088e8](https://github.com/vuejs-translations/docs-ja/pull/597/commits/ca088e8c532b00ea5e13bb2f6fd4cbf8f1218d77)
    - 検索したところ、"テンプレート式" も "テンプレート内の式" も同じくらい存在したので、一律 "テンプレート内の式" に変換しました
- タイプチェック -> 型チェックに変更 [c9d5a81](https://github.com/vuejs-translations/docs-ja/pull/597/commits/c9d5a81dc59661b716a85ed925be3076195f2d81)
    - 他全てで型チェックだったので修正しました

2022-06-08 10:58 UTC, bobstrange commented
@jay-es 

ありがとうございます :bow:
取り込みましたので、スミマセンが再度ご確認よろしくお願いいたします :bow:

2022-06-09 11:58 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-06-19 13:57 UTC, kazupon approved these changes
遅くなりました 🙇 
確認しました！よさそうです！

2022-06-19 13:57 UTC, merged