translation reactivity-in-depth
vuejs-translations/docs-ja pull request #605
Opened 2022-06-08 14:52 UTC by hiro-lapis

resolve #50

2022-06-09 04:12 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +次に、いくつかの用語を定義する必要があります:
termsの訳に悩みました。
用語、条件など様々ありますが、ここでは用語で訳しました。

2022-06-09 04:13 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +- `A0` と `A1` はエフェクトの**依存関係**と見なされ、それらの値はエフェクトを実行するために使用されます。エフェクトは依存関係との関係において**サブスクライバー**と言われます。
reactivity-coreのページでも作用・エフェクトと二つの呼び方があるためカッコ付きで書いています

2022-06-09 12:48 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-06-09 12:48 UTC, jay-es commented on src/guide/extras/reactivity-in-depth.md
> +- リアクティブオブジェクトのプロパティをローカル変数に割り当てたり破壊した場合、ローカル変数へのアクセスがプロキシーが仕込んだ get/set をトリガーしなくなり、リアクティビティが"切断"されます。
destructure を「分割代入」に変更
```suggestion
- リアクティブオブジェクトのプロパティをローカル変数に割り当てたり分割代入した場合、ローカル変数へのアクセスはプロキシーが仕込んだ get/set をトリガーしなくなるため、リアクティビティが"切断"されます。
```

2022-06-09 12:48 UTC, jay-es commented on src/guide/extras/reactivity-in-depth.md
> +エフェクトサブスクリプションは、グローバルなデータストラクチャ `WeakMap<target, Map<key, Set<effect>>` に格納されます。もし、あるプロパティに対してサブスクライブするエフェクトの Set が見つからなかった場合（初めて追跡された場合）、Set が作成されます。簡単にではありますが、これが `getSubscribersForProperty()` 関数が行
```suggestion
エフェクトサブスクリプションは、グローバルなデータストラクチャ `WeakMap<target, Map<key, Set<effect>>` に格納されます。もし、あるプロパティに対してサブスクライブするエフェクトの Set が見つからなかった場合（初めて追跡された場合）、Set が作成されます。要するに、これが `getSubscribersForProperty()` 関数が行うことです。説明の簡略化のため、詳細は割愛します。
```

2022-06-12 00:59 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +console.log(A2) // まだ 3 です
確かにそうですね、修正しました！

2022-06-12 01:00 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +- リアクティブオブジェクトのプロパティをローカル変数に割り当てたり破壊した場合、ローカル変数へのアクセスがプロキシーが仕込んだ get/set をトリガーしなくなり、リアクティビティが"切断"されます。
修正しました！

2022-06-12 01:01 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +エフェクトサブスクリプションは、グローバルなデータストラクチャ `WeakMap<target, Map<key, Set<effect>>` に格納されます。もし、あるプロパティに対してサブスクライブするエフェクトの Set が見つからなかった場合（初めて追跡された場合）、Set が作成されます。簡単にではありますが、これが `getSubscribersForProperty()` 関数が行
意味間違えてましたね、修正しました。

2022-06-12 01:01 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +ref の変更のためにリアクティブエフェクトを使用するのはあまり気持ちのいい使い方ではありません。実際、算出プロパティに対して使う方がより宣言的です:
修正しました🙇‍♂️

2022-06-12 01:01 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +。なので、リアクティブな状態にアクセスするには、常にリアクティブオブジェクトか refs を使ってオブジェクトのプロパティとしてアクセスしなければなりません。
失礼しました、修正しました🙇‍♂️

2022-06-12 01:02 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +私たちは、コードの冗長性を減らすために[リアクティビティトランスフォーム](/guide/extras/reactivity-transform.html)機能を実験的に使用しています:
機能なので英語表記のままの方がいいですね、修正しました🙇‍♂️

2022-06-12 01:02 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +このスニペットは、変数への参照の後に自動的に `.value` を追加することで、トランスフォームなしで書いたものと全く同じにコンパイルされます。リアクティビティトランスフォームによって、Vue のリアクティビティシステムは洗練されたものになります。
修正しました！

2022-06-12 01:02 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +- `onTrigger` 依存関係の変更によってウォッチャーのコールバック関数がトリガーされたときに呼ばれます。
修正しました！

2022-06-12 01:02 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +// plusOne にアクセスし、onTrack がトリガーされる
修正しました！

2022-06-12 01:03 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +Vue のリアクティビティシステムを外部の状態管理ソリューションと統合する一般的な方法は、外部の状態を [`shallowRef`](/api/reactivity-advanced.html#shallowref) で保持することです。shallow ref は `.value` プロパティにアクセスしたときのみリアクティブになり、内部の値はそのまま残されます。内部の値はそのまま残ります。外部
失礼しました、修正しました🙇‍♂️

2022-06-12 01:03 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +// count.value を変更し、onTrigger がトリガーされる
修正しました！

2022-06-12 01:03 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +[ステートマシン](https://en.wikipedia.org/wiki/Finite-state_machine)は、アプリケーションが取りうるすべての状態と、ある状態から別の状態に移行するためのすべての方法を記述するためのモデルです。単純なコンポーネントには過剰かもしれませんが、複雑な状態繊維をより堅牢で管理しやすくするのに役立ちます。
失礼しました、修正しました🙇‍♂️

2022-06-14 11:59 UTC, jay-es approved these changes
ありがとうございます。自分はOKです！:ok_man:

2022-06-19 14:34 UTC, kazupon requested changes
いつも翻訳ありがとうございます！
レビュー 👀 遅くなってしまい、すいません。
内容確認お願いします。

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +Vue の最も特徴的な機能の 1 つは、控えめなリアクティビティシステムです。コンポーネントの状態はリアクティブな JavaScript オブジェクトです。状態を変更すると、ビューが更新されます。状態管理はシンプルで直感的ですが、よくある落とし穴を避けるために、仕組みを理解することも重要です。このセクションでは Vue のリアクティビティシステムのローレベルの詳細について、いくつか掘り下げていき
`the view updates.` の訳ですが、MVCを知っている人、それなりに経験のある開発者を考慮すると、カッコ付で英語表記があった方が、初心者だけではに人にも理解のたすけになるかと思います。
また、`lower-level` は比較級も入っているので、`より低レベルな` と訳すとよさそうです。
```suggestion
Vue の最も特徴的な機能の 1 つは、控えめなリアクティビティシステムです。コンポーネントの状態はリアクティブな JavaScript オブジェクトです。状態を変更すると、ビュー (View) が更新されます。状態管理はシンプルで直感的ですが、よくある落とし穴を避けるために、仕組みを理解することも重要です。このセクションでは Vue のリアクティビティシステムのより
低レベルな詳細について、いくつか掘り下げていきます。
```

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +# リアクティビティの深み
これまでに Vue のドキュメントでは、`xxx in Depth` は `xxx の探求` と訳してきたいので、それに習うとよさそうです。
https://v3.ja.vuejs.org/guide/reactivity.html
```suggestion
# リアクティビティの探求
```

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +次に、いくつかの用語を定義する必要があります:
いいと思います！

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +- `update()` 関数はプログラムの状態を変更するため、**サイドエフェクト（副作用）**、もしくは略して**エフェクト（作用）**を発生させます。
`side effect` と `effect` の訳ですが、前回の翻訳でそれぞれ、`副作用` と `作用` として訳したので、そのように訳しておいてください。
https://v3.ja.vuejs.org/guide/reactivity.html#vue-%E3%81%8B%E3%82%99%E5%A4%89%E6%9B%B4%E3%82%92%E3%81%A8%E3%82%99%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB%E8%BF%BD%E8%B7%A1%E3%81%99%E3%82%8B%E3%81%AE%E3%81%8B

ここでの文章は、それぞれ単語が初めてでてくるので、以下でお願いします。
```suggestion
- `update()` 関数はプログラムの状態を変更するため、**副作用（サイドエフェクト: side effect）**、もしくは略して**作用（エフェクト: effect）**を発生させます。
```

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +- `update()` 関数はプログラムの状態を変更するため、**サイドエフェクト（副作用）**、もしくは略して**エフェクト（作用）**を発生させます。
以降にこのファイルででてくる `side effect` と `effect` はそれぞれ、`副作用` と `作用` で訳すようお願いします。 🙏

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +2. 実行中のエフェクトがあるときに変数が読み込まれた場合、エフェクトをその変数のサブスクライバーにします。例： `update()` が実行されているときに `A0` と `A1` が読み込まれるので、最初の呼び出し以降は `update()` が `A0` と `A1` の両方のサブスクライバーになります。
`subscriber` もここでは、日本語で訳しておいてください。:pray:
ここでの文章で、初めて単語がでてくるところなので、日英同時表記 `購読者（subscriber）` として訳してください。

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +2. 実行中のエフェクトがあるときに変数が読み込まれた場合、エフェクトをその変数のサブスクライバーにします。例： `update()` が実行されているときに `A0` と `A1` が読み込まれるので、最初の呼び出し以降は `update()` が `A0` と `A1` の両方のサブスクライバーになります。
以降の `subscriber` も同様に上記のように日本語で訳してください。

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +この時点で、依存関係を自動的に追跡し、依存関係が変更されるたびに再実行するエフェクトが作成しました。これを**リアクティブエフェクト**と呼びます。
ここも日英表記でお願いします。 🙏 
```suggestion
この時点で、依存関係を自動的に追跡し、依存関係が変更されるたびに再実行するエフェクトが作成しました。これを**リアクティブ作用（Reactive Effect）**と呼びます。
```

2022-06-19 14:34 UTC, kazupon commented on src/guide/extras/reactivity-in-depth.md
> +     debugger
ここ英語と同じフォーマットにしておいてください。
```suggestion
    debugger
```

2022-06-20 11:13 UTC, jay-es commented
@hiro-lapis 別の PR でコード部分に変更が入っているので main の取り込みをお願いします:pray:

2022-06-20 13:00 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +Vue の最も特徴的な機能の 1 つは、控えめなリアクティビティシステムです。コンポーネントの状態はリアクティブな JavaScript オブジェクトです。状態を変更すると、ビューが更新されます。状態管理はシンプルで直感的ですが、よくある落とし穴を避けるために、仕組みを理解することも重要です。このセクションでは Vue のリアクティビティシステムのローレベルの詳細について、いくつか掘り下げていき
ありがとうございます、修正します！

2022-06-20 13:01 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +# リアクティビティの深み
リサーチ不足で失礼しました。
探求という表現とてもいいですね。
修正します！

2022-06-20 14:03 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +2. 実行中のエフェクトがあるときに変数が読み込まれた場合、エフェクトをその変数のサブスクライバーにします。例： `update()` が実行されているときに `A0` と `A1` が読み込まれるので、最初の呼び出し以降は `update()` が `A0` と `A1` の両方のサブスクライバーになります。
修正します！

2022-06-20 14:03 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +この時点で、依存関係を自動的に追跡し、依存関係が変更されるたびに再実行するエフェクトが作成しました。これを**リアクティブエフェクト**と呼びます。
承知しました、修正します！

2022-06-20 14:04 UTC, hiro-lapis commented on src/guide/extras/reactivity-in-depth.md
> +     debugger
失礼しました。修正します！

2022-06-20 14:06 UTC, hiro-lapis commented
@kazupon 
指摘いただいた訳の修正をしました。
都合よろしいときに確認おねがいします🙇‍♂️

2022-06-26 08:16 UTC, kazupon approved these changes
すいません、遅くなりました。LGTMです。

2022-06-26 08:17 UTC, merged