「Guide > Scaling Up > Routing」の翻訳
vuejs-translations/docs-ja pull request #643
Opened 2022-06-29 14:50 UTC by bobstrange

resolve #37

2022-06-30 09:55 UTC, jay-es requested changes
1箇所修正お願いします:pray:

2022-06-30 13:35 UTC, bobstrange commented
@jay-es 

レビューありがとうございます :bow:
suggestion の方を取り込みましたので、再度よろしくお願いします。

2022-07-01 10:06 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-07-04 12:39 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応のお願いします！

2022-07-04 12:39 UTC, kazupon commented on src/guide/scaling-up/routing.md
> +## 公式のルーター
以下のように助詞がなくてもよさそうです。
```suggestion
## 公式ルーター
```

2022-07-04 15:51 UTC, kazupon approved these changes

2022-07-04 15:51 UTC, merged