translate rendering-mechanism
vuejs-translations/docs-ja pull request #644
Opened 2022-06-30 04:00 UTC by hiro-lapis

resolve #51 

よろしくおねがいします🙇‍♂️

2022-06-30 04:02 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +Vue のテンプレートは、仮想 DOM レンダー関数にコンパイルされます。また、Vue はテンプレートのコンパイルステップをスキップしてレンダー関数を直接書ける API を提供しています。レンダー関数は、JavaScript のパワーすべてを使って vnode を操作できます。そのため、高度に動的なロジックを扱う場面において、テンプレートよりも柔軟性があります。
`Render functions ~`が長文かつやや複雑なので、2文に分けています。

2022-06-30 04:02 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +React の仮想 DOM 実装や他のほとんどの仮想 DOM 実装は純粋なランタイムです:照合アルゴリズムは入力される仮想 DOM ツリーを予想できないため、正確さの確保のためにツリー全体をトラバースして、すべての vnode のプロパティの差分を比較する必要があります。加えて、ツリーの一部が変更されない場合でも再レンダリングのたびに新しい vnode が作成されるため、不要なメモリー負荷が発生
reconciliation　(調停、和解、一致)の訳に迷いました。
一致のニュアンスをとって、照合と訳しています。

2022-06-30 10:47 UTC, jay-es requested changes
何点か修正お願いします:pray:

2022-06-30 10:47 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +ランタイムのレンダラーは、仮想 DOM ツリー内を移動して、実際の DOM ツリーを構築することができます。この処理を**マウント**と呼びます。
下にあわせて walk を「走査」に
```suggestion
ランタイムのレンダラーは、仮想 DOM ツリー内を走査して、実際の DOM ツリーを構築することができます。この処理を**マウント**と呼びます。
```

2022-06-30 10:47 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +仮想 DOM の主な利点は、DOM の直接的な操作はレンダリングシステムに任せ、開発者は宣言的な方法で希望する UI 構造をプログラム的に作成、検査、合成できることです。
```suggestion
仮想 DOM の主な利点は、DOM の直接的な操作はレンダラーに任せ、開発者は宣言的な方法で希望する UI 構造をプログラム的に作成、検査、合成できることです。
```

2022-06-30 10:47 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +上層レベルでは、Vue のコンポーネントがマウントされると、以下のようなことが起こります:
```suggestion
大まかには、Vue のコンポーネントがマウントされると、以下のようなことが起こります:
```

2022-06-30 10:47 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +2. **マウント**: ランタイムレンダラーはレンダー関数を呼び出し、返された仮想 DOM ツリーを走査して、それに基づいて実際の DOM ノードを作成します。このステップは、[reactive effect](./reactivity-in-depth) として実行されるため、使用されたすべての reactive dependencies を追跡します。
reactive dependencies も翻訳
```suggestion
2. **マウント**: ランタイムレンダラーはレンダー関数を呼び出し、返された仮想 DOM ツリーを走査して、それに基づいて実際の DOM ノードを作成します。このステップは、[reactive effect](./reactivity-in-depth) として実行されるため、使用されたすべてのリアクティブな依存関係を追跡します。
```

2022-06-30 10:47 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +3. **パッチ**: マウント中に使用される依存関係が変更されると、エフェクト（副作用）が再実行されます。このとき、更新された新しい仮想 DOM ツリーが作成されます。ランタイムレンダラーは新しいツリーを走査して、古いツリーと比較し、必要な更新を実際の DOM に適用します
```suggestion
3. **パッチ**: マウント中に使用される依存関係が変更されると、エフェクト（副作用）が再実行されます。このとき、更新された新しい仮想 DOM ツリーが作成されます。ランタイムレンダラーは新しいツリーを走査して、古いツリーと比較し、必要な更新を実際の DOM に適用します。
```

2022-06-30 10:47 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +### 静的ホスト
```suggestion
### 静的ホイスティング
```

2022-06-30 10:47 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +- ハイドレーション中は、ブロックノードとその動的な子孫ノードのみが渡される必要があり、テンプレートレベルでの部分的なハイドレーションが効果的に実現されています。
```suggestion
- ハイドレーション中は、ブロックノードとその動的な子孫ノードのみを走査すればよく、テンプレートレベルでの部分的なハイドレーションが効果的に実現されています。
```

2022-06-30 23:21 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +ランタイムのレンダラーは、仮想 DOM ツリー内を移動して、実際の DOM ツリーを構築することができます。この処理を**マウント**と呼びます。
表現は統一するべきでしたね。
修正します！

2022-06-30 23:22 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +仮想 DOM の主な利点は、DOM の直接的な操作はレンダリングシステムに任せ、開発者は宣言的な方法で希望する UI 構造をプログラム的に作成、検査、合成できることです。
修正します！

2022-06-30 23:23 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +2. **マウント**: ランタイムレンダラーはレンダー関数を呼び出し、返された仮想 DOM ツリーを走査して、それに基づいて実際の DOM ノードを作成します。このステップは、[reactive effect](./reactivity-in-depth) として実行されるため、使用されたすべての reactive dependencies を追跡します。
訳漏れ失礼しました。
修正します！

2022-06-30 23:23 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +3. **パッチ**: マウント中に使用される依存関係が変更されると、エフェクト（副作用）が再実行されます。このとき、更新された新しい仮想 DOM ツリーが作成されます。ランタイムレンダラーは新しいツリーを走査して、古いツリーと比較し、必要な更新を実際の DOM に適用します
修正します🙇‍♂️

2022-06-30 23:26 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +1. テンプレートは、実際の HTML に近いものになっています。これにより、既存の HTML スニペットの再利用、アクセシビリティベストプラクティスの適用、CSS によるスタイル付けが容易になり、デザイナーが理解し修正することができるようになります。
文意を読み取れず失礼しました、修正します！

2022-06-30 23:27 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +React の仮想 DOM 実装や他のほとんどの仮想 DOM 実装は純粋なランタイムです:照合アルゴリズムは入力される仮想 DOM ツリーを予想できないため、正確さの確保のためにツリー全体をトラバースして、すべての vnode のプロパティの差分を比較する必要があります。加えて、ツリーの一部が変更されない場合でも再レンダリングのたびに新しい vnode が作成されるため、不要なメモリー負荷が発生
そのほうがしっくりきますね、修正します！

2022-06-30 23:29 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +### 静的ホスト
修正します。

2022-06-30 23:33 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +このコンポーネントに再レンダリングが必要な場合、完全なツリーではなく、フラット化されたツリーのみを渡す必要があります。これは **ツリーのフラット化** と呼ばれ、仮想 DOM 照合時に走査する必要のあるノードの数を大幅に削減します。テンプレートの静的な部分は、すべて効果的にスキップされます。
指摘いただいた文章を少し意訳加えて、
`フラット化されたツリーを走査するだけでいいです。`
で修正させてもらいます。

不適切なようであれば指摘ください🙇‍♂️

2022-06-30 23:35 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +- ハイドレーション中は、ブロックノードとその動的な子孫ノードのみが渡される必要があり、テンプレートレベルでの部分的なハイドレーションが効果的に実現されています。
ポジティブな表現の方がしっくりきますね、修正します！

2022-07-01 10:22 UTC, jay-es requested changes
ありがとうございます！
1点修正お願いします:pray:

2022-07-01 10:22 UTC, jay-es commented on src/guide/extras/rendering-mechanism.md
> +## コンパイラー情報に基づく仮想
DOM が消えているので修正お願いします:pray:
```suggestion
## コンパイラー情報に基づく仮想 DOM
```

2022-07-01 15:49 UTC, hiro-lapis commented
@jay-es 
失礼しました🙇‍♂️
suggestを受け入れて修正させてもらいました。

2022-07-02 12:44 UTC, jay-es approved these changes
ありがとうございます！:pray:

2022-07-04 12:47 UTC, kazupon requested changes
いつも翻訳ありがとうございます！
レビューしました。確認お願いします！

2022-07-04 12:47 UTC, kazupon commented on src/guide/extras/rendering-mechanism.md
> +`foo` と `bar` の div たちは静的なので、再レンダリングのたびに vnode を再作成して差分を取ることは不要です。Vue コンパイラーは、vnode の作成呼び出しをレンダー関数から自動的に引き上げ（ホイスティング）、レンダリングのたびに同じ vnode を再利用します。また、レンダラーは、古い vnode と新しい vnode が同じものであることに気づいたときに、それらの差
`hoisting` は巻き上げと訳す方が多いですね。

```suggestion
`foo` と `bar` の div たちは静的なので、再レンダリングのたびに vnode を再作成して差分を取ることは不要です。Vue コンパイラーは、vnode の作成呼び出しをレンダー関数から自動的に巻き上げ（ホイスティング）、レンダリングのたびに同じ vnode を再利用します。また、レンダラーは、古い vnode と新しい vnode が同じものであることに気づいたときに、それらの差分比較を完全にスキップすることができます。
```

2022-07-06 05:41 UTC, hiro-lapis commented on src/guide/extras/rendering-mechanism.md
> +`foo` と `bar` の div たちは静的なので、再レンダリングのたびに vnode を再作成して差分を取ることは不要です。Vue コンパイラーは、vnode の作成呼び出しをレンダー関数から自動的に引き上げ（ホイスティング）、レンダリングのたびに同じ vnode を再利用します。また、レンダラーは、古い vnode と新しい vnode が同じものであることに気づいたときに、それらの差
こちらこそいつもありがとうございます！

hostingの訳、失礼しました。
suggest受け入れて修正させてもらいます。

2022-07-07 09:20 UTC, kazupon commented
@hiro-lapis ありがとうございました。マージします！

2022-07-07 09:20 UTC, merged