「Style Guide > Priority B Rules: Strongly Recommended」の翻訳
vuejs-translations/docs-ja pull request #689
Opened 2022-07-17 23:19 UTC by nabeken5

resolve #104

2022-07-19 12:30 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
>  <!-- In Single-File Components and string templates -->
このあたりのコメントも翻訳お願いします:pray:

2022-07-19 12:34 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
> +JavaScript では、クラスやプロトタイプのコンストラクタのためにパスカルケースを利用します。Vue のコンポーネントもインスタンスを持つので、パスカルケースを使用するのは理にかなっています。さらに、JSX（およびテンプレート）内でパスカルケースを使用すると、コードを読む人がコンポーネントと HTML 要素をより簡単に区別することができます。
`essentially, ~` の翻訳を追加
```suggestion
JavaScript では、クラスやプロトタイプのコンストラクターなど、基本的に個別のインスタンスを持つことができるすべてのもののためにパスカルケースを利用します。Vue のコンポーネントもインスタンスを持つので、パスカルケースを使用するのは理にかなっています。さらに、JSX（およびテンプレート）内でパスカルケースを使用すると、コードを読む人がコンポーネントと HTML 要素をより簡単に区別することができます。
```

2022-07-19 12:34 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
> +しかし、`app.component` によるグローバルなコンポーネント定義のみを使用するアプリケーションでは、代わりにケバブケース(kebab-case)を使用することをお勧めします。理由は以下の通りです。
```suggestion
しかし、`app.component` によるグローバルなコンポーネント定義**のみ**を使用するアプリケーションでは、代わりにケバブケース(kebab-case)を使用することをお勧めします。理由は以下の通りです。
```

2022-07-19 12:40 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
> +長い名前によってもたらされる明快さは非常に貴重ですが、それをタイプする労力はエディターの自動補完によってとても小さくなります。特に、一般的でない略語は常に避けるべきです。
逆接から順接に変更
```suggestion
長い名前によってもたらされる明快さは非常に貴重ですし、それをタイプする労力はエディターの自動補完によってとても小さくなります。特に、一般的でない略語は常に避けるべきです。
```

2022-07-19 12:42 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
> +私たちは単純にこの慣習に従っています。JavaScript の中ではキャメルケースがより自然で、HTML の中ではケバブケースが自然です。
`each language` の訳を追加

```suggestion
私たちは単に各言語の慣習に従っているだけです。JavaScript の中ではキャメルケースがより自然で、HTML の中ではケバブケースが自然です。
```

2022-07-19 12:50 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
> +## 用符付きの属性値
```suggestion
## 引用符付きの属性値
```

2022-07-20 11:43 UTC, nabeken5 commented
修正しました。
ありがとうございます。

2022-07-20 12:30 UTC, kazupon requested changes
レビュー 👀  コメント 💬  しました。
確認お願いします！

2022-07-20 12:30 UTC, kazupon commented on src/style-guide/rules-strongly-recommended.md
> +- これらのコンポーネントは頻繁に使用されるので、あらゆる場所で import するのではなく、単純にグローバル化してしまいたいと思うかもしれません。プレフィックスを利用すれば、Webpack でできるようになります:
少し違和感があったので、以下のように少し補完ぎみで翻訳するとよいかと思います。

```suggestion
- これらのコンポーネントは頻繁に使用されるので、あらゆる場所で import するのではなく、単純にグローバル化してしまいたいと思うかもしれません。プレフィックスを利用すれば、Webpack で以下ができるようになります:
```

2022-07-21 12:09 UTC, jay-es requested changes
修正ありがとうございます。
394, 399, 404, 414, 419, 426 行目のコメントが英語のままなので、翻訳お願いします:pray:

2022-07-22 10:50 UTC, jay-es requested changes
スペース追加お願いします:pray:

2022-07-22 10:50 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
> +<!-- DOMテンプレートの中 -->
```suggestion
<!-- DOM テンプレートの中 -->
```

2022-07-22 10:50 UTC, jay-es commented on src/style-guide/rules-strongly-recommended.md
> +<!-- DOMテンプレートの中 -->
```suggestion
<!-- DOM テンプレートの中 -->
```

2022-07-25 15:28 UTC, kazupon commented
jay-es さんの suggestionsを取り込んで、全て対応されているようなので、マージします！

2022-07-25 15:29 UTC, merged