「Guide > Reusability > Custom Directives」の翻訳
vuejs-translations/docs-ja pull request #703
Opened 2022-07-25 14:49 UTC by hiro-lapis

resolve #28 

お待たせしてすみません。
今回もよろしくおねがいします🙇‍♂️

2022-07-25 15:35 UTC, kazupon approved these changes
確認 👀 しました。
よさそうです！

2022-07-26 12:04 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

また、219, 221 行目のコメントも翻訳お願いします:pray:

2022-07-26 12:04 UTC, jay-es commented on src/guide/reusability/custom-directives.md
> +`el` 以外のディレクティブの引数は、読み取り専用として扱い、決して変更しないようにしましょう。フック間で情報を共有する必要がある場合は、エレメントの [dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) を通して行うことを推奨します。
日本語版に変更
```suggestion
`el` 以外のディレクティブの引数は、読み取り専用として扱い、決して変更しないようにしましょう。フック間で情報を共有する必要がある場合は、要素の [dataset](https://developer.mozilla.org/ja/docs/Web/API/HTMLElement/dataset) を通して行うことを推奨します。
```

2022-07-27 04:39 UTC, hiro-lapis commented on src/guide/reusability/custom-directives.md
> +Vue におけるコードの再利用として 2 つの方法を紹介してきました:[components](/guide/essentials/component-basics.html) と [composables](./composables) です。components はメインブロックの構築、composables はステートフルなロジックの再利用に重点を置いています。一方、カスタムディレクティブ
失礼しました。修正します！

2022-07-27 04:39 UTC, hiro-lapis commented on src/guide/reusability/custom-directives.md
> +カスタムディレクティブは DOM を直接操作することでしか必要な機能を実現できない場合にのみ使用してください。`v-bind` のような組み込みディレクティブは宣言的なテンプレートは、効率的かつサーバレンダリングフレンドリーです。可能なかぎり組み込みディレクティブを使用することをおすすめします。
変な訳になってましたね。。。修正します。

2022-07-27 04:40 UTC, hiro-lapis commented on src/guide/reusability/custom-directives.md
> +  // もしくはイベントリスナーが適用される前に呼ばれます
ありがとうございます、
その方が意味としても適切ですね、修正します！

2022-07-27 04:40 UTC, hiro-lapis commented on src/guide/reusability/custom-directives.md
> +  // すべての子要素がマウントされた時に呼ばれます
修正します！

2022-07-27 04:41 UTC, hiro-lapis commented on src/guide/reusability/custom-directives.md
> +  - `arg`: ディレクティブに渡される引数がある場合に存在する引数。例えば `v-my-directive:foo` の場合、引数は `"foo"` となります。 - `modifiers`: 修飾子がある時に、それを含むオブジェクト。例えば `v-my-directive.foo.bar` の場合、修飾子オブジェクトは `{ foo: true, bar: true }` となります。
失礼しました、修正します！

2022-07-27 04:41 UTC, hiro-lapis commented on src/guide/reusability/custom-directives.md
> +  oldValue: /* 前回の更新による value `baz` */
修正します。

2022-07-27 04:42 UTC, hiro-lapis commented on src/guide/reusability/custom-directives.md
> +`el` 以外のディレクティブの引数は、読み取り専用として扱い、決して変更しないようにしましょう。フック間で情報を共有する必要がある場合は、エレメントの [dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) を通して行うことを推奨します。
ありがとうございます、修正します！

2022-07-27 04:43 UTC, hiro-lapis commented
@jay-es 
ありがとうございます、修正しました。
ご都合のいい時に確認いただけますか🙇‍♂️

2022-07-27 11:23 UTC, jay-es approved these changes
確認しました！ありがとうございます:pray:

2022-07-27 11:23 UTC, merged