「Guide > Extra Topics > Render Functions & JSX」の翻訳
vuejs-translations/docs-ja pull request #830
Opened 2022-08-30 03:16 UTC by KanDai

resolve #52 

時間かかってしまいすみません！よろしくお願いします！

1点気になったので確認させてください。

`.composition-api` に `display: none` がかかっていてページに表示されていなかったんですが、これは意図通りの挙動でしょうか？(参照)

添付画像 `composition-api` 部分が表示されておらず、 `options-api` 部分は表示されています。

![PixelSnap 2022-08-30 at 12 13 37@2x](https://user-images.githubusercontent.com/3655103/187340686-293781a0-e493-4f24-886c-2a2c512cab64.png)

![PixelSnap 2022-08-30 at 12 14 15@2x](https://user-images.githubusercontent.com/3655103/187340757-9fc6323f-230e-4f52-9e8c-28c4e9a024da.png)

2022-08-30 11:25 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

`.composition-api` などについては、メニューのトグルで表示が切り替わります
![image](https://user-images.githubusercontent.com/46585162/187424643-f26330a3-a5ec-4ef8-b1a1-8e26a56b8313.png)

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +出来上がった vnode は以下のようになります。
```suggestion
出来上がった vnode は以下のようになります:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +コンポーネントツリー内のすべての vnode は一意でなければなりません。つまり、以下の render 関数は無効です。
```suggestion
コンポーネントツリー内のすべての vnode は一意でなければなりません。つまり、以下の render 関数は無効です:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +  // `items` が配列の値を持つ参照であると仮定する
```suggestion
  // `items` が配列の値を持つ ref であると仮定する
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +コンポーネント用の vnode を作成するには、`h()` に渡される最初の引数はコンポーネントの定義でなければなりません。つまり、render 関数を使う場合、コンポーネントを登録する必要はなく、インポートされたコンポーネントを直接使えばいいのです。
```suggestion
コンポーネント用の vnode を作成するには、`h()` に渡される最初の引数はコンポーネントの定義でなければなりません。つまり、render 関数を使う場合、コンポーネントを登録する必要はなく、インポートされたコンポーネントを直接使えばいいのです:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +動的なコンポーネントは、render 関数を使えば簡単です。
```suggestion
動的なコンポーネントは、render 関数を使えば簡単です:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +レンダーファンクションでは、スロットは `setup()` コンテキストからアクセスすることができます。`slots` オブジェクトの各スロットは、**vnodes の配列を返す関数** です。
```suggestion
render 関数では、スロットは `setup()` コンテキストからアクセスすることができます。`slots` オブジェクトの各スロットは、**vnode の配列を返す関数** です:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +### パッシングスロット
```suggestion
### スロットの渡し方
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +- コンポーネントへの子要素の渡し方（スロットなど）が[異なります](#パッシングスロット)。
```suggestion
- コンポーネントへの子要素の渡し方（スロットなど）が[異なります](#スロットの渡し方)。
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +// シングルデフォルトスロット
```suggestion
// 単一のデフォルトスロット
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +// スロットのオブジェクトがプロップスとして扱われるのを避けるために、
```suggestion
// スロットのオブジェクトが props として扱われるのを避けるために、
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +// `null`が必要であることに注意してください。
```suggestion
// `null` が必要であることに注意してください。
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +    return () => h(Transition, { mode: 'out-in' } /* ... */)
```suggestion
  setup () {
    return () => h(Transition, { mode: 'out-in' }, /* ... */)
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +    return h(Transition, { mode: 'out-in' } /* ... */)
```suggestion
  render () {
    return h(Transition, { mode: 'out-in' }, /* ... */)
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +`v-model` ディレクティブは、テンプレートのコンパイル時に `modelValue` と `onUpdate:modelValue` プロパティに展開されます。
```suggestion
`v-model` ディレクティブは、テンプレートのコンパイル時に `modelValue` と `onUpdate:modelValue` プロパティに展開されます:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +カスタムディレクティブは、[`withDirectives`](/api/render-function.html#withdirectives)を使って vnode に適用することが可能です。
```suggestion
カスタムディレクティブは、[`withDirectives`](/api/render-function.html#withdirectives)を使って vnode に適用することが可能です:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +関数型コンポーネントのシグネチャは `setup()` フックと同じです。
```suggestion
関数型コンポーネントのシグネチャは `setup()` フックと同じです:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +関数型コンポーネントに `this` という参照はないので、Vue は最初の引数として `props` を渡します。
```suggestion
関数型コンポーネントに `this` という参照はないので、Vue は最初の引数として `props` を渡します:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +コンポーネントに対する通常の設定オプションのほとんどは、関数型コンポーネントでは使用できません。しかし、[`props`](/api/options-state.html#props) と [`emits`](/api/options-state.html#emits) はプロパティとして追加することで定義することが可能です。
```suggestion
コンポーネントに対する通常の設定オプションのほとんどは、関数型コンポーネントでは使用できません。しかし、[`props`](/api/options-state.html#props) と [`emits`](/api/options-state.html#emits) はプロパティとして追加することで定義することが可能です:
```

2022-08-30 11:25 UTC, jay-es commented on src/guide/extras/render-function.md
> +関数型コンポーネントは、通常のコンポーネントと同様に登録や消費を行うことができます。もし、`h()` の第一引数に関数を渡した場合、それは関数型コンポーネントとして扱われます。
```suggestion
関数型コンポーネントは、通常のコンポーネントと同様に登録や使用ができます。もし、`h()` の第一引数に関数を渡した場合、それは関数型コンポーネントとして扱われます。
```

2022-08-30 11:42 UTC, KanDai commented
@jay-es 
レビューありがとうございます！基本的なスタイルのところでミスが多くて失礼しました。

確認して修正します！

> `.composition-api` などについては、メニューのトグルで表示が切り替わります

なるほど、見落としていました。ありがとうございます！

2022-08-30 12:17 UTC, KanDai commented
suggestion 確認して適用させていただきました！
自分でも見直して一部修正しました。

2022-08-31 12:53 UTC, jay-es approved these changes
ありがとうございます！
自分は OK です:pray:

2022-09-02 03:46 UTC, kazupon approved these changes
すいません。遅くなりました。
大丈夫でそうです！
ありがとうございました！

2022-09-02 03:46 UTC, merged