translate api/application.md
vuejs-translations/docs-ja pull request #845
Opened 2022-09-04 13:39 UTC by syusn0227

resolve #59

2022-09-06 13:59 UTC, jay-es requested changes
レビューしました。
何点か修正お願いします:pray:

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +[SSR hydration (ハイドレーション) ](/guide/scaling-up/ssr.html#client-hydration)モードでアプリケーションインスタンスを作成します。使用法は `createApp()` と全く同じです。
リンク修正お願いします:pray:
```suggestion
[SSR hydration (ハイドレーション) ](/guide/scaling-up/ssr.html#クライアント・ハイドレーション)モードでアプリケーションインスタンスを作成します。使用法は `createApp()` と全く同じです。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +  SSR ハイドレーションモードでは、コンテナ内の既存の DOM ノードをハイドレートします。[ミスマッチ](/guide/scaling-up/ssr.html#hydration-mismatch)があった場合、既存の DOM ノードは期待される結果に合うよう変化されます。
```suggestion
  SSR ハイドレーションモードでは、コンテナ内の既存の DOM ノードをハイドレートします。[ミスマッチ](/guide/scaling-up/ssr.html#ハイドレーション・ミスマッチ)があった場合、既存の DOM ノードは期待される結果に合うよう変化されます。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +マウントしたアプリケーションインスタンスをアンマウトし、アプリケーションのコンポーネントツリーにあるすべてのコンポーネントに対して、ライフサイクルフックの unmount を呼び出します。
```suggestion
マウントしたアプリケーションインスタンスをアンマウントし、アプリケーションのコンポーネントツリーにあるすべてのコンポーネントに対して、ライフサイクルフックの unmount を呼び出します。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +  - [アプリケーションレベルの Provide ](/guide/components/provide-inject.html#app-level-provide)
```suggestion
  - [アプリケーションレベルの Provide](/guide/components/provide-inject.html#アプリケーションレベルの-provide)
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +ミックインはエコシステムのライブラリーで幅広く使用していることから、主に後方互換性ため、Vue 3 でサポートしています。ミックイン (特にグローバルミックスイン) はアプリケーションコードでは避けるべきです。
```suggestion
ミックインはエコシステムのライブラリーで幅広く使用されていることから、主に後方互換性のため、Vue 3 でサポートしています。ミックイン (特にグローバルミックスイン) はアプリケーションコードでは避けるべきです。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +  プラグイン内でバージョンチェックを行います。
```suggestion
  プラグイン内でバージョンチェックを行います:
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +      // 例 エラーがthrowされたのはどのライフサイクルフックか
```suggestion
      // 例 エラーが throw されたのはどのライフサイクルフックか
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +  警告ハンドラーは、第 1 引数として警告メッセージ、第 2 引数としてソースコンポーネントのインスタンス、第 3 引数としてコンポーネントトーレスの文字列を受け取ります。
```suggestion
  警告ハンドラーは、第 1 引数として警告メッセージ、第 2 引数としてソースコンポーネントのインスタンス、第 3 引数としてコンポーネントトレースの文字列を受け取ります。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +これを `true` に設定することで、ブラウザーの開発ツールの performance/timeline パネルで、コンポーネントの初期化、コンパイル、レンダリング、パッチについてのパフォーマンスのトレースが有効となります。 開発モードおよび[ performance.mark ](https://developer.mozilla.org/en-US/docs/Web/API/Perform
```suggestion
これを `true` に設定することで、ブラウザーの開発ツールの performance/timeline パネルで、コンポーネントの初期化、コンパイル、レンダリング、パッチについてのパフォーマンスのトレースが有効となります。 開発モードおよび [performance.mark](https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark) API をサポートするブラウザーでのみ動作します。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +- `vue-loader` の場合: [`compilerOptions` ローダオプションによって渡す](https://vue-loader.vuejs.org/options.html#compileroptions). 参照 [`vue-cli` での設定方法](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-
```suggestion
- `vue-loader` の場合: [`compilerOptions` ローダーオプションによって渡す](https://vue-loader.vuejs.org/options.html#compileroptions)。[`vue-cli` での設定方法](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader)も参照してください。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +ネイティブカスタム要素を認識するため、チェックメソッドを指定する。
```suggestion
ネイティブカスタム要素を認識するためのチェックメソッドを指定する。
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +    // self からのオプション
```suggestion
    // 自身のオプション
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +      // this.$options に公開されているマージオプション
```suggestion
      // this.$options に公開されているマージされたオプション
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +  これにより、アプリケーションのコンポーネントテンプレート内およびコンポーネントインスタンスの `this` でも、`msg` を使用できるようになります。
```suggestion
  これにより、アプリケーションのコンポーネントテンプレート内およびコンポーネントインスタンスの `this` でも、`msg` を使用できるようになります:
```

2022-09-06 13:59 UTC, jay-es commented on src/api/application.md
> +  以下のソースから、エラーを捕捉することができます。
```suggestion
  以下のソースから、エラーを捕捉することができます:
```

2022-09-07 14:11 UTC, kazupon approved these changes
翻訳ありがとうございます！
内容確認しました 👀 
よさそうです！

2022-09-07 14:46 UTC, syusn0227 commented
@jay-es 

レビューありがとうございます！
修正しましたので、確認お願いします🙏

2022-09-08 12:26 UTC, jay-es requested changes
ありがとうございます！
2 箇所修正お願いします:pray:

2022-09-08 12:26 UTC, jay-es commented on src/api/application.md
> +ミックインはエコシステムのライブラリーで幅広く使用されていることから、主に後方互換性ため、Vue 3 でサポートしています。ミックイン (特にグローバルミックスイン) はアプリケーションコードでは避けるべきです。
前回 suggestion の修正漏れ
```suggestion
ミックインはエコシステムのライブラリーで幅広く使用されていることから、主に後方互換性のため、Vue 3 でサポートしています。ミックイン (特にグローバルミックスイン) はアプリケーションコードでは避けるべきです。
```

2022-09-08 12:26 UTC, jay-es commented on src/api/application.md
> +これを `true` に設定することで、ブラウザーの開発ツールの performance/timeline パネルで、コンポーネントの初期化、コンパイル、レンダリング、パッチについてのパフォーマンスのトレースが有効となります。 開発モードおよび [performance.mark](https://developer.mozilla.org/en-US/docs/Web/API/Performa
前回見落としていましたが、日本語版のリンクに変更お願いします:pray:
```suggestion
これを `true` に設定することで、ブラウザーの開発ツールの performance/timeline パネルで、コンポーネントの初期化、コンパイル、レンダリング、パッチについてのパフォーマンスのトレースが有効となります。 開発モードおよび [performance.mark](https://developer.mozilla.org/ja/docs/Web/API/Performance/mark) API をサポートするブラウザーでのみ動作します。
```

2022-09-08 14:24 UTC, syusn0227 commented
再度修正しました。
確認お願いします🙇‍♂️

2022-09-10 08:33 UTC, jay-es approved these changes
修正ありがとうございました！:pray:

2022-09-10 08:34 UTC, merged