i18n 対応
vuejs-translations/docs-ja pull request #857
Opened 2022-09-12 10:57 UTC by jay-es

ページコンテンツ以外の英語箇所を翻訳しました

2022-09-12 10:59 UTC, jay-es commented on .vitepress/config.ts
>        copyright: `Copyright © 2014-${new Date().getFullYear()} Evan You`
中国版では「この中国語ドキュメントの内容の著作権は、Vue公式チームと翻訳協力者にあり、すべての権利は留保されています。」のような内容になっているので、同じように変更すべきかどうか...

2022-09-13 15:27 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました！
コメントしたところの対応お願いします。

2022-09-13 15:27 UTC, kazupon commented on .vitepress/config.ts
>        copyright: `Copyright © 2014-${new Date().getFullYear()} Evan You`
中国でそのライセンスにしたのは、Evan氏ですね。
https://github.com/vuejs-translations/docs-zh-cn/commit/4ff4a5a7ec562d0ff1bd26d44e490f3c7c802ae2

なので、同じようにしておいた方がいいのと、翻訳ドキュメントはまさにそのとおりだと思うので。

2022-09-14 10:57 UTC, jay-es commented on .vitepress/config.ts
>        copyright: `Copyright © 2014-${new Date().getFullYear()} Evan You`
copyright 部分を修正しました

2022-09-14 14:36 UTC, kazupon commented
ありがとうございます！マージしますー

2022-09-14 14:36 UTC, merged