「API > Options API > Options: Lifecycle」の翻訳
vuejs-translations/docs-ja pull request #876
Opened 2022-09-25 07:09 UTC by jay-es

resolve #69

内容は前回 PR の [Composition API のページ](https://github.com/vuejs-translations/docs-ja/pull/875/files)とほぼ同じです。
よろしくお願いします！

2022-09-30 15:52 UTC, kazupon commented on src/api/options-lifecycle.md
> +  - そのコンポーネント自身の DOM ツリーが作成され、親コンテナーに挿入された。アプリケーションのルートコンテナが document 内にある場合のみ、そのコンポーネントの DOM ツリーも document 内にあることを保証することに注意してください。
`挿入された。` で終わるの不自然なので以下のようにすると自然が文章になりそうです。

```suggestion
  - そのコンポーネント自身の DOM ツリーが作成され、親コンテナーに挿入されます。アプリケーションのルートコンテナが document 内にある場合のみ、そのコンポーネントの DOM ツリーも document 内にあることを保証することに注意してください。
```

2022-09-30 15:55 UTC, kazupon commented on src/api/options-lifecycle.md
> +  - イベント ハンドラー
ここは空白入れる必要なさそうです。
```suggestion
  - イベントハンドラー
```

2022-09-30 15:57 UTC, kazupon requested changes
レビュー 👀 コメント 💬 しました。
対応お願いします！

2022-10-02 11:04 UTC, jay-es commented on src/api/options-lifecycle.md
> +  - イベント ハンドラー
下の行の「ライフサイクル フック」と、composition-api-lifecycle.md の同じ箇所も修正しました

2022-10-02 11:06 UTC, jay-es commented on src/api/options-lifecycle.md
> +  - そのコンポーネント自身の DOM ツリーが作成され、親コンテナーに挿入された。アプリケーションのルートコンテナが document 内にある場合のみ、そのコンポーネントの DOM ツリーも document 内にあることを保証することに注意してください。
こちらは「された時」に修正しました。
（関連箇所や composition-api-lifecycle.md も同様に修正）

2022-10-02 11:41 UTC, kazupon commented
いつもありがとうございます！ 💚 
LGTMです！

2022-10-02 11:41 UTC, kazupon approved these changes

2022-10-02 11:41 UTC, merged