translate about/releases.md
vuejs-translations/docs-ja pull request #967
Opened 2022-11-08 12:23 UTC by Amplil

about/releases.md の翻訳をしました。
レビューよろしくお願いします。
resolve #109

2022-11-09 12:23 UTC, jay-es commented on src/about/releases.md
> +### コンパイルされたコードの以前の実行時との互換性
ここの runtime は「ランタイム」でよいと思います（ランタイムモジュール的な意味合い）
```suggestion
### コンパイルされたコードの以前のランタイムとの互換性
```

2022-11-09 12:34 UTC, jay-es commented on src/about/releases.md
> +アプリケーションでは、コンパイラーバージョンや実行時バージョンが常に同じなので、このことはライブラリーの著者に対する懸念のみがあります。パッケージとしてプリコンパイルされた Vue コンポーネントコードを出す場合にのみ、バージョン不一致は起こる可能性があり、コンシューマーは Vue の以前のバージョンを使用しているプロジェクトでそれを使用します。結果として、あなたのパッケージ Vue のマイナー
2文目が原文と少し変わっていたので修正しました
```suggestion
アプリケーションでは、コンパイラーバージョンとランタイムのバージョンは常に同じなので、このことはライブラリー作成者に対してのみの懸念事項です。バージョンの不一致は、コンパイル済みの Vue コンポーネントコードをパッケージとして出荷し、利用者が古いバージョンの Vue を使用するプロジェクトでそれを使用する場合にのみ発生します。結果として、あなたのパッケージ Vue のマイナーバージョンの最小条件を明示的に宣言する必要が出てくる可能性があります。
```

2022-11-09 12:40 UTC, jay-es commented on src/about/releases.md
> +実質的な API サーフェスに対する新機能と Vue への主要な変更は、**Request for Comments** (RFC) プロセスを通過します。RFC プロセスは、フレームワークを導入することで一貫してコントロールされた経路を新機能に提供し、参加やデザインプロセスのフィードバックをする機会をユーザーに与えることを目的とします
後半が原文と異なっていなので修正しました
```suggestion
実質的な API サーフェスに対する新機能と Vue への主要な変更は、**Request for Comments** (RFC) プロセスを通過します。RFC プロセスは、新機能がフレームワークに導入されるための一貫して管理された経路を提供し、ユーザーが設計プロセスに参加してフィードバックをする機会を与えることを目的とします。
```

2022-11-09 12:42 UTC, jay-es commented on src/about/releases.md
> +現在の安定版の Vue の最新バージョンは <strong>{{ version }}</strong> です。
（細かいですが）原文に合わせ順番入れ替え
```suggestion
現在の最新版の Vue の安定バージョンは <strong>{{ version }}</strong> です。
```

2022-11-09 12:50 UTC, jay-es commented on src/about/releases.md
> +ある機能は Vue の安定したバージョンで出され文書化されますが、実験用として指定されます。実験的機能は通常、理論的に解決された設計上の問題の大部分に関連する RFC の議論がある機能ですが、実際の使用からのフィードバックはまだ不足しています。
```suggestion
Vue の安定したバージョンで出され、ドキュメント化されますが、実験的として指定される機能もあります。実験的機能は通常、理論的には設計上の問題の大部分が解決された、関連する RFC の議論がある機能ですが、実際の使用からのフィードバックはまだ不足しています。
```

2022-11-09 15:02 UTC, Amplil commented
修正しました。
ありがとうございました。

2022-11-10 09:50 UTC, jay-es approved these changes
ありがとうございます！:pray:
自分はOKです

2022-11-14 09:03 UTC, kazupon commented on src/about/releases.md
> +実質的な API サーフェスに対する新機能と Vue への主要な変更は、**Request for Comments** (RFC) プロセスを通過します。RFC プロセスは、新機能がフレームワークに導入されるための一貫して管理された経路を提供し、ユーザーが設計プロセスに参加してフィードバックをする機会を与えることを目的とします。
`API surface ` は日本語で表現するのが難しいので、翻訳は `API サーフェス` ではなく、文章の文脈上、単純に `API` でも通じるので、`API に対する新機能` でどうでしょうか。

2022-11-14 10:00 UTC, Amplil commented on src/about/releases.md
> +実質的な API サーフェスに対する新機能と Vue への主要な変更は、**Request for Comments** (RFC) プロセスを通過します。RFC プロセスは、新機能がフレームワークに導入されるための一貫して管理された経路を提供し、ユーザーが設計プロセスに参加してフィードバックをする機会を与えることを目的とします。
ご指摘ありがとうございます。

2022-11-14 10:00 UTC, Amplil commented
ありがとうございます。
修正しました。

2022-11-14 10:27 UTC, jay-es requested changes
コメント分かりづらくてすみません:bow:
16 行目だけでなく、27, 37, 41, 51, 57, 63, 67, 73 行目にも差分があるので、同様に対応お願いします:pray:
https://github.com/vuejs-translations/docs-ja/pull/963/files#diff-7e86828390505e97c3ee6bcc99716b013fb9ec74d4570484ef1839c41e335d08

2022-11-14 10:29 UTC, Amplil commented
ありがとうございます。
修正しました。

2022-11-14 10:41 UTC, jay-es approved these changes
ありがとうございます。
kazupon さんの箇所もよさそうなのでマージします

2022-11-14 10:42 UTC, merged